In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture

In [2]:
def matriz_conf(y_true, y_pred, labels):
    total_labels = labels
    print(total_labels)
    cm = np.zeros((len(total_labels),len(total_labels)), dtype=int)
    for i in range(len(y_true)):
        cm[int(y_true[i])][y_pred[i]] += 1

    
    cm = pd.DataFrame(cm, columns=total_labels, index=total_labels)

    cm_transp = pd.DataFrame(np.transpose(cm.to_numpy()), columns=total_labels, index=total_labels)

    for c in cm_transp.columns:
        cm_transp[c] = cm_transp[c]/cm_transp[c].sum()

    cm_porcento = pd.DataFrame(np.transpose(cm_transp.to_numpy()), columns=total_labels, index=total_labels)

    return cm, cm_porcento

def acc(cm, hidden_classes):
    cm_transp = pd.DataFrame(np.transpose(cm.dropna().to_numpy()), columns=cm.columns, index=cm.columns)
    acc = 0
    total = 0
    for c in cm_transp.columns:
        if c not in hidden_classes:
            acc += cm_transp[c][c]
        else:
            acc += cm_transp[c][-1]
        total += cm_transp[c].sum()
    return acc/total

In [3]:
filenames = [0,2,3,4,5]

labels_str = ['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

filenames

# pd.set_option('future.no_silent_downcasting', True)

[0, 2, 3, 4, 5]

In [4]:
exp_val = []
y_true_all_exp_val = []
for i in range(len(filenames)):
    exp_val.append(pd.read_csv(f'val_{filenames[i]}_GMM_BIC_1_10_scores.csv'))
    y_true_all_exp_val.append(exp_val[i]['Label'].values.tolist())
    exp_val[i] = exp_val[i].drop(columns=['Label'])

In [5]:
from sklearn.metrics import classification_report
ths = [20, 20.5, 21, 21.5, 22, 23, 24, 25]
f1s = [[],[],[],[],[],[],[],[]]
for i in range(len(exp_val)):
    index = 0
    for th in ths:
        y_pred = []
        prog= 0
        for j in range(len(exp_val[i])):
            # print(exp[i][j])
            m = np.nanmax(exp_val[i].values[j])
            # print(m)
            if m > th:
                y_pred.append(exp_val[i].values[j].tolist().index(m))
            else:
                y_pred.append(-1)
        # print(y_pred[:10])

        cm, cm_porcento = matriz_conf(y_true_all_exp_val[i], y_pred, list(range(len(labels_str))) + [-1])
        print(f'th = {th} hidden = {filenames[i]}')
        display(cm)
        tp = cm[-1][filenames[i]]
        fp = cm[-1].sum() - tp
        fn = cm.iloc[filenames[i]].sum() - tp
        tn = cm.drop(columns=[-1]).values.sum() - fn

        acc = (tp+tn)/(tp+fp+tn+fn)
        recall = tp/(tp+fn)
        precision = tp/(tp+fp)
        if precision == 0 or recall == 0:
            f1 = 0
        else:
            f1 = 2*precision*recall/(precision+recall)

        f1s[index].append(f1)
        index += 1
        print(f'th: {th} hidden: {filenames[i]} acc:{acc} recall:{recall} precision:{precision} f1:{f1}')

        true_labels = np.array(y_true_all_exp_val[i])
        true_labels[true_labels == filenames[i]] = -1

        print('MULTICLASS DETECTION')
        print(classification_report(true_labels, y_pred))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 0

     0   1      2      3      4   5      -1
 0   0   0      0      0      0   0  202228
 1   0   0      0      0      0  48  128488
 2   0   0  64293      0      0   0   18012
 3   0   0      0  42877      0   0   18073
 4   0   0      0      0  40287   0    5503
 5   0   0      0      0      4  24     119
-1   0   0      0      0      0   0       0

th: 20 hidden: 0 acc:0.6726742262806853 recall:1.0 precision:0.5430062053095539 f1:0.7038289326913204
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.54      1.00      0.70    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.78      0.88     82305
           3       1.00      0.70      0.83     60950
           4       1.00      0.88      0.94     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.67    519956
   macro avg       0.65      0.59      0.59    519956
weighted avg       0.57      0.67      0.59    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 0

     0   1      2      3      4   5      -1
 0   0   0      0      0      0   0  202228
 1   0   0      0      0      0  48  128488
 2   0   0  64060      0      0   0   18245
 3   0   0      0  41855      0   0   19095
 4   0   0      0      0  40103   0    5687
 5   0   0      0      0      4  24     119
-1   0   0      0      0      0   0       0

th: 20.5 hidden: 0 acc:0.6699066844117579 recall:1.0 precision:0.5409161669279039 f1:0.7020708569841518
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.54      1.00      0.70    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.78      0.88     82305
           3       1.00      0.69      0.81     60950
           4       1.00      0.88      0.93     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.67    519956
   macro avg       0.65      0.58      0.59    519956
weighted avg       0.57      0.67      0.59    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0

     0   1      2      3      4   5      -1
 0   0   0      0      0      0   0  202228
 1   0   0      0      0      0  48  128488
 2   0   0  63817      0      0   0   18488
 3   0   0      0  39728      0   0   21222
 4   0   0      0      0  39608   0    6182
 5   0   0      0      0      2  24     121
-1   0   0      0      0      0   0       0

th: 21 hidden: 0 acc:0.6643927563101493 recall:1.0 precision:0.5367996623567605 f1:0.6985941961147375
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.54      1.00      0.70    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.78      0.87     82305
           3       1.00      0.65      0.79     60950
           4       1.00      0.86      0.93     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.66    519956
   macro avg       0.65      0.58      0.58    519956
weighted avg       0.57      0.66      0.58    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 0

     0   1      2      3      4   5      -1
 0   0   0      0      0      0   0  202228
 1   0   0      0      0      0  48  128488
 2   0   0  63579      0      0   0   18726
 3   0   0      0  38087      0   0   22863
 4   0   0      0      0  37683   0    8107
 5   0   0      0      0      0  24     123
-1   0   0      0      0      0   0       0

th: 21.5 hidden: 0 acc:0.6570729061689835 recall:1.0 precision:0.5314307488141695 f1:0.694031707572375
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.53      1.00      0.69    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.77      0.87     82305
           3       1.00      0.62      0.77     60950
           4       1.00      0.82      0.90     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.66    519956
   macro avg       0.64      0.56      0.58    519956
weighted avg       0.57      0.66      0.58    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 0

     0   1      2      3      4   5      -1
 0   0   0      0      0      0   0  202228
 1   0   0      0      0      0  48  128488
 2   0   0  63322      0      0   0   18983
 3   0   0      0  37765      0   0   23185
 4   0   0      0      0  34093   0   11697
 5   0   0      0      0      0  24     123
-1   0   0      0      0      0   0       0

th: 22 hidden: 0 acc:0.649054920031695 recall:1.0 precision:0.5256716852437199 f1:0.6891019743343352
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.53      1.00      0.69    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.77      0.87     82305
           3       1.00      0.62      0.77     60950
           4       1.00      0.74      0.85     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.65    519956
   macro avg       0.64      0.55      0.57    519956
weighted avg       0.57      0.65      0.57    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 0

     0   1      2      3      4   5      -1
 0   0   0      0      0      0   0  202228
 1   0   0      0      0      0  48  128488
 2   0   0  62631      0      0   0   19674
 3   0   0      0  36249      0   0   24701
 4   0   0      0      0  20358   0   25432
 5   0   0      0      0      0  24     123
-1   0   0      0      0      0   0       0

th: 23 hidden: 0 acc:0.6183946333920562 recall:1.0 precision:0.5047548209641429 f1:0.6708798190003218
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.50      1.00      0.67    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.76      0.86     82305
           3       1.00      0.59      0.75     60950
           4       1.00      0.44      0.62     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.62    519956
   macro avg       0.64      0.49      0.52    519956
weighted avg       0.56      0.62      0.54    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 0

     0   1      2      3      4   5      -1
 0   0   0      0      0      0   0  202228
 1   0   0      0      0      0  48  128488
 2   0   0  61673      0      0   0   20632
 3   0   0      0  36249      0   0   24701
 4   0   0      0      0  20279   0   25511
 5   0   0      0      0      0  24     123
-1   0   0      0      0      0   0       0

th: 24 hidden: 0 acc:0.6164002338659424 recall:1.0 precision:0.5034517268592398 f1:0.6697278241330262
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.50      1.00      0.67    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.75      0.86     82305
           3       1.00      0.59      0.75     60950
           4       1.00      0.44      0.61     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.62    519956
   macro avg       0.64      0.49      0.52    519956
weighted avg       0.56      0.62      0.54    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 0

     0   1      2      3      4   5      -1
 0   0   0      0      0      0   0  202228
 1   0   0      0      0      0  48  128488
 2   0   0  60232      0      0   0   22073
 3   0   0      0  29549      0   0   31401
 4   0   0      0      0  20190   0   25600
 5   0   0      0      0      0  24     123
-1   0   0      0      0      0   0       0

th: 25 hidden: 0 acc:0.6005719714745094 recall:1.0 precision:0.4933437095188491 f1:0.6607235914601375
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.49      1.00      0.66    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.73      0.85     82305
           3       1.00      0.48      0.65     60950
           4       1.00      0.44      0.61     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.60    519956
   macro avg       0.64      0.47      0.50    519956
weighted avg       0.56      0.60      0.52    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 2

         0      1   2      3      4   5      -1
 0  186941      0   0      0      0   0   15287
 1       0  16860   0      0      2  48  111626
 2       0      0   0      0      0   0   82305
 3       0      0   0  55090      0   0    5860
 4       0      0   0      0  39470   0    6320
 5       0      0   0      0      3  24     120
-1       0      0   0      0      0   0       0

th: 20 hidden: 2 acc:0.732260037387779 recall:1.0 precision:0.37154994176545475 f1:0.5417957165849853
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.37      1.00      0.54     82305
           0       1.00      0.92      0.96    202228
           1       1.00      0.13      0.23    128536
           3       1.00      0.90      0.95     60950
           4       1.00      0.86      0.93     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.73    519956
   macro avg       0.78      0.66      0.64    519956
weighted avg       0.90      0.73      0.71    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 2

         0    1   2      3      4   5      -1
 0  184284    0   0      0      0   0   17944
 1       0  569   0      0      1  48  127918
 2       0    0   0      0      0   0   82305
 3       0    0   0  53667      0   0    7283
 4       0    0   0      0  37167   0    8623
 5       0    0   0      0      1  24     122
-1       0    0   0      0      0   0       0

th: 20.5 hidden: 2 acc:0.6886467316465239 recall:1.0 precision:0.3370462130674256 f1:0.5041653905053598
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.34      1.00      0.50     82305
           0       1.00      0.91      0.95    202228
           1       1.00      0.00      0.01    128536
           3       1.00      0.88      0.94     60950
           4       1.00      0.81      0.90     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.69    519956
   macro avg       0.78      0.63      0.59    519956
weighted avg       0.89      0.69      0.64    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2

         0   1   2      3      4   5      -1
 0  181768   0   0      0      0   0   20460
 1       0   0   0      0      0  48  128488
 2       0   0   0      0      0   0   82305
 3       0   0   0  51683      0   0    9267
 4       0   0   0      0  35468   0   10322
 5       0   0   0      0      1  24     122
-1       0   0   0      0      0   0       0

th: 21 hidden: 2 acc:0.6756283223965105 recall:1.0 precision:0.3279554039623213 f1:0.49392532758822455
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.33      1.00      0.49     82305
           0       1.00      0.90      0.95    202228
           1       0.00      0.00      0.00    128536
           3       1.00      0.85      0.92     60950
           4       1.00      0.77      0.87     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.68    519956
   macro avg       0.61      0.61      0.58    519956
weighted avg       0.65      0.68      0.63    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 2

         0   1   2      3      4   5      -1
 0  176498   0   0      0      0   0   25730
 1       0   0   0      0      0  47  128489
 2       0   0   0      0      0   0   82305
 3       0   0   0  46390      0   0   14560
 4       0   0   0      0  34056   0   11734
 5       0   0   0      0      1  23     123
-1       0   0   0      0      0   0       0

th: 21.5 hidden: 2 acc:0.6525936810037772 recall:1.0 precision:0.3130169886020058 f1:0.4767904624528597
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.31      1.00      0.48     82305
           0       1.00      0.87      0.93    202228
           1       0.00      0.00      0.00    128536
           3       1.00      0.76      0.86     60950
           4       1.00      0.74      0.85     45790
           5       0.33      0.16      0.21       147

    accuracy                           0.65    519956
   macro avg       0.61      0.59      0.56    519956
weighted avg       0.64      0.65      0.61    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 2

         0   1   2      3      4   5      -1
 0  155543   0   0      0      0   0   46685
 1       0   0   0      0      0   0  128536
 2       0   0   0      0      0   0   82305
 3       0   0   0  27045      0   0   33905
 4       0   0   0      0  31626   0   14164
 5       0   0   0      0      0   0     147
-1       0   0   0      0      0   0       0

th: 22 hidden: 2 acc:0.5702771003700313 recall:1.0 precision:0.26919755872598466 f1:0.4242011921236345
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.27      1.00      0.42     82305
           0       1.00      0.77      0.87    202228
           1       0.00      0.00      0.00    128536
           3       1.00      0.44      0.61     60950
           4       1.00      0.69      0.82     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.57    519956
   macro avg       0.54      0.48      0.45    519956
weighted avg       0.64      0.57      0.55    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 2

        0   1   2      3      4   5      -1
 0  75886   0   0      0      0   0  126342
 1      0   0   0      0      0   0  128536
 2      0   0   0      0      0   0   82305
 3      0   0   0  26351      0   0   34599
 4      0   0   0      0  18920   0   26870
 5      0   0   0      0      0   0     147
-1      0   0   0      0      0   0       0

th: 23 hidden: 2 acc:0.3913061874466301 recall:1.0 precision:0.2063821624427343 f1:0.3421505537264292
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.21      1.00      0.34     82305
           0       1.00      0.38      0.55    202228
           1       0.00      0.00      0.00    128536
           3       1.00      0.43      0.60     60950
           4       1.00      0.41      0.58     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.39    519956
   macro avg       0.53      0.37      0.35    519956
weighted avg       0.63      0.39      0.39    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 2

     0   1   2      3      4   5      -1
 0   0   0   0      0      0   0  202228
 1   0   0   0      0      0   0  128536
 2   0   0   0      0      0   0   82305
 3   0   0   0  24271      0   0   36679
 4   0   0   0      0  17135   0   28655
 5   0   0   0      0      0   0     147
-1   0   0   0      0      0   0       0

th: 24 hidden: 2 acc:0.23792590142242806 recall:1.0 precision:0.1719882979834918 f1:0.29349831953000327
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.17      1.00      0.29     82305
           0       0.00      0.00      0.00    202228
           1       0.00      0.00      0.00    128536
           3       1.00      0.40      0.57     60950
           4       1.00      0.37      0.54     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.24    519956
   macro avg       0.36      0.30      0.23    519956
weighted avg       0.23      0.24      0.16    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 2

     0   1   2      3   4   5      -1
 0   0   0   0      0   0   0  202228
 1   0   0   0      0   0   0  128536
 2   0   0   0      0   0   0   82305
 3   0   0   0  24271   0   0   36679
 4   0   0   0      0   0   0   45790
 5   0   0   0      0   0   0     147
-1   0   0   0      0   0   0       0

th: 25 hidden: 2 acc:0.20497118986991206 recall:1.0 precision:0.16604295066423233 f1:0.2847973148324366
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.17      1.00      0.28     82305
           0       0.00      0.00      0.00    202228
           1       0.00      0.00      0.00    128536
           3       1.00      0.40      0.57     60950
           4       0.00      0.00      0.00     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.20    519956
   macro avg       0.19      0.23      0.14    519956
weighted avg       0.14      0.20      0.11    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 3

         0     1      2   3      4   5      -1
 0  182313     0      0   0      0   0   19915
 1       0  1076     10   0      0   0  127450
 2       0     0  69122   0      0   0   13183
 3       0     0      0   0      0   0   60950
 4       0     0      0   0  40952   0    4838
 5       0     4      0   0      3   0     140
-1       0     0      0   0      0   0       0

th: 20 hidden: 3 acc:0.681653832247344 recall:1.0 precision:0.26912343912820785 f1:0.4241091620103957
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.27      1.00      0.42     60950
           0       1.00      0.90      0.95    202228
           1       1.00      0.01      0.02    128536
           2       1.00      0.84      0.91     82305
           4       1.00      0.89      0.94     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.68    519956
   macro avg       0.71      0.61      0.54    519956
weighted avg       0.91      0.68      0.65    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 3

         0     1      2   3      4   5      -1
 0  177513     0      0   0      0   0   24715
 1       0  1076     10   0      0   0  127450
 2       0     0  68792   0      0   0   13513
 3       0     0      0   0      0   0   60950
 4       0     0      0   0  40576   0    5214
 5       0     4      0   0      3   0     140
-1       0     0      0   0      0   0       0

th: 20.5 hidden: 3 acc:0.6710644746863196 recall:1.0 precision:0.2627359019234251 f1:0.4161375336255514
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.26      1.00      0.42     60950
           0       1.00      0.88      0.93    202228
           1       1.00      0.01      0.02    128536
           2       1.00      0.84      0.91     82305
           4       1.00      0.89      0.94     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.67    519956
   macro avg       0.71      0.60      0.54    519956
weighted avg       0.91      0.67      0.64    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 3

         0     1      2   3      4   5      -1
 0  164729     0      0   0      0   0   37499
 1       0  1076     10   0      0   0  127450
 2       0     0  68425   0      0   0   13880
 3       0     0      0   0      0   0   60950
 4       0     0      0   0  38850   0    6940
 5       0     4      0   0      1   0     142
-1       0     0      0   0      0   0       0

th: 21 hidden: 3 acc:0.6424485918039219 recall:1.0 precision:0.24690007737147626 f1:0.39602223442307133
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.25      1.00      0.40     60950
           0       1.00      0.81      0.90    202228
           1       1.00      0.01      0.02    128536
           2       1.00      0.83      0.91     82305
           4       1.00      0.85      0.92     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.64    519956
   macro avg       0.71      0.58      0.52    519956
weighted avg       0.91      0.64      0.62    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 3

         0     1      2   3      4   5      -1
 0  160733     0      0   0      0   0   41495
 1       0  1076     10   0      0   0  127450
 2       0     0  67896   0      0   0   14409
 3       0     0      0   0      0   0   60950
 4       0     0      0   0  34451   0   11339
 5       0     4      0   0      0   0     143
-1       0     0      0   0      0   0       0

th: 21.5 hidden: 3 acc:0.6252836778496642 recall:1.0 precision:0.23828512897500254 f1:0.3848631036573045
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.24      1.00      0.38     60950
           0       1.00      0.79      0.89    202228
           1       1.00      0.01      0.02    128536
           2       1.00      0.82      0.90     82305
           4       1.00      0.75      0.86     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.63    519956
   macro avg       0.71      0.56      0.51    519956
weighted avg       0.91      0.63      0.61    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 3

         0     1      2   3      4   5      -1
 0  157430     0      0   0      0   0   44798
 1       0  1076     10   0      0   0  127450
 2       0     0  65874   0      0   0   16431
 3       0     0      0   0      0   0   60950
 4       0     0      0   0  29690   0   16100
 5       0     4      0   0      0   0     143
-1       0     0      0   0      0   0       0

th: 22 hidden: 3 acc:0.605885882651609 recall:1.0 precision:0.22924565204308842 f1:0.3729859067015073
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.23      1.00      0.37     60950
           0       1.00      0.78      0.88    202228
           1       1.00      0.01      0.02    128536
           2       1.00      0.80      0.89     82305
           4       1.00      0.65      0.79     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.61    519956
   macro avg       0.70      0.54      0.49    519956
weighted avg       0.91      0.61      0.60    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 3

         0   1      2   3      4   5      -1
 0  147339   0      0   0      0   0   54889
 1       0   0     10   0      0   0  128526
 2       0   0  61745   0      0   0   20560
 3       0   0      0   0      0   0   60950
 4       0   0      0   0  22893   0   22897
 5       0   0      0   0      0   0     147
-1       0   0      0   0      0   0       0

th: 23 hidden: 3 acc:0.5633880559124234 recall:1.0 precision:0.2116547267240571 f1:0.34936475227774927
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.21      1.00      0.35     60950
           0       1.00      0.73      0.84    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.75      0.86     82305
           4       1.00      0.50      0.67     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.56    519956
   macro avg       0.54      0.50      0.45    519956
weighted avg       0.66      0.56      0.56    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 3

         0   1      2   3      4   5      -1
 0  121452   0      0   0      0   0   80776
 1       0   0     10   0      0   0  128526
 2       0   0  60460   0      0   0   21845
 3       0   0      0   0      0   0   60950
 4       0   0      0   0  20486   0   25304
 5       0   0      0   0      0   0     147
-1       0   0      0   0      0   0       0

th: 24 hidden: 3 acc:0.5065005500465424 recall:1.0 precision:0.1919394863138801 f1:0.3220624679654846
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.19      1.00      0.32     60950
           0       1.00      0.60      0.75    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.73      0.85     82305
           4       1.00      0.45      0.62     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.51    519956
   macro avg       0.53      0.46      0.42    519956
weighted avg       0.66      0.51      0.52    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 3

         0   1      2   3      4   5      -1
 0  109377   0      0   0      0   0   92851
 1       0   0      0   0      0   0  128536
 2       0   0  57840   0      0   0   24465
 3       0   0      0   0      0   0   60950
 4       0   0      0   0  20026   0   25764
 5       0   0      0   0      0   0     147
-1       0   0      0   0      0   0       0

th: 25 hidden: 3 acc:0.4773346206217449 recall:1.0 precision:0.18319091829895434 f1:0.3096557207560781
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.18      1.00      0.31     60950
           0       1.00      0.54      0.70    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.70      0.83     82305
           4       1.00      0.44      0.61     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.48    519956
   macro avg       0.53      0.45      0.41    519956
weighted avg       0.66      0.48      0.49    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 4

         0   1      2      3   4   5      -1
 0  172408   0      0      0   0   0   29820
 1       1   0      0      0   0   0  128535
 2       0   0  68851      0   0   0   13454
 3       0   0      3  55600   0   0    5347
 4       0   0      0      0   0   0   45790
 5       0   0      0      0   0   0     147
-1       0   0      0      0   0   0       0

th: 20 hidden: 4 acc:0.6590038387863588 recall:1.0 precision:0.20525072503395445 f1:0.34059423615475876
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.21      1.00      0.34     45790
           0       1.00      0.85      0.92    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.84      0.91     82305
           3       1.00      0.91      0.95     60950
           5       0.00      0.00      0.00       147

    accuracy                           0.66    519956
   macro avg       0.53      0.60      0.52    519956
weighted avg       0.68      0.66      0.64    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 4

         0   1      2      3   4   5      -1
 0  168517   0      0      0   0   0   33711
 1       0   0      0      0   0   0  128536
 2       0   0  68644      0   0   0   13661
 3       0   0      3  54315   0   0    6632
 4       0   0      0      0   0   0   45790
 5       0   0      0      0   0   0     147
-1       0   0      0      0   0   0       0

th: 20.5 hidden: 4 acc:0.6486491164637008 recall:1.0 precision:0.20041404605277555 f1:0.3339081989448239
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.20      1.00      0.33     45790
           0       1.00      0.83      0.91    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.83      0.91     82305
           3       1.00      0.89      0.94     60950
           5       0.00      0.00      0.00       147

    accuracy                           0.65    519956
   macro avg       0.53      0.59      0.52    519956
weighted avg       0.68      0.65      0.64    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 4

         0   1      2      3   4   5      -1
 0  161001   0      0      0   0   0   41227
 1       0   0      0      0   0   0  128536
 2       0   0  68446      0   0   0   13859
 3       0   0      3  51505   0   0    9442
 4       0   0      0      0   0   0   45790
 5       0   0      0      0   0   0     147
-1       0   0      0      0   0   0       0

th: 21 hidden: 4 acc:0.6284089422951172 recall:1.0 precision:0.1915891565307258 f1:0.32156915071052106
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.19      1.00      0.32     45790
           0       1.00      0.80      0.89    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.83      0.91     82305
           3       1.00      0.85      0.92     60950
           5       0.00      0.00      0.00       147

    accuracy                           0.63    519956
   macro avg       0.53      0.58      0.51    519956
weighted avg       0.68      0.63      0.62    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 4

         0   1      2      3   4   5      -1
 0  146819   0      0      0   0   0   55409
 1       0   0      0      0   0   0  128536
 2       0   0  68042      0   0   0   14263
 3       0   0      1  45868   0   0   15081
 4       0   0      0      0   0   0   45790
 5       0   0      0      0   0   0     147
-1       0   0      0      0   0   0       0

th: 21.5 hidden: 4 acc:0.5895114201970936 recall:1.0 precision:0.17664123197518766 f1:0.3002465444435702
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.18      1.00      0.30     45790
           0       1.00      0.73      0.84    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.83      0.91     82305
           3       1.00      0.75      0.86     60950
           5       0.00      0.00      0.00       147

    accuracy                           0.59    519956
   macro avg       0.53      0.55      0.48    519956
weighted avg       0.68      0.59      0.60    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 4

         0   1      2      3   4   5      -1
 0  138782   0      0      0   0   0   63446
 1       0   0      0      0   0   0  128536
 2       0   0  67679      0   0   0   14626
 3       0   0      1  43485   0   0   17464
 4       0   0      0      0   0   0   45790
 5       0   0      0      0   0   0     147
-1       0   0      0      0   0   0       0

th: 22 hidden: 4 acc:0.5687731269568963 recall:1.0 precision:0.16958693969460278 f1:0.2899945851633476
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.17      1.00      0.29     45790
           0       1.00      0.69      0.81    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.82      0.90     82305
           3       1.00      0.71      0.83     60950
           5       0.00      0.00      0.00       147

    accuracy                           0.57    519956
   macro avg       0.53      0.54      0.47    519956
weighted avg       0.68      0.57      0.58    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 4

        0   1      2      3   4   5      -1
 0  97878   0      0      0   0   0  104350
 1      0   0      0      0   0   0  128536
 2      0   0  64178      0   0   0   18127
 3      0   0      0  41153   0   0   19797
 4      0   0      0      0   0   0   45790
 5      0   0      0      0   0   0     147
-1      0   0      0      0   0   0       0

th: 23 hidden: 4 acc:0.47888475178668966 recall:1.0 precision:0.14456332656662887 f1:0.25260869925000756
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.14      1.00      0.25     45790
           0       1.00      0.48      0.65    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.78      0.88     82305
           3       1.00      0.68      0.81     60950
           5       0.00      0.00      0.00       147

    accuracy                           0.48    519956
   macro avg       0.52      0.49      0.43    519956
weighted avg       0.68      0.48      0.51    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 4

        0   1      2      3   4   5      -1
 0  20905   0      0      0   0   0  181323
 1      0   0      0      0   0   0  128536
 2      0   0  53786      0   0   0   28519
 3      0   0      0  38815   0   0   22135
 4      0   0      0      0   0   0   45790
 5      0   0      0      0   0   0     147
-1      0   0      0      0   0   0       0

th: 24 hidden: 4 acc:0.3063643846787036 recall:1.0 precision:0.11265838356501415 f1:0.2025030957013975
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.11      1.00      0.20     45790
           0       1.00      0.10      0.19    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.65      0.79     82305
           3       1.00      0.64      0.78     60950
           5       0.00      0.00      0.00       147

    accuracy                           0.31    519956
   macro avg       0.52      0.40      0.33    519956
weighted avg       0.67      0.31      0.31    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 4

     0   1      2      3   4   5      -1
 0   0   0      0      0   0   0  202228
 1   0   0      0      0   0   0  128536
 2   0   0  52492      0   0   0   29813
 3   0   0      0  24271   0   0   36679
 4   0   0      0      0   0   0   45790
 5   0   0      0      0   0   0     147
-1   0   0      0      0   0   0       0

th: 25 hidden: 4 acc:0.23569878989760673 recall:1.0 precision:0.10331841883784265 f1:0.1872866745878691
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.10      1.00      0.19     45790
           0       0.00      0.00      0.00    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.64      0.78     82305
           3       1.00      0.40      0.57     60950
           5       0.00      0.00      0.00       147

    accuracy                           0.24    519956
   macro avg       0.35      0.34      0.26    519956
weighted avg       0.28      0.24      0.21    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 5

         0   1      2      3      4   5      -1
 0  171837   0      0      0      0   0   30391
 1       0   0      0      0      0   0  128536
 2       0   0  61722      0      0   0   20583
 3       0   0      3  51656      0   0    9291
 4       0   0      0      0  35507   0   10283
 5       0   0      0      0      1   0     146
-1       0   0      0      0      0   0       0

th: 20 hidden: 5 acc:0.6171118325396764 recall:0.9931972789115646 precision:0.0007328213622446419 f1:0.0014645621109756893
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.99      0.00       147
           0       1.00      0.85      0.92    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.75      0.86     82305
           3       1.00      0.85      0.92     60950
           4       1.00      0.78      0.87     45790

    accuracy                           0.62    519956
   macro avg       0.67      0.70      0.59    519956
weighted avg       0.75      0.62      0.68    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 5

         0   1      2      3      4   5      -1
 0  163605   0      0      0      0   0   38623
 1       0   0      0      0      0   0  128536
 2       0   0  61361      0      0   0   20944
 3       0   0      2  44680      0   0   16268
 4       0   0      0      0  35398   0   10392
 5       0   0      0      0      1   0     146
-1       0   0      0      0      0   0       0

th: 20.5 hidden: 5 acc:0.5869573579302864 recall:0.9931972789115646 precision:0.0006793573093728043 f1:0.001357785879026858
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.99      0.00       147
           0       1.00      0.81      0.89    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.75      0.85     82305
           3       1.00      0.73      0.85     60950
           4       1.00      0.77      0.87     45790

    accuracy                           0.59    519956
   macro avg       0.67      0.68      0.58    519956
weighted avg       0.75      0.59      0.66    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 5

         0   1      2      3      4   5      -1
 0  161626   0      0      0      0   0   40602
 1       0   0      0      0      0   0  128536
 2       0   0  61002      0      0   0   21303
 3       0   0      2  44369      0   0   16579
 4       0   0      0      0  35299   0   10491
 5       0   0      0      0      1   0     146
-1       0   0      0      0      0   0       0

th: 21 hidden: 5 acc:0.5816722953480679 recall:0.9931972789115646 precision:0.0006707801724732032 f1:0.0013406549007364417
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.99      0.00       147
           0       1.00      0.80      0.89    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.74      0.85     82305
           3       1.00      0.73      0.84     60950
           4       1.00      0.77      0.87     45790

    accuracy                           0.58    519956
   macro avg       0.67      0.67      0.58    519956
weighted avg       0.75      0.58      0.66    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 5

         0   1      2      3      4   5      -1
 0  152374   0      0      0      0   0   49854
 1       0   0      0      0      0   0  128536
 2       0   0  60683      0      0   0   21622
 3       0   0      0  43652      0   0   17298
 4       0   0      0      0  35120   0   10670
 5       0   0      0      0      0   0     147
-1       0   0      0      0      0   0       0

th: 21.5 hidden: 5 acc:0.5615398226003738 recall:1.0 precision:0.0006443779123032346 f1:0.0012879259135950654
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      1.00      0.00       147
           0       1.00      0.75      0.86    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.74      0.85     82305
           3       1.00      0.72      0.83     60950
           4       1.00      0.77      0.87     45790

    accuracy                           0.56    519956
   macro avg       0.67      0.66      0.57    519956
weighted avg       0.75      0.56      0.64    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 5

         0   1      2      3      4   5      -1
 0  138414   0      0      0      0   0   63814
 1       0   0      0      0      0   0  128536
 2       0   0  60354      0      0   0   21951
 3       0   0      0  42974      0   0   17976
 4       0   0      0      0  34537   0   11253
 5       0   0      0      0      0   0     147
-1       0   0      0      0      0   0       0

th: 22 hidden: 5 acc:0.5316334459069614 recall:1.0 precision:0.0006032575909913533 f1:0.0012057877813504824
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      1.00      0.00       147
           0       1.00      0.68      0.81    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.73      0.85     82305
           3       1.00      0.71      0.83     60950
           4       1.00      0.75      0.86     45790

    accuracy                           0.53    519956
   macro avg       0.67      0.65      0.56    519956
weighted avg       0.75      0.53      0.62    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 5

         0   1      2      3      4   5      -1
 0  113650   0      0      0      0   0   88578
 1       0   0      0      0      0   0  128536
 2       0   0  59412      0      0   0   22893
 3       0   0      0  40331      0   0   20619
 4       0   0      0      0  33152   0   12638
 5       0   0      0      0      0   0     147
-1       0   0      0      0      0   0       0

th: 23 hidden: 5 acc:0.47444783789397565 recall:1.0 precision:0.0005376521061698323 f1:0.001074726383436054
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      1.00      0.00       147
           0       1.00      0.56      0.72    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.72      0.84     82305
           3       1.00      0.66      0.80     60950
           4       1.00      0.72      0.84     45790

    accuracy                           0.47    519956
   macro avg       0.67      0.61      0.53    519956
weighted avg       0.75      0.47      0.58    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 5

        0   1      2      3      4   5      -1
 0  74935   0      0      0      0   0  127293
 1      0   0      0      0      0   0  128536
 2      0   0  56146      0      0   0   26159
 3      0   0      0  38251      0   0   22699
 4      0   0      0      0  25955   0   19835
 5      0   0      0      0      0   0     147
-1      0   0      0      0      0   0       0

th: 24 hidden: 5 acc:0.37586641946626254 recall:1.0 precision:0.00045276881993661235 f1:0.0009051278262154572
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      1.00      0.00       147
           0       1.00      0.37      0.54    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.68      0.81     82305
           3       1.00      0.63      0.77     60950
           4       1.00      0.57      0.72     45790

    accuracy                           0.38    519956
   macro avg       0.67      0.54      0.47    519956
weighted avg       0.75      0.38      0.49    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 5

        0   1      2      3      4   5      -1
 0  53714   0      0      0      0   0  148514
 1      0   0      0      0      0   0  128536
 2      0   0  41831      0      0   0   40474
 3      0   0      0  36248      0   0   24702
 4      0   0      0      0  19971   0   25819
 5      0   0      0      0      0   0     147
-1      0   0      0      0      0   0       0

th: 25 hidden: 5 acc:0.29216125979890606 recall:1.0 precision:0.0003992482183208761 f1:0.0007981777655909366
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      1.00      0.00       147
           0       1.00      0.27      0.42    202228
           1       0.00      0.00      0.00    128536
           2       1.00      0.51      0.67     82305
           3       1.00      0.59      0.75     60950
           4       1.00      0.44      0.61     45790

    accuracy                           0.29    519956
   macro avg       0.67      0.47      0.41    519956
weighted avg       0.75      0.29      0.41    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Média absolute threshold

In [6]:
for i in range(len(f1s)):
    print(f'Média f1 absolute th {ths[i]}: {np.mean(np.array(f1s[i]))}')

Média f1 absolute th 20: 0.40235852191048715
Média f1 absolute th 20.5: 0.3915279531877827
Média f1 absolute th 21: 0.38229031274745817
Média f1 absolute th 21.5: 0.3714439488079409
Média f1 absolute th 22: 0.35549788922083503
Média f1 absolute th 23: 0.32321571012758876
Média f1 absolute th 24: 0.29773936703122544
Média f1 absolute th 25: 0.28865229588042246