In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture

In [2]:
def matriz_conf(y_true, y_pred, labels):
    total_labels = labels
    print(total_labels)
    cm = np.zeros((len(total_labels),len(total_labels)), dtype=int)
    for i in range(len(y_true)):
        cm[y_true[i]][y_pred[i]] += 1

    
    cm = pd.DataFrame(cm, columns=total_labels, index=total_labels)

    cm_transp = pd.DataFrame(np.transpose(cm.to_numpy()), columns=total_labels, index=total_labels)

    for c in cm_transp.columns:
        cm_transp[c] = cm_transp[c]/cm_transp[c].sum()

    cm_porcento = pd.DataFrame(np.transpose(cm_transp.to_numpy()), columns=total_labels, index=total_labels)

    return cm, cm_porcento

def acc(cm, hidden_classes):
    cm_transp = pd.DataFrame(np.transpose(cm.dropna().to_numpy()), columns=cm.columns, index=cm.columns)
    acc = 0
    total = 0
    for c in cm_transp.columns:
        if c not in hidden_classes:
            acc += cm_transp[c][c]
        else:
            acc += cm_transp[c][-1]
        total += cm_transp[c].sum()
    return acc/total

In [3]:
filenames = [0,2,3,4,5]

labels_str = ['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

filenames

# pd.set_option('future.no_silent_downcasting', True)

[0, 2, 3, 4, 5]

In [8]:
exp_val = []
y_true_all_exp_val = []
for i in range(len(filenames)):
    exp_val.append(pd.read_csv(f'val_{filenames[i]}_GMM_BIC_1_10_scores_corr.csv'))
    y_true_all_exp_val.append(exp_val[i]['Label'].values.tolist())
    exp_val[i] = exp_val[i].drop(columns=['Label'])

In [9]:
exp_val[0]

         0           1           2             3           4           5
0      NaN   19.935705  -48.818030 -15808.303205  -21.500241  -65.854462
1      NaN   -8.412854   29.685671     17.478867 -320.092369 -158.010622
2      NaN   24.235509  -36.801325 -14968.220023  -20.034179  -37.640116
3      NaN -102.669033  -52.032445     26.650458 -974.547268 -195.489090
4      NaN   27.129415  -17.689401 -15496.922456  -15.503954   -0.599197
...     ..         ...         ...           ...         ...         ...
519951 NaN   24.848032  -30.161328 -15479.226154  -18.381144  -26.695069
519952 NaN    4.697448 -172.079922 -35874.640927   27.759064  -18.744434
519953 NaN   18.034682   -8.887314 -17512.429612  -23.359146   -1.604396
519954 NaN   26.376891   -4.701878 -14893.066887  -15.588237    8.495412
519955 NaN  -88.197497  -40.690918     28.315703 -939.649783 -270.881731

[519956 rows x 6 columns]

In [14]:
from sklearn.metrics import classification_report
ths = [15, 16, 17, 18, 19, 20, 20.5, 21]
f1s = [[],[],[],[],[],[],[],[]]
for i in range(len(exp_val)):
    index = 0
    for th in ths:
        y_pred = []
        prog= 0
        for j in range(len(exp_val[i])):
            # print(exp[i][j])
            m = np.nanmax(exp_val[i].values[j])
            # print(m)
            if m > th:
                y_pred.append(exp_val[i].values[j].tolist().index(m))
            else:
                y_pred.append(-1)
        # print(y_pred[:10])

        cm, cm_porcento = matriz_conf(y_true_all_exp_val[i], y_pred, list(range(len(labels_str))) + [-1])
        print(f'th = {th} hidden = {filenames[i]}')
        display(cm)
        tp = cm[-1][filenames[i]]
        fp = cm[-1].sum() - tp
        fn = cm.iloc[filenames[i]].sum() - tp
        tn = cm.drop(columns=[-1]).values.sum() - fn

        acc = (tp+tn)/(tp+fp+tn+fn)
        recall = tp/(tp+fn)
        precision = tp/(tp+fp)
        if precision == 0 or recall == 0:
            f1 = 0
        else:
            f1 = 2*precision*recall/(precision+recall)

        f1s[index].append(f1)
        index += 1
        print(f'th: {th} hidden: {filenames[i]} acc:{acc} recall:{recall} precision:{precision} f1:{f1}')

        true_labels = np.array(y_true_all_exp_val[i])
        true_labels[true_labels == filenames[i]] = -1

        print('MULTICLASS DETECTION')
        print(classification_report(true_labels, y_pred))

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 0

     0       1      2      3      4    5     -1
 0   0  122107      0      0      0    0  80121
 1   0  122748     16      1     90  380   5301
 2   0       0  82042      0      0    0    263
 3   0       0      3  60944      0    0      3
 4   0      39      0      0  44698   16   1037
 5   0       5      0      0      9  122     11
-1   0       0      0      0      0    0      0

th: 15 hidden: 0 acc:0.752436744647624 recall:0.3961914274976759 precision:0.9237340896513558 f1:0.5545396658407276
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.92      0.40      0.55    202228
           1       0.50      0.95      0.66    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790
           5       0.24      0.83      0.37       147

    accuracy                           0.75    519956
   macro avg       0.78      0.86      0.76    519956
weighted avg       0.85      0.75      0.74    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 0

     0       1      2      3      4    5     -1
 0   0  112905      0      0      0    0  89323
 1   0  120876     16      1     90  374   7179
 2   0       0  81819      0      0    0    486
 3   0       0      3  60933      0    0     14
 4   0      38      0      0  44691   16   1045
 5   0       5      0      0      9  122     11
-1   0       0      0      0      0    0      0

th: 16 hidden: 0 acc:0.7660571279108233 recall:0.44169452301362816 precision:0.9109200677150258 f1:0.5949195100670693
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.91      0.44      0.59    202228
           1       0.52      0.94      0.67    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790
           5       0.24      0.83      0.37       147

    accuracy                           0.76    519956
   macro avg       0.78      0.86      0.77    519956
weighted avg       0.85      0.76      0.76    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 0

     0       1      2      3      4    5     -1
 0   0  102272      0      0      0    0  99956
 1   0  116174     16      1     89  371  11885
 2   0       0  81620      0      0    0    685
 3   0       0      3  60932      0    0     15
 4   0      29      0      0  44688   16   1057
 5   0       1      0      0      9  117     20
-1   0       0      0      0      0    0      0

th: 17 hidden: 0 acc:0.7770311334035956 recall:0.49427378997962695 precision:0.8797549684028939 f1:0.6329413701614078
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.88      0.49      0.63    202228
           1       0.53      0.90      0.67    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790
           5       0.23      0.80      0.36       147

    accuracy                           0.78    519956
   macro avg       0.77      0.86      0.77    519956
weighted avg       0.84      0.78      0.77    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 0

     0       1      2      3      4    5      -1
 0   0   90821      0      0      0    0  111407
 1   0  111866     15      0     89  324   16242
 2   0       0  81373      0      0    0     932
 3   0       0      3  60924      0    0      23
 4   0       1      0      0  44670   16    1103
 5   0       1      0      0      9  103      34
-1   0       0      0      0      0    0       0

th: 18 hidden: 0 acc:0.7900687750501966 recall:0.5508979963209842 precision:0.8586876931733223 f1:0.6711891773027
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.86      0.55      0.67    202228
           1       0.55      0.87      0.68    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790
           5       0.23      0.70      0.35       147

    accuracy                           0.79    519956
   macro avg       0.77      0.85      0.78    519956
weighted avg       0.83      0.79      0.79    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 0

     0       1      2      3      4    5      -1
 0   0   48339      0      0      0    0  153889
 1   0  109725      3      0     88  110   18610
 2   0       0  80739      0      0    0    1566
 3   0       0      3  60891      0    0      56
 4   0       0      0      0  44655   15    1120
 5   0       0      0      0      9   91      47
-1   0       0      0      0      0    0       0

th: 19 hidden: 0 acc:0.8658771126787651 recall:0.760967818501889 precision:0.8779209073068321 f1:0.8152714057152544
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.88      0.76      0.82    202228
           1       0.69      0.85      0.77    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790
           5       0.42      0.62      0.50       147

    accuracy                           0.87    519956
   macro avg       0.83      0.86      0.84    519956
weighted avg       0.88      0.87      0.87    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 0

     0       1      2      3      4   5      -1
 0   0    1380      0      0      0   0  200848
 1   0  107676      3      0     88  48   20721
 2   0       0  80338      0      0   0    1967
 3   0       0      3  60874      0   0      73
 4   0       0      0      0  44616   0    1174
 5   0       0      0      0      8  58      81
-1   0       0      0      0      0   0       0

th: 20 hidden: 0 acc:0.95115740562663 recall:0.9931760191467057 precision:0.8931976661448698 f1:0.940537401777603
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.89      0.99      0.94    202228
           1       0.99      0.84      0.91    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.97      0.99     45790
           5       0.55      0.39      0.46       147

    accuracy                           0.95    519956
   macro avg       0.90      0.86      0.88    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 0

     0       1      2      3      4   5      -1
 0   0       0      0      0      0   0  202228
 1   0  102432      3      0     88  48   25965
 2   0       0  80202      0      0   0    2103
 3   0       0      3  60866      0   0      81
 4   0       0      0      0  44592   0    1198
 5   0       0      0      0      8  58      81
-1   0       0      0      0      0   0       0

th: 20.5 hidden: 0 acc:0.9434029033225888 recall:1.0 precision:0.8729668128604483 f1:0.9321754201583834
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.87      1.00      0.93    202228
           1       1.00      0.80      0.89    128536
           2       1.00      0.97      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.97      0.99     45790
           5       0.55      0.39      0.46       147

    accuracy                           0.94    519956
   macro avg       0.90      0.86      0.87    519956
weighted avg       0.95      0.94      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0

     0      1      2      3      4   5      -1
 0   0      0      0      0      0   0  202228
 1   0  93713      3      0     85  48   34687
 2   0      0  80025      0      0   0    2280
 3   0      0      3  60855      0   0      92
 4   0      0      0      0  44405   0    1385
 5   0      0      0      0      7  50      90
-1   0      0      0      0      0   0       0

th: 21 hidden: 0 acc:0.9258898829900991 recall:1.0 precision:0.8399498259692144 f1:0.9130138377841486
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.84      1.00      0.91    202228
           1       1.00      0.73      0.84    128536
           2       1.00      0.97      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.97      0.98     45790
           5       0.51      0.34      0.41       147

    accuracy                           0.93    519956
   macro avg       0.89      0.83      0.86    519956
weighted avg       0.94      0.93      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 2

         0       1   2      3      4    5     -1
 0  201695     296   0      0      0    0    237
 1      78  118657   0      0    120  332   9349
 2      40     828   0      0      0    0  81437
 3       0       0   0  60935      0    0     15
 4       1      15   0      0  45487   63    224
 5       0       6   0      0      9  114     18
-1       0       0   0      0      0    0      0

th: 15 hidden: 2 acc:0.9794001800152321 recall:0.9894538606403013 precision:0.8921669588080631 f1:0.9382953596220871
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.89      0.99      0.94     82305
           0       1.00      1.00      1.00    202228
           1       0.99      0.92      0.96    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      1.00     45790
           5       0.22      0.78      0.35       147

    accuracy                           0.98    519956
   macro avg       0.85      0.95      0.87    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 2

         0       1   2      3      4    5     -1
 0  201454     296   0      0      0    0    478
 1      73  114764   0      0    116  316  13267
 2      40     426   0      0      0    0  81839
 3       0       0   0  60917      0    0     33
 4       1       4   0      0  45463   63    259
 5       0       6   0      0      9  108     24
-1       0       0   0      0      0    0      0

th: 16 hidden: 2 acc:0.9720610974774788 recall:0.9943381325557378 precision:0.853378519290928 f1:0.9184815240874274
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.85      0.99      0.92     82305
           0       1.00      1.00      1.00    202228
           1       0.99      0.89      0.94    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      1.00     45790
           5       0.22      0.73      0.34       147

    accuracy                           0.97    519956
   macro avg       0.84      0.94      0.87    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 2

         0       1   2      3      4    5     -1
 0  201434     294   0      0      0    0    500
 1      72  111774   0      0    111  291  16288
 2      40      39   0      0      0    0  82226
 3       0       0   0  60900      0    0     50
 4       1       3   0      0  45443   61    282
 5       0       6   0      0      9  106     26
-1       0       0   0      0      0    0      0

th: 17 hidden: 2 acc:0.9668721968781974 recall:0.9990401555191057 precision:0.8274564263575253 f1:0.9051888791646714
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.83      1.00      0.91     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.87      0.93    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.23      0.72      0.35       147

    accuracy                           0.97    519956
   macro avg       0.84      0.93      0.86    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 2

         0       1   2      3      4   5     -1
 0  201317     292   0      0      0   0    619
 1      71  107327   0      0    106  94  20938
 2      35      26   0      0      0   0  82244
 3       0       0   0  60869      0   0     81
 4       1       2   0      0  45399  56    332
 5       0       4   0      0      9  68     66
-1       0       0   0      0      0   0      0

th: 18 hidden: 2 acc:0.9575021732608143 recall:0.999258854261588 precision:0.7886843114691215 f1:0.8815714017739905
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.79      1.00      0.88     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.83      0.91    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.31      0.46      0.37       147

    accuracy                           0.96    519956
   macro avg       0.85      0.88      0.86    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 2

         0      1   2      3      4   5     -1
 0  201195    286   0      0      0   0    747
 1      71  99232   0      0    102  48  29083
 2      35     16   0      0      0   0  82254
 3       0      0   0  60846      0   0    104
 4       1      2   0      0  45220   0    567
 5       0      4   0      0      8  63     72
-1       0      0   0      0      0   0      0

th: 19 hidden: 2 acc:0.9411027086907354 recall:0.9993803535629671 precision:0.7290276263660294 f1:0.8430600824057561
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.73      1.00      0.84     82305
           0       1.00      0.99      1.00    202228
           1       1.00      0.77      0.87    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.57      0.43      0.49       147

    accuracy                           0.94    519956
   macro avg       0.88      0.86      0.87    519956
weighted avg       0.96      0.94      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 2

         0      1   2      3      4   5     -1
 0  201049    279   0      0      0   0    900
 1      71  80085   0      0     96   0  48284
 2      22      7   0      0      0   0  82276
 3       0      0   0  60691      0   0    259
 4       1      2   0      0  44743   0   1044
 5       0      4   0      0      7  47     89
-1       0      0   0      0      0   0      0

th: 20 hidden: 2 acc:0.9026744570694444 recall:0.9996476520260008 precision:0.619305693553729 f1:0.7647996579242134
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.62      1.00      0.76     82305
           0       1.00      0.99      1.00    202228
           1       1.00      0.62      0.77    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790
           5       1.00      0.32      0.48       147

    accuracy                           0.90    519956
   macro avg       0.94      0.82      0.83    519956
weighted avg       0.94      0.90      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 2

         0      1   2      3      4   5     -1
 0  200620    279   0      0      0   0   1329
 1      71  78219   0      0     91   0  50155
 2      22      6   0      0      0   0  82277
 3       0      0   0  60686      0   0    264
 4       1      2   0      0  44641   0   1146
 5       0      4   0      0      6  47     90
-1       0      0   0      0      0   0      0

th: 20.5 hidden: 2 acc:0.8980452192108563 recall:0.9996598019561388 precision:0.6082832449856204 f1:0.756340604690071
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.61      1.00      0.76     82305
           0       1.00      0.99      1.00    202228
           1       1.00      0.61      0.76    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.97      0.99     45790
           5       1.00      0.32      0.48       147

    accuracy                           0.90    519956
   macro avg       0.93      0.82      0.83    519956
weighted avg       0.94      0.90      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2

         0      1   2      3      4   5     -1
 0  200056    279   0      0      0   0   1893
 1      71  76732   0      0     89   0  51644
 2      22      3   0      0      0   0  82280
 3       0      0   0  60679      0   0    271
 4       1      2   0      0  44540   0   1247
 5       0      4   0      0      6  47     90
-1       0      0   0      0      0   0      0

th: 21 hidden: 2 acc:0.8938948680272946 recall:0.9996962517465524 precision:0.5987265781335274 f1:0.7489191280207528
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.60      1.00      0.75     82305
           0       1.00      0.99      0.99    202228
           1       1.00      0.60      0.75    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.97      0.99     45790
           5       1.00      0.32      0.48       147

    accuracy                           0.89    519956
   macro avg       0.93      0.81      0.83    519956
weighted avg       0.94      0.89      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 3

         0       1      2   3      4    5     -1
 0  201995       5      0   0      0   85    143
 1     220  119313     16   0    136  279   8572
 2       0       0  82148   0      0    0    157
 3       0       0   3248   0      0    0  57702
 4       2       9      0   0  45540  132    107
 5       0      14      0   0      6  123      4
-1       0       0      0   0      0    0      0

th: 15 hidden: 3 acc:0.9764768557339467 recall:0.9467104183757178 precision:0.8652920446877109 f1:0.9041720531202256
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.87      0.95      0.90     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.93      0.96    128536
           2       0.96      1.00      0.98     82305
           4       1.00      0.99      1.00     45790
           5       0.20      0.84      0.32       147

    accuracy                           0.97    519956
   macro avg       0.84      0.95      0.86    519956
weighted avg       0.98      0.97      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 3

         0       1      2   3      4    5     -1
 0  201947       2      0   0      0   85    194
 1     218  117271     15   0    131  260  10641
 2       0       0  82103   0      0    0    202
 3       0       0   3164   0      0    0  57786
 4       2       0      0   0  45495  132    161
 5       0      13      0   0      6  120      8
-1       0       0      0   0      0    0      0

th: 16 hidden: 3 acc:0.9723630461039011 recall:0.9480885972108285 precision:0.8375753710575139 f1:0.8894121992889135
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.84      0.95      0.89     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.91      0.95    128536
           2       0.96      1.00      0.98     82305
           4       1.00      0.99      1.00     45790
           5       0.20      0.82      0.32       147

    accuracy                           0.97    519956
   macro avg       0.83      0.94      0.86    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 3

         0       1      2   3      4    5     -1
 0  201786       2      0   0      0   85    355
 1     209  114705     15   0    123  190  13294
 2       0       0  81922   0      0    0    383
 3       0       0   2937   0      0    0  58013
 4       2       0      0   0  45418  132    238
 5       0      13      0   0      6  109     19
-1       0       0      0   0      0    0      0

th: 17 hidden: 3 acc:0.9668702736385386 recall:0.9518129614438064 precision:0.8023706121545738 f1:0.8707261429471977
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.80      0.95      0.87     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.89      0.94    128536
           2       0.97      1.00      0.98     82305
           4       1.00      0.99      0.99     45790
           5       0.21      0.74      0.33       147

    accuracy                           0.97    519956
   macro avg       0.83      0.93      0.85    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 3

         0       1      2   3      4    5     -1
 0  201617       1      0   0      0   68    542
 1     207  107100     15   0    121  147  20946
 2       0       0  81879   0      0    0    426
 3       0       0   2667   0      0    0  58283
 4       2       0      0   0  45406  125    257
 5       0       5      0   0      6  107     29
-1       0       0      0   0      0    0      0

th: 18 hidden: 3 acc:0.9521747994061036 recall:0.9562428219852338 precision:0.7241653516891766 f1:0.8241782328028113
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.72      0.96      0.82     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.83      0.91    128536
           2       0.97      0.99      0.98     82305
           4       1.00      0.99      0.99     45790
           5       0.24      0.73      0.36       147

    accuracy                           0.95    519956
   macro avg       0.82      0.92      0.84    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 3

         0       1      2   3      4    5     -1
 0  201567       1      0   0      0   32    628
 1     182  103528     15   0    108  121  24582
 2       0       0  81746   0      0    0    559
 3       0       0   2426   0      0    0  58524
 4       2       0      0   0  45225  122    441
 5       0       5      0   0      5   99     38
-1       0       0      0   0      0    0      0

th: 19 hidden: 3 acc:0.9448530260252791 recall:0.9601968826907301 precision:0.690369461614684 f1:0.8032280643965907
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.69      0.96      0.80     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.81      0.89    128536
           2       0.97      0.99      0.98     82305
           4       1.00      0.99      0.99     45790
           5       0.26      0.67      0.38       147

    accuracy                           0.94    519956
   macro avg       0.82      0.90      0.84    519956
weighted avg       0.96      0.94      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 3

         0      1      2   3      4    5     -1
 0  201205      1      0   0      0    0   1022
 1     180  97044     15   0     81  116  31100
 2       0      0  81612   0      0    0    693
 3       0      0   1419   0      0    0  59531
 4       2      0      0   0  44787  117    884
 5       0      4      0   0      5   98     40
-1       0      0      0   0      0    0      0

th: 20 hidden: 3 acc:0.9323827400780066 recall:0.9767186218211649 precision:0.6382652514206069 f1:0.7720269744520815
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.64      0.98      0.77     60950
           0       1.00      0.99      1.00    202228
           1       1.00      0.75      0.86    128536
           2       0.98      0.99      0.99     82305
           4       1.00      0.98      0.99     45790
           5       0.30      0.67      0.41       147

    accuracy                           0.93    519956
   macro avg       0.82      0.89      0.84    519956
weighted avg       0.95      0.93      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 3

         0      1      2   3      4    5     -1
 0  201151      1      0   0      0    0   1076
 1     176  90588     15   0     49  114  37594
 2       0      0  81414   0      0    0    891
 3       0      0      3   0      0    0  60947
 4       2      0      0   0  44120  115   1553
 5       0      4      0   0      5   96     42
-1       0      0      0   0      0    0      0

th: 20.5 hidden: 3 acc:0.9208413788859058 recall:0.9999507793273175 precision:0.5969168388783875 f1:0.7475728750774289
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.60      1.00      0.75     60950
           0       1.00      0.99      1.00    202228
           1       1.00      0.70      0.83    128536
           2       1.00      0.99      0.99     82305
           4       1.00      0.96      0.98     45790
           5       0.30      0.65      0.41       147

    accuracy                           0.92    519956
   macro avg       0.81      0.88      0.83    519956
weighted avg       0.95      0.92      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 3

         0      1      2   3      4    5     -1
 0  201025      1      0   0      0    0   1202
 1     175  80261     15   0     48   87  47950
 2       0      0  81139   0      0    0   1166
 3       0      0      3   0      0    0  60947
 4       2      0      0   0  44011  115   1662
 5       0      4      0   0      5   92     46
-1       0      0      0   0      0    0      0

th: 21 hidden: 3 acc:0.8999357637953981 recall:0.9999507793273175 precision:0.5394828852911757 f1:0.7008503763159559
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.54      1.00      0.70     60950
           0       1.00      0.99      1.00    202228
           1       1.00      0.62      0.77    128536
           2       1.00      0.99      0.99     82305
           4       1.00      0.96      0.98     45790
           5       0.31      0.63      0.42       147

    accuracy                           0.90    519956
   macro avg       0.81      0.87      0.81    519956
weighted avg       0.95      0.90      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 4

         0       1      2      3   4      5     -1
 0  201541       0      0      0   0    582    105
 1     355  102874     18      1   0   2672  22616
 2       0       0  81574      0   0      0    731
 3       0       0      3  60892   0      0     55
 4      11   24322      0      0   0  20597    860
 5       0       1      0      0   0    145      1
-1       0       0      0      0   0      0      0

th: 15 hidden: 4 acc:0.8683773242351276 recall:0.018781393317318193 precision:0.035292186474064347 f1:0.02451609224892386
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.04      0.02      0.02     45790
           0       1.00      1.00      1.00    202228
           1       0.81      0.80      0.80    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.99      0.01       147

    accuracy                           0.86    519956
   macro avg       0.64      0.80      0.64    519956
weighted avg       0.87      0.86      0.86    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 4

         0       1      2      3   4      5     -1
 0  201519       0      0      0   0    582    127
 1     354  100134     18      1   0   2637  25392
 2       0       0  81206      0   0      0   1099
 3       0       0      3  60890   0      0     57
 4      11   24322      0      0   0  20595    862
 5       0       1      0      0   0    145      1
-1       0       0      0      0   0      0      0

th: 16 hidden: 4 acc:0.8622883474755556 recall:0.018825070976195676 precision:0.03130220059554071 f1:0.023510800785511675
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.03      0.02      0.02     45790
           0       1.00      1.00      1.00    202228
           1       0.80      0.78      0.79    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.99      0.01       147

    accuracy                           0.86    519956
   macro avg       0.64      0.79      0.64    519956
weighted avg       0.87      0.86      0.86    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 4

         0      1      2      3   4      5     -1
 0  201499      0      0      0   0    582    147
 1     354  98095     16      1   0   2611  27459
 2       0      0  80430      0   0      0   1875
 3       0      0      3  60883   0      0     64
 4      11  24217      0      0   0  20572    990
 5       0      1      0      0   0    144      2
-1       0      0      0      0   0      0      0

th: 17 hidden: 4 acc:0.8570129010916309 recall:0.021620441144354664 precision:0.032419687592101384 f1:0.025941016940270154
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.03      0.02      0.03     45790
           0       1.00      1.00      1.00    202228
           1       0.80      0.76      0.78    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.98      0.01       147

    accuracy                           0.85    519956
   macro avg       0.64      0.79      0.63    519956
weighted avg       0.86      0.85      0.86    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 4

         0      1      2      3   4      5     -1
 0  201412      0      0      0   0    437    379
 1     354  96870     14      1   0   2591  28706
 2       0      0  79437      0   0      0   2868
 3       0      0      3  60883   0      0     64
 4      11  23436      0      0   0  20572   1771
 5       0      1      0      0   0    143      3
-1       0      0      0      0   0      0      0

th: 18 hidden: 4 acc:0.8537587795890421 recall:0.03867656693601223 precision:0.05241040513746264 f1:0.04450811123258064
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.05      0.04      0.04     45790
           0       1.00      1.00      1.00    202228
           1       0.81      0.75      0.78    128536
           2       1.00      0.97      0.98     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.97      0.01       147

    accuracy                           0.85    519956
   macro avg       0.64      0.79      0.64    519956
weighted avg       0.87      0.85      0.86    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 4

         0      1      2      3   4      5     -1
 0  201087      0      0      0   0    291    850
 1     349  93794     14      1   0   2549  31829
 2       0      0  77998      0   0      0   4307
 3       0      0      3  60854   0      0     93
 4      11    357      0      0   0  20572  24850
 5       0      1      0      0   0    143      3
-1       0      0      0      0   0      0      0

th: 19 hidden: 4 acc:0.8884097885205672 recall:0.5426949115527407 precision:0.4012465284505587 f1:0.46137279292994926
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.40      0.54      0.46     45790
           0       1.00      0.99      1.00    202228
           1       1.00      0.73      0.84    128536
           2       1.00      0.95      0.97     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.97      0.01       147

    accuracy                           0.88    519956
   macro avg       0.73      0.86      0.71    519956
weighted avg       0.95      0.88      0.91    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 4

         0      1      2      3   4      5     -1
 0  200902      0      0      0   0    256   1070
 1     337  85139     13      0   0   2481  40566
 2       0      0  77841      0   0      0   4464
 3       0      0      3  60849   0      0     98
 4      11      0      0      0   0  20572  25207
 5       0      0      0      0   0    137     10
-1       0      0      0      0   0      0      0

th: 20 hidden: 4 acc:0.8715448999530729 recall:0.5504913736623717 precision:0.3529650633620388 f1:0.430135233138518
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.35      0.55      0.43     45790
           0       1.00      0.99      1.00    202228
           1       1.00      0.66      0.80    128536
           2       1.00      0.95      0.97     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.93      0.01       147

    accuracy                           0.87    519956
   macro avg       0.73      0.85      0.70    519956
weighted avg       0.94      0.87      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 4

         0      1      2      3   4      5     -1
 0  200621      0      0      0   0    232   1375
 1     300  80880     11      0   0   2443  44902
 2       0      0  77574      0   0      0   4731
 3       0      0      3  60842   0      0    105
 4      11      0      0      0   0  20572  25207
 5       0      0      0      0   0    120     27
-1       0      0      0      0   0      0      0

th: 20.5 hidden: 4 acc:0.8620594819561656 recall:0.5504913736623717 precision:0.3301635951641846 f1:0.41276599228734945
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.33      0.55      0.41     45790
           0       1.00      0.99      1.00    202228
           1       1.00      0.63      0.77    128536
           2       1.00      0.94      0.97     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.82      0.01       147

    accuracy                           0.86    519956
   macro avg       0.72      0.82      0.69    519956
weighted avg       0.94      0.86      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 4

         0      1      2      3   4      5     -1
 0  200334      0      0      0   0    212   1682
 1     265  71643     11      0   0   2418  54199
 2       0      0  77339      0   0      0   4966
 3       0      0      3  60832   0      0    115
 4      11      0      0      0   0  20572  25207
 5       0      0      0      0   0    117     30
-1       0      0      0      0   0      0      0

th: 21 hidden: 4 acc:0.8431117248382556 recall:0.5504913736623717 precision:0.29242798640355455 f1:0.3819560720969172
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.29      0.55      0.38     45790
           0       1.00      0.99      0.99    202228
           1       1.00      0.56      0.72    128536
           2       1.00      0.94      0.97     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.80      0.01       147

    accuracy                           0.84    519956
   macro avg       0.72      0.81      0.68    519956
weighted avg       0.94      0.84      0.87    519956

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 5

         0       1      2      3      4   5    -1
 0  201899     196      0      0      0   0   133
 1     168  120434     13      1    160   0  7760
 2       0       0  81900      0      0   0   405
 3       0       0      3  60928      0   0    19
 4       0      55      0      0  45697   0    38
 5       0      89      0      0     14   0    44
-1       0       0      0      0      0   0     0

th: 15 hidden: 5 acc:0.9837332389663741 recall:0.29931972789115646 precision:0.00523871889510656 f1:0.01029721507137842
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.30      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.94      0.97    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.98    519956
   macro avg       0.83      0.87      0.83    519956
weighted avg       1.00      0.98      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 5

         0       1      2      3      4   5    -1
 0  201881     195      0      0      0   0   152
 1     164  118245     13      1    158   0  9955
 2       0       0  81874      0      0   0   431
 3       0       0      3  60912      0   0    35
 4       0      48      0      0  45689   0    53
 5       0      77      0      0     14   0    56
-1       0       0      0      0      0   0     0

th: 16 hidden: 5 acc:0.9793886405772796 recall:0.38095238095238093 precision:0.005242463958060288 f1:0.010342598577892695
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.38      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.92      0.96    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.98    519956
   macro avg       0.83      0.88      0.83    519956
weighted avg       1.00      0.98      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 5

         0       1      2      3      4   5     -1
 0  201777     195      0      0      0   0    256
 1     160  115136     13      0    152   0  13075
 2       0       0  81828      0      0   0    477
 3       0       0      3  60903      0   0     44
 4       0      48      0      0  45663   0     79
 5       0      66      0      0     14   0     67
-1       0       0      0      0      0   0      0

th: 17 hidden: 5 acc:0.9730534891413889 recall:0.4557823129251701 precision:0.004786398056865267 f1:0.009473312124425592
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.46      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.90      0.94    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.97    519956
   macro avg       0.83      0.89      0.82    519956
weighted avg       1.00      0.97      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 5

         0       1      2      3      4   5     -1
 0  201584     195      0      0      0   0    449
 1     152  106896     13      0    144   0  21331
 2       0       0  81760      0      0   0    545
 3       0       0      3  60868      0   0     79
 4       0      48      0      0  45562   0    180
 5       0      66      0      0     13   0     68
-1       0       0      0      0      0   0      0

th: 18 hidden: 5 acc:0.9564136196139673 recall:0.46258503401360546 precision:0.0030019424333392196 f1:0.0059651739111364534
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.46      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.83      0.91    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.96    519956
   macro avg       0.83      0.88      0.82    519956
weighted avg       1.00      0.96      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 5

         0       1      2      3      4   5     -1
 0  201262     179      0      0      0   0    787
 1     135  105310     13      0    129   0  22949
 2       0       0  81588      0      0   0    717
 3       0       0      3  60826      0   0    121
 4       0      47      0      0  45484   0    259
 5       0      66      0      0     11   0     70
-1       0       0      0      0      0   0      0

th: 19 hidden: 5 acc:0.9520921001007777 recall:0.47619047619047616 precision:0.0028109063165080513 f1:0.005588822355289421
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.48      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.82      0.90    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      1.00     45790

    accuracy                           0.95    519956
   macro avg       0.83      0.88      0.82    519956
weighted avg       1.00      0.95      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 5

         0      1      2      3      4   5     -1
 0  201092    140      0      0      0   0    996
 1     121  99523     13      0    111   0  28768
 2       0      0  81373      0      0   0    932
 3       0      0      3  60821      0   0    126
 4       0     39      0      0  45370   0    381
 5       0     50      0      0      8   0     89
-1       0      0      0      0      0   0      0

th: 20 hidden: 5 acc:0.9398776050281178 recall:0.6054421768707483 precision:0.0028441774255400743 f1:0.005661757689493941
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.61      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.77      0.87    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.94    519956
   macro avg       0.83      0.89      0.81    519956
weighted avg       1.00      0.94      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 5

         0      1      2      3      4   5     -1
 0  200901     55      0      0      0   0   1272
 1      97  96289     13      0     87   0  32050
 2       0      0  81274      0      0   0   1031
 3       0      0      3  60821      0   0    126
 4       0      8      0      0  45245   0    537
 5       0     15      0      0      7   0    125
-1       0      0      0      0      0   0      0

th: 20.5 hidden: 5 acc:0.9326135288370554 recall:0.8503401360544217 precision:0.0035570985458581146 f1:0.0070845613239628215
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.85      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.75      0.86    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.93    519956
   macro avg       0.83      0.93      0.81    519956
weighted avg       1.00      0.93      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 5

         0      1      2      3      4   5     -1
 0  200655     22      0      0      0   0   1551
 1      50  93150     13      0     85   0  35238
 2       0      0  81081      0      0   0   1224
 3       0      0      3  60821      0   0    126
 4       0      8      0      0  45070   0    712
 5       0      6      0      0      6   0    135
-1       0      0      0      0      0   0      0

th: 21 hidden: 5 acc:0.9252571371423736 recall:0.9183673469387755 precision:0.0034627815113117528 f1:0.006899547696317686
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.92      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.72      0.84    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790

    accuracy                           0.92    519956
   macro avg       0.83      0.93      0.80    519956
weighted avg       1.00      0.92      0.96    519956

# Média absolute threshold

In [15]:
for i in range(len(f1s)):
    print(f'Média f1 absolute th {ths[i]}: {np.mean(np.array(f1s[i]))}')

Média f1 absolute th 15: 0.48636407718066854
Média f1 absolute th 16: 0.48733332656136297
Média f1 absolute th 17: 0.48885414426759455
Média f1 absolute th 18: 0.48548241940464376
Média f1 absolute th 19: 0.585704233560568
Média f1 absolute th 20: 0.582632204996382
Média f1 absolute th 20.5: 0.571187890707439
Média f1 absolute th 21: 0.5503277923828185