In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture

In [2]:
def matriz_conf(y_true, y_pred, labels):
    total_labels = labels
    print(total_labels)
    cm = np.zeros((len(total_labels),len(total_labels)), dtype=int)
    for i in range(len(y_true)):
        cm[y_true[i]][y_pred[i]] += 1
    
    cm = pd.DataFrame(cm, columns=total_labels, index=total_labels)

    cm_transp = pd.DataFrame(np.transpose(cm.to_numpy()), columns=total_labels, index=total_labels)

    for c in cm_transp.columns:
        cm_transp[c] = cm_transp[c]/cm_transp[c].sum()

    cm_porcento = pd.DataFrame(np.transpose(cm_transp.to_numpy()), columns=total_labels, index=total_labels)

    return cm, cm_porcento

def acc(cm, hidden_classes):
    cm_transp = pd.DataFrame(np.transpose(cm.dropna().to_numpy()), columns=cm.columns, index=cm.columns)
    acc = 0
    total = 0
    for c in cm_transp.columns:
        if c not in hidden_classes:
            acc += cm_transp[c][c]
        else:
            acc += cm_transp[c][-1]
        total += cm_transp[c].sum()
    return acc/total

In [3]:
filenames = ['0_2','0_3','0_4','0_5','2_3','2_4','2_5','3_4','3_5','4_5']

labels_str = ['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

filenames

# pd.set_option('future.no_silent_downcasting', True)

['0_2', '0_3', '0_4', '0_5', '2_3', '2_4', '2_5', '3_4', '3_5', '4_5']

# ROC

In [4]:
from sklearn.metrics import roc_curve
exp_test = []
y_true_all_exp_test = []
for i in range(len(filenames)):
    exp_test.append(pd.read_csv(f'test_{filenames[i]}_GMM_BIC_1_10_scores.csv'))
    test_encoded_df = pd.read_csv(f'test_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_2_hidden_{filenames[i]}_hidden.csv')
    y_true_all_exp_test.append(test_encoded_df['Label'].values.tolist())

In [5]:
from sklearn.metrics import classification_report
ths = [21]
f1s = [[]]
cd_test_index = []
for i in range(len(exp_test)):
    hidden_classes = list(map(int, filenames[i].split('_'))) # Classes ocultas do treinamento
    index = 0
    cd_test_index.append([])
    for th in ths:
        y_pred = []
        for j in range(len(exp_test[i])):
            # print(exp[i][j])
            m = np.nanmax(exp_test[i].values[j])
            # print(m)
            if m > th:
                y_pred.append(exp_test[i].values[j].tolist().index(m))
            else:
                y_pred.append(-1)
                cd_test_index[-1].append(j)
        # print(y_pred[:10])

        cm, cm_porcento = matriz_conf(y_true_all_exp_test[i], y_pred, list(range(len(labels_str))) + [-1])
        print(f'th = {th} hidden = {filenames[i]}')
        display(cm)
        tp = cm[-1][hidden_classes].sum()
        fp = cm[-1].sum() - tp
        fn = cm.iloc[hidden_classes].values.sum() - tp
        tn = cm.drop(columns=[-1]).values.sum() - fn

        acc = (tp+tn)/(tp+fp+tn+fn)
        recall = tp/(tp+fn)
        precision = tp/(tp+fp)
        if precision == 0 or recall == 0:
            f1 = 0
        else:
            f1 = 2*precision*recall/(precision+recall)

        f1s[index].append(f1)
        index += 1
        print(f'th: {th} hidden: {filenames[i]} acc:{acc} recall:{recall} precision:{precision} f1:{f1}')

        true_labels = np.array(y_true_all_exp_test[i])
        true_labels[true_labels == filenames[i]] = -1

        print('MULTICLASS DETECTION')
        print(classification_report(true_labels, y_pred))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0_2

     0       1   2      3      4   5      -1
 0   0      35   0      0      0   0  252751
 1   0  142359   0     20      2   0   18289
 2   0     442   0   2620      0   0   99819
 3   0       0   0  76088      0   0      99
 4   0       0   0      0  50517   0    6721
 5   0       0   0      0      5  23     157
-1   0       0   0      0      0   0       0

th: 21 hidden: 0_2 acc:0.9563610571323508 recall:0.9912924167831145 precision:0.933129717655279 f1:0.9613321281576217
MULTICLASS DETECTION

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.00      0.00      0.00    252786
           1       1.00      0.89      0.94    160670
           2       0.00      0.00      0.00    102881
           3       0.97      1.00      0.98     76187
           4       1.00      0.88      0.94     57238
           5       1.00      0.12      0.22       185

    accuracy                           0.41    649947
   macro avg       0.57      0.41      0.44    649947
weighted avg       0.45      0.41      0.43    649947

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0_3

     0       1      2   3      4   5      -1
 0   0      11      0   0      0   0  252775
 1   0  141027     42   0     12   0   19589
 2   0       0  99297   0      0   0    3584
 3   0       0  18651   0      0   0   57536
 4   0       1      0   0  52273   0    4964
 5   0       0      0   0      9  11     165
-1   0       0      0   0      0   0       0

th: 21 hidden: 0_3 acc:0.9277418004852703 recall:0.9432719402504157 precision:0.916417857554199 f1:0.9296510112554787
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.00      0.00      0.00    252786
           1       1.00      0.88      0.93    160670
           2       0.84      0.97      0.90    102881
           3       0.00      0.00      0.00     76187
           4       1.00      0.91      0.95     57238
           5       1.00      0.06      0.11       185

    accuracy                           0.45    649947
   macro avg       0.55      0.40      0.41    649947
weighted avg       0.47      0.45      0.46    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0_4

     0       1       2      3   4      5      -1
 0   0   60545       0      0   0  49367  142874
 1   0  156289      12      0   0     89    4280
 2   0       0  102401      0   0      0     480
 3   0       0       1  76128   0      0      58
 4   0   31551       0      0   0  25597      90
 5   0       0       0      0   0    164      21
-1   0       0       0      0   0      0       0

th: 21 hidden: 0_4 acc:0.7355184345800504 recall:0.4611384925038062 precision:0.9672604750918452 f1:0.624532847560323
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.00      0.00      0.00    252786
           1       0.63      0.97      0.76    160670
           2       1.00      1.00      1.00    102881
           3       1.00      1.00      1.00     76187
           4       0.00      0.00      0.00     57238
           5       0.00      0.89      0.00       185

    accuracy                           0.52    649947
   macro avg       0.38      0.55      0.40    649947
weighted avg       0.43      0.52      0.46    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0_5

     0      1      2      3      4   5      -1
 0   0      1      0      0  17039   0  235746
 1   0  67470      2      0    475   0   92723
 2   0      0  89576      0      0   0   13305
 3   0      0      1  73830      0   0    2356
 4   0      0      0      0  53012   0    4226
 5   0      0      0      0     20   0     165
-1   0      0      0      0      0   0       0

th: 21 hidden: 0_5 acc:0.8004914246853975 recall:0.9325614398488364 precision:0.6768917798353614 f1:0.7844194103994734
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.00      0.00      0.00    252786
           1       1.00      0.42      0.59    160670
           2       1.00      0.87      0.93    102881
           3       1.00      0.97      0.98     76187
           4       0.75      0.93      0.83     57238
           5       0.00      0.00      0.00       185

    accuracy                           0.44    649947
   macro avg       0.54      0.46      0.48    649947
weighted avg       0.59      0.44      0.48    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2_3

         0       1   2   3      4   5      -1
 0  234145       3   0   0      0   0   18638
 1      12  111871   0   0      1   0   48786
 2       0    1355   0   0      0   0  101526
 3       0       0   0   0      0   0   76187
 4       0      13   0   0  46713   0   10512
 5       0       0   0   0      3   0     182
-1       0       0   0   0      0   0       0

th: 21 hidden: 2_3 acc:0.877723875946808 recall:0.9924330421962606 precision:0.6946499837783536 f1:0.8172610192251534
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.93      0.96    252786
           1       0.99      0.70      0.82    160670
           2       0.00      0.00      0.00    102881
           3       0.00      0.00      0.00     76187
           4       1.00      0.82      0.90     57238
           5       0.00      0.00      0.00       185

    accuracy                           0.60    649947
   macro avg       0.43      0.35      0.38    649947
weighted avg       0.72      0.60      0.66    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2_4

         0       1   2      3   4   5     -1
 0  251796     357   0      0   0   0    633
 1      62  145109   0     15   0  67  15417
 2    1672      50   0   3447   0   0  97712
 3       0       0   0  75090   0   0   1097
 4       0   30486   0      0   0   0  26752
 5       2       0   0      0   0  31    152
-1       0       0   0      0   0   0      0

th: 21 hidden: 2_4 acc:0.918525664400328 recall:0.7773218668615217 precision:0.8779723905391392 f1:0.8245870903200588
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       0.99      1.00      0.99    252786
           1       0.82      0.90      0.86    160670
           2       0.00      0.00      0.00    102881
           3       0.96      0.99      0.97     76187
           4       0.00      0.00      0.00     57238
           5       0.32      0.17      0.22       185

    accuracy                           0.73    649947
   macro avg       0.44      0.44      0.44    649947
weighted avg       0.70      0.73      0.71    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2_5

         0      1   2      3      4   5      -1
 0  242434      0   0      0      0   0   10352
 1      10  84130   0     26     12   0   76492
 2     238    116   0   1699      0   0  100828
 3       0      0   0  76028      0   0     159
 4       0     43   0      0  52715   0    4480
 5       0      8   0      0      9   0     168
-1       0      0   0      0      0   0       0

th: 21 hidden: 2_5 acc:0.8560605710927198 recall:0.9799157821201948 precision:0.5247117867403717 f1:0.6834559880898003
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.96      0.98    252786
           1       1.00      0.52      0.69    160670
           2       0.00      0.00      0.00    102881
           3       0.98      1.00      0.99     76187
           4       1.00      0.92      0.96     57238
           5       0.00      0.00      0.00       185

    accuracy                           0.70    649947
   macro avg       0.57      0.49      0.52    649947
weighted avg       0.84      0.70      0.75    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 3_4

         0       1      2   3   4   5     -1
 0  240952     355      0   0   0   0  11479
 1      44  110403      1   0   0   0  50222
 2       0       0  91484   0   0   0  11397
 3       0       0      1   0   0   0  76186
 4       0    3010      0   0   0   0  54228
 5       0       0      0   0   0  48    137
-1       0       0      0   0   0   0      0

th: 21 hidden: 3_4 acc:0.882688896171534 recall:0.9774330148023234 precision:0.6403861546091559 f1:0.7738004117790157
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.95      0.98    252786
           1       0.97      0.69      0.80    160670
           2       1.00      0.89      0.94    102881
           3       0.00      0.00      0.00     76187
           4       0.00      0.00      0.00     57238
           5       1.00      0.26      0.41       185

    accuracy                           0.68    649947
   macro avg       0.57      0.40      0.45    649947
weighted avg       0.79      0.68      0.73    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 3_5

         0      1      2   3      4   5      -1
 0  234806      0      0   0      0   0   17980
 1       0  26453     16   0      7   0  134194
 2       0      0  85240   0      0   0   17641
 3       0      0      1   0      0   0   76186
 4       0      0      0   0  52390   0    4848
 5       0      0      0   0      5   0     180
-1       0      0      0   0      0   0       0

th: 21 hidden: 3_5 acc:0.7312565486108867 recall:0.9999214371759283 precision:0.3042118639679081 f1:0.466498269705957
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.93      0.96    252786
           1       1.00      0.16      0.28    160670
           2       1.00      0.83      0.91    102881
           3       0.00      0.00      0.00     76187
           4       1.00      0.92      0.96     57238
           5       0.00      0.00      0.00       185

    accuracy                           0.61    649947
   macro avg       0.57      0.41      0.44    649947
weighted avg       0.88      0.61      0.67    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 4_5

         0      1      2      3   4   5      -1
 0  243622      0      0      0   0   0    9164
 1      44  18603      1      0   0   0  142022
 2       0      0  90819      0   0   0   12062
 3       0      0      1  67107   0   0    9079
 4       0      0      0      0   0   0   57238
 5       0      0      0      0   0   0     185
-1       0      0      0      0   0   0       0

th: 21 hidden: 4_5 acc:0.7348599193472699 recall:1.0 precision:0.24993688792165397 f1:0.3999192124607815
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           0       1.00      0.96      0.98    252786
           1       1.00      0.12      0.21    160670
           2       1.00      0.88      0.94    102881
           3       1.00      0.88      0.94     76187
           4       0.00      0.00      0.00     57238
           5       0.00      0.00      0.00       185

    accuracy                           0.65    649947
   macro avg       0.57      0.41      0.44    649947
weighted avg       0.91      0.65      0.69    649947

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Média absolute threshold

In [6]:
for i in range(len(f1s)):
    print(f'Média f1 absolute th {ths[i]}: {np.mean(np.array(f1s[i]))}')

Média f1 absolute th 21: 0.7265457388953662

# CD detectados

In [7]:
display(pd.DataFrame(cd_test_index))

,0,1,2,3,4,5,6,7,8,9,...,206686,206687,206688,206689,206690,206691,206692,206693,206694,206695
0,3,10,11,19,31,33,37,39,40,44,...,710024.0,710031.0,710034.0,710036.0,710038.0,710040.0,710043.0,710045.0,710048.0,710049.0
1,13,18,19,24,33,34,42,51,57,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15,16,19,30,33,55,57,80,83,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,5,6,12,19,21,27,33,46,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,33,46,323,430,516,1020,1106,1147,1477,1481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4,19,33,57,77,105,107,157,193,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
train = pd.read_csv('../../../train_CADE_cod_joined_attacks.csv')
test = pd.read_csv('../../../test_CADE_cod_joined_attacks.csv')

In [18]:
for i in range(len(filenames)):
    cd_test = test.loc[cd_test_index[i]]
    n_samples = test[test['Label'] == labels_str[filenames[i]]].shape[0]
    print(cd_test['Label'].value_counts())
    cd_test['Label'] = 'New Concept'
    retrain = pd.concat([train,cd_test], ignore_index=True)
    new_test = test.drop(cd_test_index[i])
    new_samples = train[train['Label'] == labels_str[filenames[i]]].sample(frac=n_samples/train[train['Label'] == labels_str[filenames[i]]].shape[0], random_state=123)
    new_test = pd.concat([new_test,new_samples],ignore_index=True)
    print(retrain['Label'].value_counts())
    print(new_test['Label'].value_counts())
    retrain.to_csv(f'retrain_hidden_{filenames[i]}_CADE_cod_joined_attacks.csv',index=False)
    new_test.to_csv(f'retest_hidden_{filenames[i]}_CADE_cod_joined_attacks.csv',index=False)

Label
DDoS             185839
Benign            14778
Infilteration      5366
DoS                 460
Bot                 193
BruteForce           47
Web                  13
Name: count, dtype: int64
Label
DDoS             808918
Benign           514148
DoS              418752
BruteForce       243804
New Concept      206696
Bot              183163
Infilteration    102810
Web                 595
Name: count, dtype: int64
Label
DDoS             319733
Benign           145892
DoS              130400
BruteForce        76141
Bot               57045
Infilteration     26761
Web                 172
Name: count, dtype: int64
Label
DoS              100917
Benign            25230
Infilteration      7484
DDoS                553
Bot                 114
Web                  14
BruteForce           14
Name: count, dtype: int64
Label
DDoS             808918
Benign           514148
DoS              418752
BruteForce       243804
Bot              183163
New Concept      134326
Infilteration    102810
Web                 595
Name: count, dtype: int64
Label
DDoS             252233
DoS              160803
Benign           135440
BruteForce        76174
Bot               57124
Infilteration     24643
Web                 171
Name: count, dtype: int64
Label
BruteForce       37536
Benign           18223
Infilteration     5420
DoS                298
Bot                240
DDoS               165
Web                  9
Name: count, dtype: int64
Label
DDoS             808918
Benign           514148
DoS              418752
BruteForce       243804
Bot              183163
Infilteration    102810
New Concept       61891
Web                 595
Name: count, dtype: int64
Label
DDoS             252621
Benign           142447
DoS              130562
BruteForce       114840
Bot               56998
Infilteration     26707
Web                 176
Name: count, dtype: int64
Label
Bot              48960
Benign           31837
Infilteration     9374
DoS                658
DDoS               150
Web                 35
BruteForce          11
Name: count, dtype: int64
Label
DDoS             808918
Benign           514148
DoS              418752
BruteForce       243804
Bot              183163
Infilteration    102810
New Concept       91025
Web                 595
Name: count, dtype: int64
Label
DDoS             252636
DoS              130202
Benign           128833
BruteForce        76177
Bot               65516
Infilteration     22753
Web                 150
Name: count, dtype: int64
Label
Benign           2943
Infilteration    1432
DoS               266
DDoS              151
Bot                68
BruteForce         59
Web                 6
Name: count, dtype: int64
Label
DDoS             808918
Benign           514148
DoS              418752
BruteForce       243804
Bot              183163
Infilteration    102810
New Concept        4925
Web                 595
Name: count, dtype: int64
Label
DDoS             252635
Benign           157727
DoS              130594
BruteForce        76129
Infilteration     62822
Bot               57170
Web                 179
Name: count, dtype: int64
Label
Benign           26189
Infilteration     7515
DoS                417
Bot                199
DDoS               156
Web                 98
BruteForce          10
Name: count, dtype: int64
Label
DDoS             808918
Benign           514148
DoS              418752
BruteForce       243804
Bot              183163
Infilteration    102810
New Concept       34584
Web                 595
Name: count, dtype: int64
Label
DDoS             252630
Benign           134481
DoS              130443
BruteForce        76178
Bot               57039
Infilteration     24612
Web                 272
Name: count, dtype: int64