In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture

In [2]:
def matriz_conf(y_true, y_pred, labels):
    total_labels = labels
    print(total_labels)
    cm = np.zeros((len(total_labels),len(total_labels)), dtype=int)
    for i in range(len(y_true)):
        cm[y_true[i]][y_pred[i]] += 1

    
    cm = pd.DataFrame(cm, columns=total_labels, index=total_labels)

    cm_transp = pd.DataFrame(np.transpose(cm.to_numpy()), columns=total_labels, index=total_labels)

    for c in cm_transp.columns:
        cm_transp[c] = cm_transp[c]/cm_transp[c].sum()

    cm_porcento = pd.DataFrame(np.transpose(cm_transp.to_numpy()), columns=total_labels, index=total_labels)

    return cm, cm_porcento

def acc(cm, hidden_classes):
    cm_transp = pd.DataFrame(np.transpose(cm.dropna().to_numpy()), columns=cm.columns, index=cm.columns)
    acc = 0
    total = 0
    for c in cm_transp.columns:
        if c not in hidden_classes:
            acc += cm_transp[c][c]
        else:
            acc += cm_transp[c][-1]
        total += cm_transp[c].sum()
    return acc/total

In [3]:
filenames = [0,2,3,4,5]

labels_str = ['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

filenames

# pd.set_option('future.no_silent_downcasting', True)

[0, 2, 3, 4, 5]

In [4]:
exp_val = []
y_true_all_exp_val = []
for i in range(len(filenames)):
    exp_val.append(pd.read_csv(f'val_{filenames[i]}_GMM_BIC_1_10_scores_corr.csv'))
    y_true_all_exp_val.append(exp_val[i]['Label'].values.tolist())
    exp_val[i] = exp_val[i].drop(columns=['Label'])

In [5]:
from sklearn.metrics import classification_report
ths = [19, 20, 21, 22, 23, 24, 25, 26]
f1s = [[],[],[],[],[],[],[],[]]
for i in range(len(exp_val)):
    index = 0
    for th in ths:
        y_pred = []
        prog= 0
        for j in range(len(exp_val[i])):
            # print(exp[i][j])
            m = np.nanmax(exp_val[i].values[j])
            # print(m)
            if m > th:
                y_pred.append(exp_val[i].values[j].tolist().index(m))
            else:
                y_pred.append(-1)
        # print(y_pred[:10])

        cm, cm_porcento = matriz_conf(y_true_all_exp_val[i], y_pred, list(range(len(labels_str))) + [-1])
        print(f'th = {th} hidden = {filenames[i]}')
        display(cm)
        tp = cm[-1][filenames[i]]
        fp = cm[-1].sum() - tp
        fn = cm.iloc[filenames[i]].sum() - tp
        tn = cm.drop(columns=[-1]).values.sum() - fn

        acc = (tp+tn)/(tp+fp+tn+fn)
        recall = tp/(tp+fn)
        precision = tp/(tp+fp)
        if precision == 0 or recall == 0:
            f1 = 0
        else:
            f1 = 2*precision*recall/(precision+recall)

        f1s[index].append(f1)
        index += 1
        print(f'th: {th} hidden: {filenames[i]} acc:{acc} recall:{recall} precision:{precision} f1:{f1}')

        true_labels = np.array(y_true_all_exp_val[i])
        true_labels[true_labels == filenames[i]] = -1

        print('MULTICLASS DETECTION')
        print(classification_report(true_labels, y_pred))

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 0

     0       1      2      3      4      5      -1
 0   0   70024      0      0      0  21178  111026
 1   0  126923     36      2    152    394    1029
 2   0       1  82213      0      0      0      91
 3   0       0      3  60934      0      0      13
 4   0      59      0      0  45372    205     154
 5   0       6      0      0      6    130       5
-1   0       0      0      0      0      0       0

th: 19 hidden: 0 acc:0.8221118710044696 recall:0.5490139842158356 precision:0.988496946170694 f1:0.7059444405587736
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.99      0.55      0.71    202228
           1       0.64      0.99      0.78    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.01      0.88      0.01       147

    accuracy                           0.82    519956
   macro avg       0.77      0.90      0.75    519956
weighted avg       0.91      0.82      0.83    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 0

     0       1      2      3      4    5      -1
 0   0   64155      0      0      0    0  138073
 1   0  126047     36      2    141  342    1968
 2   0       1  82126      0      0    0     178
 3   0       0      3  60934      0    0      13
 4   0      43      0      0  45371  199     177
 5   0       6      0      0      6  129       6
-1   0       0      0      0      0    0       0

th: 20 hidden: 0 acc:0.8721103324127426 recall:0.6827590640267421 precision:0.983320870277392 f1:0.8059292032815497
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.98      0.68      0.81    202228
           1       0.66      0.98      0.79    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.19      0.88      0.32       147

    accuracy                           0.87    519956
   macro avg       0.81      0.92      0.82    519956
weighted avg       0.91      0.87      0.87    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0

     0       1      2      3      4    5      -1
 0   0   57387      0      0      0    0  144841
 1   0  124758     34      2    130  340    3272
 2   0       1  82023      0      0    0     281
 3   0       0      3  60934      0    0      13
 4   0      34      0      0  45366  199     191
 5   0       6      0      0      6  129       6
-1   0       0      0      0      0    0       0

th: 21 hidden: 0 acc:0.8823938948680273 recall:0.716226239689855 precision:0.9746776668191973 f1:0.8257000501664614
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.72      0.83    202228
           1       0.68      0.97      0.80    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.19      0.88      0.32       147

    accuracy                           0.88    519956
   macro avg       0.81      0.93      0.82    519956
weighted avg       0.91      0.88      0.88    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 0

     0       1      2      3      4    5      -1
 0   0   53478      0      0      0    0  148750
 1   0  124002     34      1    122  334    4043
 2   0       1  81919      0      0    0     385
 3   0       0      3  60915      0    0      32
 4   0      34      0      0  45355  199     202
 5   0       6      0      0      6  125      10
-1   0       0      0      0      0    0       0

th: 22 hidden: 0 acc:0.8881636138442484 recall:0.7355559071938604 precision:0.96954804395719 f1:0.8364965556024181
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.74      0.84    202228
           1       0.70      0.96      0.81    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.19      0.85      0.31       147

    accuracy                           0.89    519956
   macro avg       0.81      0.92      0.82    519956
weighted avg       0.91      0.89      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 0

     0       1      2      3      4    5      -1
 0   0   48033      0      0      0    0  154195
 1   0  122105     14      1    113  225    6078
 2   0       1  81550      0      0    0     754
 3   0       0      3  60915      0    0      32
 4   0      29      0      0  45331  197     233
 5   0       4      0      0      6  120      17
-1   0       0      0      0      0    0       0

th: 23 hidden: 0 acc:0.8939391025394456 recall:0.762480962082402 precision:0.9558983069760522 f1:0.8483042991497426
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.96      0.76      0.85    202228
           1       0.72      0.95      0.82    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.22      0.82      0.35       147

    accuracy                           0.89    519956
   macro avg       0.82      0.92      0.83    519956
weighted avg       0.91      0.89      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 0

     0       1      2      3      4    5      -1
 0   0   46696      0      0      0    0  155532
 1   0  120116      3      1    102  115    8199
 2   0       1  80889      0      0    0    1415
 3   0       0      3  60914      0    0      33
 4   0       2      0      0  45244  144     400
 5   0       0      0      0      6   73      68
-1   0       0      0      0      0    0       0

th: 24 hidden: 0 acc:0.8907388317473017 recall:0.7690923116482387 precision:0.9389364129745784 f1:0.8455698267074414
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.94      0.77      0.85    202228
           1       0.72      0.93      0.81    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.22      0.50      0.30       147

    accuracy                           0.89    519956
   macro avg       0.81      0.86      0.82    519956
weighted avg       0.91      0.89      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 0

     0       1      2      3      4   5      -1
 0   0   40858      0      0      0   0  161370
 1   0  118837      3      1     85  48    9562
 2   0       1  80717      0      0   0    1587
 3   0       0      3  60895      0   0      52
 4   0       2      0      0  44867   0     921
 5   0       0      0      0      5  50      92
-1   0       0      0      0      0   0       0

th: 25 hidden: 0 acc:0.8979298248313319 recall:0.7979607176058706 precision:0.929636372015854 f1:0.8587804540568157
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.93      0.80      0.86    202228
           1       0.74      0.92      0.82    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790
           5       0.51      0.34      0.41       147

    accuracy                           0.90    519956
   macro avg       0.86      0.84      0.85    519956
weighted avg       0.91      0.90      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 0

     0       1      2      3      4   5      -1
 0   0   23509      0      0      0   0  178719
 1   0  117101      3      0     10  48   11374
 2   0       1  80179      0      0   0    2125
 3   0       0      3  60882      0   0      65
 4   0       0      0      0  41877   0    3913
 5   0       0      0      0      4  50      93
-1   0       0      0      0      0   0       0

th: 26 hidden: 0 acc:0.920995238058605 recall:0.8837500247245683 precision:0.9104891257278809 f1:0.8969203321313771
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.91      0.88      0.90    202228
           1       0.83      0.91      0.87    128536
           2       1.00      0.97      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.91      0.96     45790
           5       0.51      0.34      0.41       147

    accuracy                           0.92    519956
   macro avg       0.88      0.84      0.85    519956
weighted avg       0.92      0.92      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 2

         0       1   2      3      4   5     -1
 0  202197       9   0      0      0   2     20
 1    2491  123519   0      4    121  75   2326
 2       0     908   0   1401      0   0  79996
 3       0       0   0  60935      0   0     15
 4      11      13   0      0  45669   0     97
 5       1       4   0      0      9  76     57
-1       0       0   0      0      0   0      0

th: 19 hidden: 2 acc:0.9907222918862365 recall:0.971945811311585 precision:0.9695192156197355 f1:0.9707309969905834
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.97      0.97     82305
           0       0.99      1.00      0.99    202228
           1       0.99      0.96      0.98    128536
           3       0.98      1.00      0.99     60950
           4       1.00      1.00      1.00     45790
           5       0.50      0.52      0.51       147

    accuracy                           0.99    519956
   macro avg       0.90      0.91      0.91    519956
weighted avg       0.99      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 2

         0       1   2      3      4   5     -1
 0  202170       6   0      0      0   0     52
 1    2488  122374   0      2    117  58   3497
 2       0     662   0   1276      0   0  80367
 3       0       0   0  60932      0   0     18
 4      11      11   0      0  45644   0    124
 5       1       4   0      0      9  68     65
-1       0       0   0      0      0   0      0

th: 20 hidden: 2 acc:0.9890490733831324 recall:0.9764534353927465 precision:0.9553510930423309 f1:0.9657870069940154
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.96      0.98      0.97     82305
           0       0.99      1.00      0.99    202228
           1       0.99      0.95      0.97    128536
           3       0.98      1.00      0.99     60950
           4       1.00      1.00      1.00     45790
           5       0.54      0.46      0.50       147

    accuracy                           0.98    519956
   macro avg       0.91      0.90      0.90    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2

         0       1   2      3      4   5     -1
 0  202050       3   0      0      0   0    175
 1    2478  121364   0      2    111  54   4527
 2       0     168   0   1225      0   0  80912
 3       0       0   0  60925      0   0     25
 4      11      11   0      0  45619   0    149
 5       1       4   0      0      8  66     68
-1       0       0   0      0      0   0      0

th: 21 hidden: 2 acc:0.9878124302825624 recall:0.9830751473179029 precision:0.9424152068579947 f1:0.9623158758570655
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.94      0.98      0.96     82305
           0       0.99      1.00      0.99    202228
           1       1.00      0.94      0.97    128536
           3       0.98      1.00      0.99     60950
           4       1.00      1.00      1.00     45790
           5       0.55      0.45      0.49       147

    accuracy                           0.98    519956
   macro avg       0.91      0.90      0.90    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 2

         0       1   2      3      4   5     -1
 0  201976       3   0      0      0   0    249
 1    2472  120123   0      1     99  48   5793
 2       0      10   0   1198      0   0  81097
 3       0       0   0  60894      0   0     56
 4      11       8   0      0  45462   0    309
 5       1       4   0      0      7  50     85
-1       0       0   0      0      0   0      0

th: 22 hidden: 2 acc:0.9851910546276993 recall:0.9853228843934148 precision:0.925881103791572 f1:0.9546776225175698
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.93      0.99      0.95     82305
           0       0.99      1.00      0.99    202228
           1       1.00      0.93      0.97    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.99      1.00     45790
           5       0.51      0.34      0.41       147

    accuracy                           0.98    519956
   macro avg       0.90      0.88      0.88    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 2

         0       1   2      3      4   5     -1
 0  201947       1   0      0      0   0    280
 1    2339  118978   0      1     79  48   7091
 2       0       4   0   1164      0   0  81137
 3       0       0   0  60875      0   0     75
 4       9       7   0      0  45162   0    612
 5       1       4   0      0      6  31    105
-1       0       0   0      0      0   0      0

th: 23 hidden: 2 acc:0.9820542507442938 recall:0.9858088815989308 precision:0.9085890257558791 f1:0.9456251274729757
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.91      0.99      0.95     82305
           0       0.99      1.00      0.99    202228
           1       1.00      0.93      0.96    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.99      0.99     45790
           5       0.39      0.21      0.27       147

    accuracy                           0.98    519956
   macro avg       0.88      0.85      0.86    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 2

         0       1   2      3      4   5     -1
 0  201631       1   0      0      0   0    596
 1     480  118061   0      1     58  48   9888
 2       0       1   0   1133      0   0  81171
 3       0       0   0  60872      0   0     78
 4       9       6   0      0  44604   0   1171
 5       1       4   0      0      5  24    113
-1       0       0   0      0      0   0      0

th: 24 hidden: 2 acc:0.9750363492295502 recall:0.9862219792236194 precision:0.8726469355064128 f1:0.9259647962035569
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.87      0.99      0.93     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.92      0.96    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.97      0.99     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.97    519956
   macro avg       0.86      0.84      0.85    519956
weighted avg       0.98      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 2

         0       1   2      3      4   5     -1
 0  201053       1   0      0      0   0   1174
 1     477  117085   0      1     36  48  10889
 2       0       1   0   1107      0   0  81197
 3       0       0   0  60866      0   0     84
 4       9       6   0      0  43235   0   2540
 5       1       4   0      0      5  24    113
-1       0       0   0      0      0   0      0

th: 25 hidden: 2 acc:0.9694051035087584 recall:0.9865378774072049 precision:0.8458285154744419 f1:0.9107805857477763
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.85      0.99      0.91     82305
           0       1.00      0.99      1.00    202228
           1       1.00      0.91      0.95    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.94      0.97     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.97    519956
   macro avg       0.86      0.83      0.84    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 2

         0       1   2      3      4   5     -1
 0  199813       1   0      0      0   0   2414
 1     476  114003   0      1     21  48  13987
 2       0       1   0   1061      0   0  81243
 3       0       0   0  60818      0   0    132
 4       9       6   0      0  39328   0   6447
 5       1       0   0      0      2  24    120
-1       0       0   0      0      0   0      0

th: 26 hidden: 2 acc:0.9535306833655155 recall:0.9870967741935484 precision:0.7786147609326931 f1:0.8705477690626204
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.78      0.99      0.87     82305
           0       1.00      0.99      0.99    202228
           1       1.00      0.89      0.94    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.86      0.92     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.95    519956
   macro avg       0.85      0.81      0.82    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 3

         0       1      2   3      4    5     -1
 0  201982      52      0   0      0    0    194
 1     785  123906     34   0    174  286   3351
 2       0       0  82116   0      0    0    189
 3       0       0      3   0      0    0  60947
 4       2      14      0   0  45537   98    139
 5       0       9      0   0      9  117     12
-1       0       0      0   0      0    0      0

th: 19 hidden: 3 acc:0.9925224442068175 recall:0.9999507793273175 precision:0.9400758884501481 f1:0.969089376858374
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.94      1.00      0.97     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.96      0.98    128536
           2       1.00      1.00      1.00     82305
           4       1.00      0.99      1.00     45790
           5       0.23      0.80      0.36       147

    accuracy                           0.99    519956
   macro avg       0.86      0.96      0.88    519956
weighted avg       0.99      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 3

         0       1      2   3      4    5     -1
 0  201886      39      0   0      0    0    303
 1     785  121843     34   0     95  245   5534
 2       0       0  81998   0      0    0    307
 3       0       0      3   0      0    0  60947
 4       1       8      0   0  45336    8    437
 5       0       9      0   0      9  114     15
-1       0       0      0   0      0    0      0

th: 20 hidden: 3 acc:0.9873085414919724 recall:0.9999507793273175 precision:0.9023436921664717 f1:0.9486431167456593
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.90      1.00      0.95     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.95      0.97    128536
           2       1.00      1.00      1.00     82305
           4       1.00      0.99      0.99     45790
           5       0.31      0.78      0.44       147

    accuracy                           0.98    519956
   macro avg       0.87      0.95      0.89    519956
weighted avg       0.99      0.98      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 3

         0       1      2   3      4    5     -1
 0  201596       4      0   0      0    0    628
 1     784  120164     32   0     92  201   7263
 2       0       0  81748   0      0    0    557
 3       0       0      3   0      0    0  60947
 4       1       8      0   0  45309    0    472
 5       0       5      0   0      9  108     25
-1       0       0      0   0      0    0      0

th: 21 hidden: 3 acc:0.9827908515335914 recall:0.9999507793273175 precision:0.8720168259600527 f1:0.9316121734611211
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.87      1.00      0.93     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.93      0.97    128536
           2       1.00      0.99      1.00     82305
           4       1.00      0.99      0.99     45790
           5       0.35      0.73      0.47       147

    accuracy                           0.98    519956
   macro avg       0.87      0.94      0.89    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 3

         0       1      2   3      4    5     -1
 0  201072       3      0   0      0    0   1153
 1     774  117610     32   0     90  109   9921
 2       0       0  81450   0      0    0    855
 3       0       0      3   0      0    0  60947
 4       1       6      0   0  45275    0    508
 5       0       4      0   0      8  101     34
-1       0       0      0   0      0    0      0

th: 22 hidden: 3 acc:0.9760095084968728 recall:0.9999507793273175 precision:0.8301370236181863 f1:0.9071653965229817
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.83      1.00      0.91     60950
           0       1.00      0.99      1.00    202228
           1       1.00      0.91      0.96    128536
           2       1.00      0.99      0.99     82305
           4       1.00      0.99      0.99     45790
           5       0.48      0.69      0.57       147

    accuracy                           0.97    519956
   macro avg       0.88      0.93      0.90    519956
weighted avg       0.98      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 3

         0       1      2   3      4   5     -1
 0  200924       3      0   0      0   0   1301
 1     704  114451     32   0     83  48  13218
 2       0       0  80933   0      0   0   1372
 3       0       0      3   0      0   0  60947
 4       1       0      0   0  45190   0    599
 5       0       4      0   0      7  75     61
-1       0       0      0   0      0   0      0

th: 23 hidden: 3 acc:0.9681626906892121 recall:0.9999507793273175 precision:0.7864331982760846 f1:0.8804316422050156
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.79      1.00      0.88     60950
           0       1.00      0.99      1.00    202228
           1       1.00      0.89      0.94    128536
           2       1.00      0.98      0.99     82305
           4       1.00      0.99      0.99     45790
           5       0.61      0.51      0.56       147

    accuracy                           0.97    519956
   macro avg       0.90      0.89      0.89    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 3

         0       1      2   3      4   5     -1
 0  199048       3      0   0      0   0   3177
 1     471  113364     31   0     72  41  14557
 2       0       0  79741   0      0   0   2564
 3       0       0      3   0      0   0  60947
 4       1       0      0   0  44424   0   1365
 5       0       4      0   0      5  73     65
-1       0       0      0   0      0   0      0

th: 24 hidden: 3 acc:0.9582060789759134 recall:0.9999507793273175 precision:0.7371877834895676 f1:0.8486962576153176
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.74      1.00      0.85     60950
           0       1.00      0.98      0.99    202228
           1       1.00      0.88      0.94    128536
           2       1.00      0.97      0.98     82305
           4       1.00      0.97      0.98     45790
           5       0.64      0.50      0.56       147

    accuracy                           0.96    519956
   macro avg       0.90      0.88      0.88    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 3

         0       1      2   3      4   5     -1
 0  198162       3      0   0      0   0   4063
 1     405  111255     20   0     52   3  16801
 2       0       0  79006   0      0   0   3299
 3       0       0      3   0      0   0  60947
 4       1       0      0   0  43847   0   1942
 5       0       4      0   0      5  30    108
-1       0       0      0   0      0   0      0

th: 25 hidden: 3 acc:0.9495803491064628 recall:0.9999507793273175 precision:0.6992542450665443 f1:0.8229964215785565
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.70      1.00      0.82     60950
           0       1.00      0.98      0.99    202228
           1       1.00      0.87      0.93    128536
           2       1.00      0.96      0.98     82305
           4       1.00      0.96      0.98     45790
           5       0.91      0.20      0.33       147

    accuracy                           0.95    519956
   macro avg       0.93      0.83      0.84    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 3

         0       1      2   3      4   5     -1
 0  197152       3      0   0      0   0   5073
 1     401  106764     20   0      2   0  21349
 2       0       0  78167   0      0   0   4138
 3       0       0      3   0      0   0  60947
 4       0       0      0   0  40732   0   5058
 5       0       0      0   0      5   4    138
-1       0       0      0   0      0   0      0

th: 26 hidden: 3 acc:0.9312268730431037 recall:0.9999507793273175 precision:0.6302493200831412 f1:0.773179070490254
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.63      1.00      0.77     60950
           0       1.00      0.97      0.99    202228
           1       1.00      0.83      0.91    128536
           2       1.00      0.95      0.97     82305
           4       1.00      0.89      0.94     45790
           5       1.00      0.03      0.05       147

    accuracy                           0.93    519956
   macro avg       0.94      0.78      0.77    519956
weighted avg       0.96      0.93      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 4

         0       1      2      3   4      5    -1
 0  201405     282      0      0   0      0   541
 1     462  122881     33      1   0     84  5075
 2       0       0  81795      0   0      0   510
 3       0       0      3  60888   0      0    59
 4       1   24192      0      0   0  20276  1321
 5       0      12      0      0   0     94    41
-1       0       0      0      0   0      0     0

th: 19 hidden: 4 acc:0.9025013655001577 recall:0.02884909368857829 precision:0.1750364383198622 f1:0.049534094531000994
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.18      0.03      0.05     45790
           0       1.00      1.00      1.00    202228
           1       0.83      0.96      0.89    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.00      0.64      0.01       147

    accuracy                           0.90    519956
   macro avg       0.67      0.77      0.66    519956
weighted avg       0.89      0.90      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 4

         0       1      2      3   4      5    -1
 0  201233     282      0      0   0      0   713
 1     437  121263     33      1   0     73  6729
 2       0       0  81702      0   0      0   603
 3       0       0      3  60887   0      0    60
 4       1   24186      0      0   0  14318  7285
 5       0      11      0      0   0     84    52
-1       0       0      0      0   0      0     0

th: 20 hidden: 4 acc:0.9102577910438575 recall:0.15909587246123608 precision:0.47176531537365624 f1:0.23794747844264436
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.47      0.16      0.24     45790
           0       1.00      1.00      1.00    202228
           1       0.83      0.94      0.88    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.57      0.01       147

    accuracy                           0.91    519956
   macro avg       0.72      0.78      0.69    519956
weighted avg       0.91      0.91      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 4

         0       1      2      3   4   5     -1
 0  200679     282      0      0   0   0   1267
 1     410  118693     32      1   0  61   9339
 2       0       0  81520      0   0   0    785
 3       0       0      3  60883   0   0     64
 4       1   24184      0      0   0   0  21605
 5       0       5      0      0   0  69     73
-1       0       0      0      0   0   0      0

th: 21 hidden: 4 acc:0.9313153420674057 recall:0.4718279100240227 precision:0.6520689342951136 f1:0.5474956603271544
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.65      0.47      0.55     45790
           0       1.00      0.99      1.00    202228
           1       0.83      0.92      0.87    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.53      0.47      0.50       147

    accuracy                           0.93    519956
   macro avg       0.83      0.81      0.82    519956
weighted avg       0.93      0.93      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 4

         0       1      2      3   4   5     -1
 0  200644     281      0      0   0   0   1303
 1     404  115562     32      0   0  53  12485
 2       0       0  81286      0   0   0   1019
 3       0       0      3  60584   0   0    363
 4       1   24184      0      0   0   0  21605
 5       0       5      0      0   0  26    116
-1       0       0      0      0   0   0      0

th: 22 hidden: 4 acc:0.9240878074298594 recall:0.4718279100240227 precision:0.585644195061126 f1:0.5226109988993842
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.59      0.47      0.52     45790
           0       1.00      0.99      1.00    202228
           1       0.83      0.90      0.86    128536
           2       1.00      0.99      0.99     82305
           3       1.00      0.99      1.00     60950
           5       0.33      0.18      0.23       147

    accuracy                           0.92    519956
   macro avg       0.79      0.75      0.77    519956
weighted avg       0.92      0.92      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 4

         0       1      2      3   4   5     -1
 0  200379     281      0      0   0   0   1568
 1     402  111836      3      0   0  50  16245
 2       0       0  80142      0   0   0   2163
 3       0       0      3  60568   0   0    379
 4       1   24035      0      0   0   0  21754
 5       0       5      0      0   0  24    118
-1       0       0      0      0   0   0      0

th: 23 hidden: 4 acc:0.9143985260291255 recall:0.47508189561039527 precision:0.5151680204608425 f1:0.49431359850937884
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.52      0.48      0.49     45790
           0       1.00      0.99      0.99    202228
           1       0.82      0.87      0.85    128536
           2       1.00      0.97      0.99     82305
           3       1.00      0.99      1.00     60950
           5       0.32      0.16      0.22       147

    accuracy                           0.91    519956
   macro avg       0.78      0.74      0.76    519956
weighted avg       0.91      0.91      0.91    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 4

         0       1      2      3   4   5     -1
 0  199832      94      0      0   0   0   2302
 1       5  107067      3      0   0  48  21413
 2       0       0  79164      0   0   0   3141
 3       0       0      3  60527   0   0    420
 4       1    2410      0      0   0   0  43379
 5       0       1      0      0   0  24    122
-1       0       0      0      0   0   0      0

th: 24 hidden: 4 acc:0.9426701490126087 recall:0.9473465822231928 precision:0.612896845020275 f1:0.7442758242041058
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.61      0.95      0.74     45790
           0       1.00      0.99      0.99    202228
           1       0.98      0.83      0.90    128536
           2       1.00      0.96      0.98     82305
           3       1.00      0.99      1.00     60950
           5       0.33      0.16      0.22       147

    accuracy                           0.94    519956
   macro avg       0.82      0.81      0.81    519956
weighted avg       0.96      0.94      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 4

         0      1      2      3   4   5     -1
 0  199026      1      0      0   0   0   3201
 1       3  91988      3      0   0  48  36494
 2       0      0  75374      0   0   0   6931
 3       0      0      3  60478   0   0    469
 4       1      4      0      0   0   0  45785
 5       0      0      0      0   0  24    123
-1       0      0      0      0   0   0      0

th: 25 hidden: 4 acc:0.9091788535953043 recall:0.9998908058528063 precision:0.4922959474425556 f1:0.6597594979573898
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.49      1.00      0.66     45790
           0       1.00      0.98      0.99    202228
           1       1.00      0.72      0.83    128536
           2       1.00      0.92      0.96     82305
           3       1.00      0.99      1.00     60950
           5       0.33      0.16      0.22       147

    accuracy                           0.91    519956
   macro avg       0.80      0.80      0.78    519956
weighted avg       0.96      0.91      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 4

         0      1      2      3   4   5     -1
 0  191182      1      0      0   0   0  11045
 1       2  83539      3      0   0  48  44944
 2       0      0  70972      0   0   0  11333
 3       0      0      3  60326   0   0    621
 4       0      0      0      0   0   0  45790
 5       0      0      0      0   0  24    123
-1       0      0      0      0   0   0      0

th: 26 hidden: 4 acc:0.869092769388179 recall:1.0 precision:0.4021746767847105 f1:0.573644187765431
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.40      1.00      0.57     45790
           0       1.00      0.95      0.97    202228
           1       1.00      0.65      0.79    128536
           2       1.00      0.86      0.93     82305
           3       1.00      0.99      0.99     60950
           5       0.33      0.16      0.22       147

    accuracy                           0.87    519956
   macro avg       0.79      0.77      0.75    519956
weighted avg       0.95      0.87      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 5

         0       1      2      3      4   5    -1
 0  201817     279      0      0      0   0   132
 1     507  125406     32      1    168   0  2422
 2       0       1  82081      0      0   0   223
 3       0       0      3  60868      0   0    79
 4       9      12      0      0  45624   0   145
 5       0      90      0      0     12   0    45
-1       0       0      0      0      0   0     0

th: 19 hidden: 5 acc:0.9940321873389287 recall:0.30612244897959184 precision:0.014773473407747865 f1:0.028186658315064204
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.31      0.03       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.98      0.99    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.88      0.83    519956
weighted avg       1.00      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 5

         0       1      2      3      4   5    -1
 0  201745     279      0      0      0   0   204
 1     493  124517     32      1    160   0  3333
 2       0       1  82014      0      0   0   290
 3       0       0      3  60850      0   0    97
 4       9      12      0      0  45606   0   163
 5       0      76      0      0     12   0    59
-1       0       0      0      0      0   0     0

th: 20 hidden: 5 acc:0.991970474424759 recall:0.4013605442176871 precision:0.014230583695127834 f1:0.027486606102958305
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.40      0.03       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.97      0.98    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.89      0.83    519956
weighted avg       1.00      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 5

         0       1      2      3      4   5    -1
 0  201653     279      0      0      0   0   296
 1     493  123783     32      1    148   0  4079
 2       0       1  81804      0      0   0   500
 3       0       0      3  60849      0   0    98
 4       9      12      0      0  45582   0   187
 5       0      74      0      0     12   0    61
-1       0       0      0      0      0   0     0

th: 21 hidden: 5 acc:0.9899106847502481 recall:0.41496598639455784 precision:0.011683585520015322 f1:0.022727272727272728
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.41      0.02       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.96      0.98    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.89      0.83    519956
weighted avg       1.00      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 5

         0       1      2      3      4   5    -1
 0  200968     279      0      0      0   0   981
 1     486  122621     32      1    127   0  5269
 2       0       0  81674      0      0   0   631
 3       0       0      3  60849      0   0    98
 4       9      12      0      0  45520   0   249
 5       0      72      0      0     11   0    64
-1       0       0      0      0      0   0     0

th: 22 hidden: 5 acc:0.9859391948549493 recall:0.43537414965986393 precision:0.00877674163466813 f1:0.01720661379217637
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.44      0.02       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.95      0.98    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      1.00     45790

    accuracy                           0.98    519956
   macro avg       0.83      0.89      0.83    519956
weighted avg       1.00      0.98      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 5

         0       1      2      3      4   5    -1
 0  200716     279      0      0      0   0  1233
 1     486  120828     32      1    103   0  7086
 2       0       0  81331      0      0   0   974
 3       0       0      3  60849      0   0    98
 4       9      12      0      0  45411   0   358
 5       0      69      0      0     10   0    68
-1       0       0      0      0      0   0     0

th: 23 hidden: 5 acc:0.9810984006338997 recall:0.46258503401360546 precision:0.006926759702556789 f1:0.01364913689281413
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.46      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.94      0.97    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.98    519956
   macro avg       0.83      0.90      0.83    519956
weighted avg       1.00      0.98      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 5

         0       1      2      3      4   5    -1
 0  200583     279      0      0      0   0  1366
 1     486  118447      3      1     56   0  9543
 2       0       0  80035      0      0   0  2270
 3       0       0      3  60845      0   0   102
 4       9       6      0      0  44615   0  1160
 5       0      67      0      0      8   0    72
-1       0       0      0      0      0   0     0

th: 24 hidden: 5 acc:0.972082253113725 recall:0.4897959183673469 precision:0.004961069386067663 f1:0.009822646657571625
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.49      0.01       147
           0       1.00      0.99      0.99    202228
           1       1.00      0.92      0.96    128536
           2       1.00      0.97      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.97      0.99     45790

    accuracy                           0.97    519956
   macro avg       0.83      0.89      0.82    519956
weighted avg       1.00      0.97      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 5

         0       1      2      3      4   5     -1
 0  199971       0      0      0      0   0   2257
 1      89  114692      3      1     22   0  13729
 2       0       0  79343      0      0   0   2962
 3       0       0      3  60845      0   0    102
 4       3       0      0      0  43753   0   2034
 5       0      38      0      0      8   0    101
-1       0       0      0      0      0   0      0

th: 25 hidden: 5 acc:0.9593619460108163 recall:0.6870748299319728 precision:0.004767524191645032 f1:0.009469341833864617
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.69      0.01       147
           0       1.00      0.99      0.99    202228
           1       1.00      0.89      0.94    128536
           2       1.00      0.96      0.98     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.96      0.98     45790

    accuracy                           0.96    519956
   macro avg       0.83      0.91      0.82    519956
weighted avg       1.00      0.96      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 5

         0       1      2      3      4   5     -1
 0  198623       0      0      0      0   0   3605
 1      76  105448      3      1     12   0  22996
 2       0       0  76548      0      0   0   5757
 3       0       0      3  60834      0   0    113
 4       1       0      0      0  42836   0   2953
 5       0      38      0      0      7   0    102
-1       0       0      0      0      0   0      0

th: 26 hidden: 5 acc:0.9317846125441384 recall:0.6938775510204082 precision:0.0028711366323256205 f1:0.005718610713985367
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.69      0.01       147
           0       1.00      0.98      0.99    202228
           1       1.00      0.82      0.90    128536
           2       1.00      0.93      0.96     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.94      0.97     45790

    accuracy                           0.93    519956
   macro avg       0.83      0.89      0.80    519956
weighted avg       1.00      0.93      0.96    519956

# Média absolute threshold

In [6]:
for i in range(len(f1s)):
    print(f'Média f1 absolute th {ths[i]}: {np.mean(np.array(f1s[i]))}')

Média f1 absolute th 19: 0.5446971134507593
Média f1 absolute th 20: 0.5971586823133654
Média f1 absolute th 21: 0.6579702065078151
Média f1 absolute th 22: 0.6476314374669061
Média f1 absolute th 23: 0.6364647608459854
Média f1 absolute th 24: 0.6748658702775987
Média f1 absolute th 25: 0.6523572602348805
Média f1 absolute th 26: 0.6240019940327336