In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture

In [2]:
def matriz_conf(y_true, y_pred, labels):
    total_labels = labels
    print(total_labels)
    cm = np.zeros((len(total_labels),len(total_labels)), dtype=int)
    for i in range(len(y_true)):
        cm[y_true[i]][y_pred[i]] += 1

    
    cm = pd.DataFrame(cm, columns=total_labels, index=total_labels)

    cm_transp = pd.DataFrame(np.transpose(cm.to_numpy()), columns=total_labels, index=total_labels)

    for c in cm_transp.columns:
        cm_transp[c] = cm_transp[c]/cm_transp[c].sum()

    cm_porcento = pd.DataFrame(np.transpose(cm_transp.to_numpy()), columns=total_labels, index=total_labels)

    return cm, cm_porcento

def acc(cm, hidden_classes):
    cm_transp = pd.DataFrame(np.transpose(cm.dropna().to_numpy()), columns=cm.columns, index=cm.columns)
    acc = 0
    total = 0
    for c in cm_transp.columns:
        if c not in hidden_classes:
            acc += cm_transp[c][c]
        else:
            acc += cm_transp[c][-1]
        total += cm_transp[c].sum()
    return acc/total

In [3]:
filenames = [0,2,3,4,5]

labels_str = ['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

filenames

# pd.set_option('future.no_silent_downcasting', True)

[0, 2, 3, 4, 5]

In [4]:
exp_val = []
y_true_all_exp_val = []
for i in range(len(filenames)):
    exp_val.append(pd.read_csv(f'val_{filenames[i]}_GMM_BIC_1_10_scores_corr.csv'))
    y_true_all_exp_val.append(exp_val[i]['Label'].values.tolist())
    exp_val[i] = exp_val[i].drop(columns=['Label'])

In [10]:
from sklearn.metrics import classification_report
ths = [15, 16, 17, 18, 19, 19.5, 20, 21]
f1s = [[],[],[],[],[],[],[],[]]
for i in range(len(exp_val)):
    index = 0
    for th in ths:
        y_pred = []
        prog= 0
        for j in range(len(exp_val[i])):
            # print(exp[i][j])
            m = np.nanmax(exp_val[i].values[j])
            # print(m)
            if m > th:
                y_pred.append(exp_val[i].values[j].tolist().index(m))
            else:
                y_pred.append(-1)
        # print(y_pred[:10])

        cm, cm_porcento = matriz_conf(y_true_all_exp_val[i], y_pred, list(range(len(labels_str))) + [-1])
        print(f'th = {th} hidden = {filenames[i]}')
        display(cm)
        tp = cm[-1][filenames[i]]
        fp = cm[-1].sum() - tp
        fn = cm.iloc[filenames[i]].sum() - tp
        tn = cm.drop(columns=[-1]).values.sum() - fn

        acc = (tp+tn)/(tp+fp+tn+fn)
        recall = tp/(tp+fn)
        precision = tp/(tp+fp)
        if precision == 0 or recall == 0:
            f1 = 0
        else:
            f1 = 2*precision*recall/(precision+recall)

        f1s[index].append(f1)
        index += 1
        print(f'th: {th} hidden: {filenames[i]} acc:{acc} recall:{recall} precision:{precision} f1:{f1}')

        true_labels = np.array(y_true_all_exp_val[i])
        true_labels[true_labels == filenames[i]] = -1

        print('MULTICLASS DETECTION')
        print(classification_report(true_labels, y_pred))

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 0

     0       1      2      3      4      5     -1
 0   0  130365      0      0      0  42480  29383
 1   0  124956     16      1    130   1400   2033
 2   0       1  82231      0      0      0     73
 3   0       0      3  60943      0      0      4
 4   0      39      0      0  45671     22     58
 5   0       4      0      0      8    134      1
-1   0       0      0      0      0      0      0

th: 15 hidden: 0 acc:0.6634061343652156 recall:0.14529639812488873 precision:0.9312563387423936 f1:0.25137308580716916
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.93      0.15      0.25    202228
           1       0.49      0.97      0.65    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790
           5       0.00      0.91      0.01       147

    accuracy                           0.66    519956
   macro avg       0.74      0.84      0.65    519956
weighted avg       0.85      0.66      0.62    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 0

     0       1      2      3      4      5     -1
 0   0  129982      0      0      0  41028  31218
 1   0  123904     14      1    125   1381   3111
 2   0       1  82184      0      0      0    120
 3   0       0      3  60943      0      0      4
 4   0      39      0      0  45650     22     79
 5   0       4      0      0      8    132      3
-1   0       0      0      0      0      0      0

th: 16 hidden: 0 acc:0.6647274000107701 recall:0.15437031469430543 precision:0.9039525119444042 f1:0.2637067447194029
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.90      0.15      0.26    202228
           1       0.49      0.96      0.65    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790
           5       0.00      0.90      0.01       147

    accuracy                           0.66    519956
   macro avg       0.73      0.84      0.65    519956
weighted avg       0.84      0.66      0.63    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 0

     0       1      2      3      4    5     -1
 0   0  126272      0      0      0    0  75956
 1   0  123412     14      1    122  889   4098
 2   0       1  82119      0      0    0    185
 3   0       0      3  60933      0    0     14
 4   0      33      0      0  45586   12    159
 5   0       4      0      0      8  128      7
-1   0       0      0      0      0    0      0

th: 17 hidden: 0 acc:0.7485652632145797 recall:0.3755958620962478 precision:0.9445031646750146 f1:0.5374619224686622
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.94      0.38      0.54    202228
           1       0.49      0.96      0.65    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790
           5       0.12      0.87      0.22       147

    accuracy                           0.75    519956
   macro avg       0.76      0.87      0.73    519956
weighted avg       0.85      0.75      0.73    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 0

     0       1      2      3      4    5      -1
 0   0   46572      0      0      0    0  155656
 1   0  122381     14      1    118  882    5140
 2   0       1  82038      0      0    0     266
 3   0       0      3  60933      0    0      14
 4   0      33      0      0  45435   11     311
 5   0       4      0      0      8  123      12
-1   0       0      0      0      0    0       0

th: 18 hidden: 0 acc:0.8993857172529983 recall:0.7697054809423027 precision:0.9644173755723393 f1:0.8561300453486677
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.96      0.77      0.86    202228
           1       0.72      0.95      0.82    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.12      0.84      0.21       147

    accuracy                           0.90    519956
   macro avg       0.80      0.92      0.81    519956
weighted avg       0.92      0.90      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 0

     0       1      2      3      4    5      -1
 0   0   30578      0      0      0    0  171650
 1   0  121092     14      1    110  875    6444
 2   0       0  81828      0      0    0     477
 3   0       0      3  60927      0    0      20
 4   0      33      0      0  45388   10     359
 5   0       4      0      0      8  115      20
-1   0       0      0      0      0    0       0

th: 19 hidden: 0 acc:0.927113063413058 recall:0.8487944300492514 precision:0.9590992903838632 f1:0.9005818498523077
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.96      0.85      0.90    202228
           1       0.80      0.94      0.86    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.12      0.78      0.20       147

    accuracy                           0.93    519956
   macro avg       0.81      0.93      0.83    519956
weighted avg       0.93      0.93      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19.5 hidden = 0

     0       1      2      3      4    5      -1
 0   0     467      0      0      0    0  201761
 1   0  119815     14      1    105  871    7730
 2   0       0  81664      0      0    0     641
 3   0       0      3  60912      0    0      35
 4   0      33      0      0  45349    4     404
 5   0       4      0      0      8  113      22
-1   0       0      0      0      0    0       0

th: 19.5 hidden: 0 acc:0.9821157944133735 recall:0.997690725319936 precision:0.9580612840882651 f1:0.9774744986325793
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.96      1.00      0.98    202228
           1       1.00      0.93      0.96    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.11      0.77      0.20       147

    accuracy                           0.98    519956
   macro avg       0.84      0.95      0.85    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 0

     0       1      2      3      4    5      -1
 0   0     419      0      0      0    0  201809
 1   0  119116     14      1    102  867    8436
 2   0       0  81501      0      0    0     804
 3   0       0      3  60896      0    0      51
 4   0      32      0      0  45185    0     573
 5   0       4      0      0      7  103      33
-1   0       0      0      0      0    0       0

th: 20 hidden: 0 acc:0.9801598596804345 recall:0.9979280811757026 precision:0.9532512068623469 f1:0.9750781525557214
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.95      1.00      0.98    202228
           1       1.00      0.93      0.96    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.11      0.70      0.18       147

    accuracy                           0.98    519956
   macro avg       0.84      0.93      0.85    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0

     0       1      2      3      4    5      -1
 0   0     305      0      0      0    0  201923
 1   0  116633     13      1     67  828   10994
 2   0       0  81288      0      0    0    1017
 3   0       0      3  60896      0    0      51
 4   0      30      0      0  44602    0    1158
 5   0       4      0      0      7   73      63
-1   0       0      0      0      0    0       0

th: 21 hidden: 0 acc:0.973867019517036 recall:0.9984918013331487 precision:0.9382777431855989 f1:0.9674487463886506
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.94      1.00      0.97    202228
           1       1.00      0.91      0.95    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.97      0.99     45790
           5       0.08      0.50      0.14       147

    accuracy                           0.97    519956
   macro avg       0.84      0.89      0.84    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 2

         0       1   2      3      4     5     -1
 0  202157      22   0      0      0     2     47
 1     369  126296   0      3    176   575   1117
 2      25   34234   0  30986      0  2204  14856
 3       0       1   0  60946      0     0      3
 4       1      32   0      0  45650    42     65
 5       0       7   0      0      9   120     11
-1       0       0   0      0      0     0      0

th: 15 hidden: 2 acc:0.8678888213618076 recall:0.18049936212866777 precision:0.9227902354183489 f1:0.30193894557131823
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.92      0.18      0.30     82305
           0       1.00      1.00      1.00    202228
           1       0.79      0.98      0.87    128536
           3       0.66      1.00      0.80     60950
           4       1.00      1.00      1.00     45790
           5       0.04      0.82      0.08       147

    accuracy                           0.87    519956
   macro avg       0.73      0.83      0.67    519956
weighted avg       0.89      0.87      0.83    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 2

         0       1   2      3      4     5     -1
 0  202150      22   0      0      0     2     54
 1     365  125985   0      2    176   533   1475
 2      25   30575   0  30986      0  1536  19183
 3       0       1   0  60946      0     0      3
 4       1      29   0      0  45640    38     82
 5       0       7   0      0      9   118     13
-1       0       0   0      0      0     0      0

th: 16 hidden: 2 acc:0.8754721553362208 recall:0.23307210983536844 precision:0.9218164344065353 f1:0.37207001891092467
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.92      0.23      0.37     82305
           0       1.00      1.00      1.00    202228
           1       0.80      0.98      0.88    128536
           3       0.66      1.00      0.80     60950
           4       1.00      1.00      1.00     45790
           5       0.05      0.80      0.10       147

    accuracy                           0.87    519956
   macro avg       0.74      0.84      0.69    519956
weighted avg       0.90      0.87      0.85    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 2

         0       1   2      3      4    5     -1
 0  202140      22   0      0      0    2     64
 1     361  125334   0      0    172  471   2198
 2      25   18262   0  11189      0  794  52035
 3       0       1   0  60945      0    0      4
 4       1      29   0      0  45628    7    125
 5       0       7   0      0      9  114     17
-1       0       0   0      0      0    0      0

th: 17 hidden: 2 acc:0.9371523744316826 recall:0.6322216147257154 precision:0.9557702551292178 f1:0.7610348963056133
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.96      0.63      0.76     82305
           0       1.00      1.00      1.00    202228
           1       0.87      0.98      0.92    128536
           3       0.84      1.00      0.92     60950
           4       1.00      1.00      1.00     45790
           5       0.08      0.78      0.15       147

    accuracy                           0.94    519956
   macro avg       0.79      0.90      0.79    519956
weighted avg       0.94      0.94      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 2

         0       1   2      3      4    5     -1
 0  202066      22   0      0      0    2    138
 1     360  123756   0      0    162  459   3799
 2      24    9075   0      0      0  259  72947
 3       0       1   0  60933      0    0     16
 4       1      21   0      0  45607    3    158
 5       0       7   0      0      9  109     22
-1       0       0   0      0      0    0      0

th: 18 hidden: 2 acc:0.9740535737639339 recall:0.8863009537695158 precision:0.9463803840166061 f1:0.9153558992376949
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.95      0.89      0.92     82305
           0       1.00      1.00      1.00    202228
           1       0.93      0.96      0.95    128536
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790
           5       0.13      0.74      0.22       147

    accuracy                           0.97    519956
   macro avg       0.83      0.93      0.85    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 2

         0       1   2      3      4    5     -1
 0  201688      21   0      0      0    0    519
 1     351  122191   0      0    150  390   5454
 2       0    5582   0      0      0    0  76723
 3       0       0   0  60930      0    0     20
 4       1      12   0      0  45566    2    209
 5       0       7   0      0      8  106     26
-1       0       0   0      0      0    0      0

th: 19 hidden: 2 acc:0.9772865396302765 recall:0.9321790899702327 precision:0.9249195308073441 f1:0.9285351212663988
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.92      0.93      0.93     82305
           0       1.00      1.00      1.00    202228
           1       0.96      0.95      0.95    128536
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790
           5       0.21      0.72      0.33       147

    accuracy                           0.98    519956
   macro avg       0.85      0.93      0.87    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19.5 hidden = 2

         0       1   2      3      4    5     -1
 0  201564      20   0      0      0    0    644
 1     329  120801   0      0    144  367   6895
 2       0    4395   0      0      0    0  77910
 3       0       0   0  60928      0    0     22
 4       1      10   0      0  45549    0    230
 5       0       7   0      0      7   97     36
-1       0       0   0      0      0    0      0

th: 19.5 hidden: 2 acc:0.9764941648908754 recall:0.946601057043922 precision:0.908709192064103 f1:0.9272681829542614
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.91      0.95      0.93     82305
           0       1.00      1.00      1.00    202228
           1       0.96      0.94      0.95    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      1.00     45790
           5       0.21      0.66      0.32       147

    accuracy                           0.97    519956
   macro avg       0.85      0.92      0.86    519956
weighted avg       0.98      0.97      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 2

         0       1   2      3      4    5     -1
 0  201333      20   0      0      0    0    875
 1     324  119261   0      0    137  356   8458
 2       0    3137   0      0      0    0  79168
 3       0       0   0  60915      0    0     35
 4       1       8   0      0  45502    0    279
 5       0       6   0      0      7   92     42
-1       0       0   0      0      0    0      0

th: 20 hidden: 2 acc:0.9753325281369962 recall:0.9618856691574024 precision:0.8909596317678967 f1:0.9250651429639757
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.89      0.96      0.93     82305
           0       1.00      1.00      1.00    202228
           1       0.97      0.93      0.95    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      1.00     45790
           5       0.21      0.63      0.31       147

    accuracy                           0.97    519956
   macro avg       0.84      0.92      0.86    519956
weighted avg       0.98      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2

         0       1   2      3      4   5     -1
 0  201284      20   0      0      0   0    924
 1     319  114855   0      0    122  91  13149
 2       0     255   0      0      0   0  82050
 3       0       0   0  60914      0   0     36
 4       1       8   0      0  45390   0    391
 5       0       5   0      0      6  63     73
-1       0       0   0      0      0   0      0

th: 21 hidden: 2 acc:0.971482202340198 recall:0.9969017678148351 precision:0.8491766970597063 f1:0.9171286774568542
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.85      1.00      0.92     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.89      0.94    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.41      0.43      0.42       147

    accuracy                           0.97    519956
   macro avg       0.88      0.88      0.88    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 3

         0       1      2   3      4    5     -1
 0  202064      76      0   0      0    0     88
 1     349  126605     18   0    120  120   1324
 2       0       1  82261   0      0    0     43
 3       0    2082    429   0      0    0  58439
 4       2      72      0   0  45638    3     75
 5       0      10      0   0      8  107     22
-1       0       0      0   0      0    0      0

th: 15 hidden: 3 acc:0.992185877266538 recall:0.9588022969647252 precision:0.9741294527512461 f1:0.9664051066222373
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.96      0.97     60950
           0       1.00      1.00      1.00    202228
           1       0.98      0.98      0.98    128536
           2       0.99      1.00      1.00     82305
           4       1.00      1.00      1.00     45790
           5       0.47      0.73      0.57       147

    accuracy                           0.99    519956
   macro avg       0.90      0.94      0.92    519956
weighted avg       0.99      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 3

         0       1      2   3      4    5     -1
 0  202061      66      0   0      0    0    101
 1     345  126321     16   0     99  120   1635
 2       0       1  82230   0      0    0     74
 3       0      10    429   0      0    0  60511
 4       2      23      0   0  45606    1    158
 5       0      10      0   0      8  106     23
-1       0       0      0   0      0    0      0

th: 16 hidden: 3 acc:0.9953265276292609 recall:0.9927973748974569 precision:0.9681450193593805 f1:0.9803162362699673
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.99      0.98     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.98      0.99    128536
           2       0.99      1.00      1.00     82305
           4       1.00      1.00      1.00     45790
           5       0.47      0.72      0.57       147

    accuracy                           0.99    519956
   macro avg       0.90      0.95      0.92    519956
weighted avg       0.99      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 3

         0       1      2   3      4    5     -1
 0  202045      66      0   0      0    0    117
 1     341  125075     16   0     99  117   2888
 2       0       1  82199   0      0    0    105
 3       0       0    356   0      0    0  60594
 4       2      22      0   0  45589    1    176
 5       0       9      0   0      8  106     24
-1       0       0      0   0      0    0      0

th: 17 hidden: 3 acc:0.9929494034110579 recall:0.9941591468416735 precision:0.9482035553329995 f1:0.9706377048392523
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.95      0.99      0.97     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.97      0.99    128536
           2       1.00      1.00      1.00     82305
           4       1.00      1.00      1.00     45790
           5       0.47      0.72      0.57       147

    accuracy                           0.99    519956
   macro avg       0.90      0.95      0.92    519956
weighted avg       0.99      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 3

         0       1      2   3      4    5     -1
 0  202010      65      0   0      0    0    153
 1     331  124371     16   0     98  109   3611
 2       0       1  82159   0      0    0    145
 3       0       0    356   0      0    0  60594
 4       2      18      0   0  45559    1    210
 5       0       7      0   0      7  103     30
-1       0       0      0   0      0    0      0

th: 18 hidden: 3 acc:0.9913358053373748 recall:0.9941591468416735 precision:0.9359158519067698 f1:0.9641587041442243
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.94      0.99      0.96     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.97      0.98    128536
           2       1.00      1.00      1.00     82305
           4       1.00      0.99      1.00     45790
           5       0.48      0.70      0.57       147

    accuracy                           0.99    519956
   macro avg       0.90      0.94      0.92    519956
weighted avg       0.99      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 3

         0       1      2   3      4    5     -1
 0  201975      60      0   0      0    0    193
 1     316  123769     14   0     97   86   4254
 2       0       1  82049   0      0    0    255
 3       0       0    156   0      0    0  60794
 4       1      10      0   0  45467    0    312
 5       0       7      0   0      7  103     30
-1       0       0      0   0      0    0      0

th: 19 hidden: 3 acc:0.9899991537745502 recall:0.9974405250205086 precision:0.9233877092256751 f1:0.9589866548884753
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.92      1.00      0.96     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.96      0.98    128536
           2       1.00      1.00      1.00     82305
           4       1.00      0.99      1.00     45790
           5       0.54      0.70      0.61       147

    accuracy                           0.99    519956
   macro avg       0.91      0.94      0.92    519956
weighted avg       0.99      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19.5 hidden = 3

         0       1      2   3      4    5     -1
 0  201921       0      0   0      0    0    307
 1     286  122711     14   0     97   83   5345
 2       0       1  81975   0      0    0    329
 3       0       0    156   0      0    0  60794
 4       1      10      0   0  45395    0    384
 5       0       6      0   0      6  100     35
-1       0       0      0   0      0    0      0

th: 19.5 hidden: 3 acc:0.9873912407972982 recall:0.9974405250205086 precision:0.9047534006012442 f1:0.9488388063428642
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.90      1.00      0.95     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.95      0.98    128536
           2       1.00      1.00      1.00     82305
           4       1.00      0.99      0.99     45790
           5       0.55      0.68      0.61       147

    accuracy                           0.99    519956
   macro avg       0.91      0.94      0.92    519956
weighted avg       0.99      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 3

         0       1      2   3      4   5     -1
 0  201795       0      0   0      0   0    433
 1     277  120280     14   0     96  79   7790
 2       0       1  81808   0      0   0    496
 3       0       0    156   0      0   0  60794
 4       1       9      0   0  44957   0    823
 5       0       5      0   0      6  98     38
-1       0       0      0   0      0   0      0

th: 20 hidden: 3 acc:0.9812753386825039 recall:0.9974405250205086 precision:0.8638701793275926 f1:0.9258627516676312
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.86      1.00      0.93     60950
           0       1.00      1.00      1.00    202228
           1       1.00      0.94      0.97    128536
           2       1.00      0.99      1.00     82305
           4       1.00      0.98      0.99     45790
           5       0.55      0.67      0.60       147

    accuracy                           0.98    519956
   macro avg       0.90      0.93      0.91    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 3

         0       1      2   3      4   5     -1
 0  201148       0      0   0      0   0   1080
 1     263  116962     14   0     94  62  11141
 2       0       1  81489   0      0   0    815
 3       0       0     75   0      0   0  60875
 4       1       6      0   0  44313   0   1470
 5       0       4      0   0      6  88     49
-1       0       0      0   0      0   0      0

th: 21 hidden: 3 acc:0.9718630037926286 recall:0.9987694831829368 precision:0.807039639400769 f1:0.8927262061885906
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.81      1.00      0.89     60950
           0       1.00      0.99      1.00    202228
           1       1.00      0.91      0.95    128536
           2       1.00      0.99      0.99     82305
           4       1.00      0.97      0.98     45790
           5       0.59      0.60      0.59       147

    accuracy                           0.97    519956
   macro avg       0.90      0.91      0.90    519956
weighted avg       0.98      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 4

         0       1      2      3   4      5    -1
 0  202056      93      0      0   0      0    79
 1     107  126414     14      2   0    181  1818
 2       0       1  82192      0   0      0   112
 3       0       0      3  60943   0      0     4
 4       0   24374      0      0   0  20572   844
 5       0      12      0      0   0    121    14
-1       0       0      0      0   0      0     0

th: 15 hidden: 4 acc:0.9096596635099893 recall:0.018431972046298317 precision:0.2939742250087078 f1:0.03468897063356692
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.29      0.02      0.03     45790
           0       1.00      1.00      1.00    202228
           1       0.84      0.98      0.90    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.82      0.01       147

    accuracy                           0.91    519956
   macro avg       0.69      0.80      0.66    519956
weighted avg       0.90      0.91      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 4

         0       1      2      3   4      5    -1
 0  202050      93      0      0   0      0    85
 1     102  124310     14      0   0    174  3936
 2       0       1  82167      0   0      0   137
 3       0       0      3  60940   0      0     7
 4       0   24359      0      0   0  20572   859
 5       0      12      0      0   0    119    16
-1       0       0      0      0   0      0     0

th: 16 hidden: 4 acc:0.9055458538799437 recall:0.01875955448787945 precision:0.17043650793650794 f1:0.033798937635254774
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.17      0.02      0.03     45790
           0       1.00      1.00      1.00    202228
           1       0.84      0.97      0.90    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.81      0.01       147

    accuracy                           0.90    519956
   macro avg       0.67      0.80      0.66    519956
weighted avg       0.89      0.90      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 4

         0       1      2      3   4      5    -1
 0  202020      92      0      0   0      0   116
 1      99  123995     14      0   0    161  4267
 2       0       1  82150      0   0      0   154
 3       0       0      3  60899   0      0    48
 4       0   24359      0      0   0  20572   859
 5       0      12      0      0   0    118    17
-1       0       0      0      0   0      0     0

th: 17 hidden: 4 acc:0.904736169983614 recall:0.01875955448787945 precision:0.15729719831532687 f1:0.033521297145421555
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.16      0.02      0.03     45790
           0       1.00      1.00      1.00    202228
           1       0.84      0.96      0.90    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.80      0.01       147

    accuracy                           0.90    519956
   macro avg       0.67      0.80      0.66    519956
weighted avg       0.88      0.90      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 4

         0       1      2      3   4    5     -1
 0  201661      92      0      0   0    0    475
 1      93  123576     14      0   0  123   4730
 2       0       0  82097      0   0    0    208
 3       0       0      3  60882   0    0     65
 4       0   24359      0      0   0  327  21104
 5       0       6      0      0   0   98     43
-1       0       0      0      0   0    0      0

th: 18 hidden: 4 acc:0.9419046996284302 recall:0.46088665647521293 precision:0.7926384976525822 f1:0.5828626665746047
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.79      0.46      0.58     45790
           0       1.00      1.00      1.00    202228
           1       0.83      0.96      0.89    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.18      0.67      0.28       147

    accuracy                           0.94    519956
   macro avg       0.80      0.85      0.79    519956
weighted avg       0.94      0.94      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 4

         0       1      2      3   4   5     -1
 0  201591      76      0      0   0   0    561
 1      82  121228     14      0   0  53   7159
 2       0       0  82038      0   0   0    267
 3       0       0      3  60881   0   0     66
 4       0   24356      0      0   0   0  21434
 5       0       2      0      0   0  79     66
-1       0       0      0      0   0   0      0

th: 19 hidden: 4 acc:0.937542792082407 recall:0.4680934701899978 precision:0.7252732379115487 f1:0.5689712382039473
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.73      0.47      0.57     45790
           0       1.00      1.00      1.00    202228
           1       0.83      0.94      0.88    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.60      0.54      0.57       147

    accuracy                           0.94    519956
   macro avg       0.86      0.82      0.84    519956
weighted avg       0.93      0.94      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19.5 hidden = 4

         0       1      2      3   4   5     -1
 0  201449      60      0      0   0   0    719
 1      77  120619     14      0   0  53   7773
 2       0       0  82007      0   0   0    298
 3       0       0      3  60881   0   0     66
 4       0   24356      0      0   0   0  21434
 5       0       2      0      0   0  79     66
-1       0       0      0      0   0   0      0

th: 19.5 hidden: 4 acc:0.9359984306364385 recall:0.4680934701899978 precision:0.7060877585979708 f1:0.5629711343997058
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.71      0.47      0.56     45790
           0       1.00      1.00      1.00    202228
           1       0.83      0.94      0.88    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.60      0.54      0.57       147

    accuracy                           0.94    519956
   macro avg       0.86      0.82      0.83    519956
weighted avg       0.93      0.94      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 4

         0       1      2      3   4   5     -1
 0  201231      47      0      0   0   0    950
 1      71  120241     14      0   0  52   8158
 2       0       0  81922      0   0   0    383
 3       0       0      3  60881   0   0     66
 4       0   24355      0      0   0   0  21435
 5       0       2      0      0   0  78     67
-1       0       0      0      0   0   0      0

th: 20 hidden: 4 acc:0.9346502396356615 recall:0.46811530901943654 precision:0.6901381242152034 f1:0.5578472068602064
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.69      0.47      0.56     45790
           0       1.00      1.00      1.00    202228
           1       0.83      0.94      0.88    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.60      0.53      0.56       147

    accuracy                           0.93    519956
   macro avg       0.85      0.82      0.83    519956
weighted avg       0.93      0.93      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 4

         0       1      2      3   4   5     -1
 0  200861      29      0      0   0   0   1338
 1      52  118601     13      0   0  51   9819
 2       0       0  81634      0   0   0    671
 3       0       0      3  60881   0   0     66
 4       0   24355      0      0   0   0  21435
 5       0       2      0      0   0  76     69
-1       0       0      0      0   0   0      0

th: 21 hidden: 4 acc:0.9301517820738678 recall:0.46811530901943654 precision:0.641804898496916 f1:0.5413699045309895
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.64      0.47      0.54     45790
           0       1.00      0.99      1.00    202228
           1       0.83      0.92      0.87    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.60      0.52      0.55       147

    accuracy                           0.93    519956
   macro avg       0.84      0.82      0.83    519956
weighted avg       0.93      0.93      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 15 hidden = 5

         0       1      2      3      4   5   -1
 0  202093      51      0      0      0   0   84
 1     163  127617     16      1    130   0  609
 2       0       1  82234      0      0   0   70
 3       0       0      3  60946      0   0    1
 4       1      50      0      0  45696   0   43
 5       0     126      0      0     15   0    6
-1       0       0      0      0      0   0    0

th: 15 hidden: 5 acc:0.9981767688035141 recall:0.04081632653061224 precision:0.007380073800738007 f1:0.012499999999999999
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.04      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.99      1.00    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           1.00    519956
   macro avg       0.83      0.84      0.83    519956
weighted avg       1.00      1.00      1.00    519956

[0, 1, 2, 3, 4, 5, -1]
th = 16 hidden = 5

         0       1      2      3      4   5   -1
 0  202090      49      0      0      0   0   89
 1     161  127272     16      1    124   0  962
 2       0       1  82204      0      0   0  100
 3       0       0      3  60946      0   0    1
 4       1      48      0      0  45680   0   61
 5       0     124      0      0     14   0    9
-1       0       0      0      0      0   0    0

th: 16 hidden: 5 acc:0.9974017032210418 recall:0.061224489795918366 precision:0.007364975450081833 f1:0.01314828341855369
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.06      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.99      0.99    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           1.00    519956
   macro avg       0.83      0.84      0.83    519956
weighted avg       1.00      1.00      1.00    519956

[0, 1, 2, 3, 4, 5, -1]
th = 17 hidden = 5

         0       1      2      3      4   5    -1
 0  202088      47      0      0      0   0    93
 1     158  126984     16      0    116   0  1262
 2       0       1  82147      0      0   0   157
 3       0       0      3  60938      0   0     9
 4       1      47      0      0  45659   0    83
 5       0     123      0      0     14   0    10
-1       0       0      0      0      0   0     0

th: 17 hidden: 5 acc:0.9966516397541331 recall:0.06802721088435375 precision:0.006195786864931847 f1:0.011357183418512209
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.07      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.99      0.99    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           1.00    519956
   macro avg       0.83      0.84      0.83    519956
weighted avg       1.00      1.00      1.00    519956

[0, 1, 2, 3, 4, 5, -1]
th = 18 hidden = 5

         0       1      2      3      4   5    -1
 0  202077      42      0      0      0   0   109
 1     151  126544     16      0    106   0  1719
 2       0       1  82115      0      0   0   189
 3       0       0      3  60920      0   0    27
 4       1      47      0      0  45585   0   157
 5       0     115      0      0     11   0    21
-1       0       0      0      0      0   0     0

th: 18 hidden: 5 acc:0.9955246213141112 recall:0.14285714285714285 precision:0.009450945094509451 f1:0.017728999577880964
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.14      0.02       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.98      0.99    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.85      0.83    519956
weighted avg       1.00      0.99      1.00    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19 hidden = 5

         0       1      2      3      4   5    -1
 0  202005      32      0      0      0   0   191
 1     144  125593     15      0     90   0  2694
 2       0       1  82072      0      0   0   232
 3       0       0      3  60876      0   0    71
 4       1      47      0      0  45397   0   345
 5       0     114      0      0     10   0    23
-1       0       0      0      0      0   0     0

th: 19 hidden: 5 acc:0.9929667125679865 recall:0.1564625850340136 precision:0.0064679415073115865 f1:0.012422360248447204
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.16      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.98      0.99    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.85      0.83    519956
weighted avg       1.00      0.99      1.00    519956

[0, 1, 2, 3, 4, 5, -1]
th = 19.5 hidden = 5

         0       1      2      3      4   5    -1
 0  201911      25      0      0      0   0   292
 1     141  125021     15      0     88   0  3271
 2       0       1  82046      0      0   0   258
 3       0       0      3  60876      0   0    71
 4       1      47      0      0  45374   0   368
 5       0     113      0      0     10   0    24
-1       0       0      0      0      0   0     0

th: 19.5 hidden: 5 acc:0.9915704405757411 recall:0.16326530612244897 precision:0.0056022408963585435 f1:0.010832769126607989
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.16      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.97      0.99    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.85      0.83    519956
weighted avg       1.00      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 5

         0       1      2      3      4   5    -1
 0  201737      22      0      0      0   0   469
 1     132  124477     15      0     84   0  3828
 2       0       1  81920      0      0   0   384
 3       0       0      3  60876      0   0    71
 4       1      47      0      0  45349   0   393
 5       0     112      0      0      9   0    26
-1       0       0      0      0      0   0     0

th: 20 hidden: 5 acc:0.9898722199570733 recall:0.17687074829931973 precision:0.0050280409978727516 f1:0.009778112072207596
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.18      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.97      0.98    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.85      0.83    519956
weighted avg       1.00      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 5

         0       1      2      3      4   5    -1
 0  201685      12      0      0      0   0   531
 1     126  121436     14      0     61   0  6899
 2       0       1  81642      0      0   0   662
 3       0       0      3  60876      0   0    71
 4       1      47      0      0  44966   0   776
 5       0      80      0      0      7   0    60
-1       0       0      0      0      0   0     0

th: 21 hidden: 5 acc:0.9826408388402096 recall:0.40816326530612246 precision:0.00666740748972108 f1:0.013120489831620381
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.41      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.94      0.97    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790

    accuracy                           0.98    519956
   macro avg       0.83      0.89      0.83    519956
weighted avg       1.00      0.98      0.99    519956

# Média absolute threshold

In [11]:
for i in range(len(f1s)):
    print(f'Média f1 absolute th {ths[i]}: {np.mean(np.array(f1s[i]))}')

Média f1 absolute th 15: 0.3133812217268583
Média f1 absolute th 16: 0.3326080441908207
Média f1 absolute th 17: 0.4628026008354923
Média f1 absolute th 18: 0.6672472629766146
Média f1 absolute th 19: 0.6738994448919152
Média f1 absolute th 19.5: 0.6854770782912036
Média f1 absolute th 20: 0.6787262732239485
Média f1 absolute th 21: 0.6663588048793411