In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture

In [2]:
def matriz_conf(y_true, y_pred, labels):
    total_labels = labels
    print(total_labels)
    cm = np.zeros((len(total_labels),len(total_labels)), dtype=int)
    for i in range(len(y_true)):
        cm[y_true[i]][y_pred[i]] += 1

    
    cm = pd.DataFrame(cm, columns=total_labels, index=total_labels)

    cm_transp = pd.DataFrame(np.transpose(cm.to_numpy()), columns=total_labels, index=total_labels)

    for c in cm_transp.columns:
        cm_transp[c] = cm_transp[c]/cm_transp[c].sum()

    cm_porcento = pd.DataFrame(np.transpose(cm_transp.to_numpy()), columns=total_labels, index=total_labels)

    return cm, cm_porcento

def acc(cm, hidden_classes):
    cm_transp = pd.DataFrame(np.transpose(cm.dropna().to_numpy()), columns=cm.columns, index=cm.columns)
    acc = 0
    total = 0
    for c in cm_transp.columns:
        if c not in hidden_classes:
            acc += cm_transp[c][c]
        else:
            acc += cm_transp[c][-1]
        total += cm_transp[c].sum()
    return acc/total

In [3]:
filenames = [0,2,3,4,5]

labels_str = ['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

filenames

# pd.set_option('future.no_silent_downcasting', True)

[0, 2, 3, 4, 5]

In [4]:
exp_val = []
y_true_all_exp_val = []
for i in range(len(filenames)):
    exp_val.append(pd.read_csv(f'val_{filenames[i]}_GMM_BIC_1_10_scores_corr.csv'))
    y_true_all_exp_val.append(exp_val[i]['Label'].values.tolist())
    exp_val[i] = exp_val[i].drop(columns=['Label'])

In [7]:
from sklearn.metrics import classification_report
ths = [20, 21, 22, 23, 24, 25, 26, 27]
f1s = [[],[],[],[],[],[],[],[]]
for i in range(len(exp_val)):
    index = 0
    for th in ths:
        y_pred = []
        prog= 0
        for j in range(len(exp_val[i])):
            # print(exp[i][j])
            m = np.nanmax(exp_val[i].values[j])
            # print(m)
            if m > th:
                y_pred.append(exp_val[i].values[j].tolist().index(m))
            else:
                y_pred.append(-1)
        # print(y_pred[:10])

        cm, cm_porcento = matriz_conf(y_true_all_exp_val[i], y_pred, list(range(len(labels_str))) + [-1])
        print(f'th = {th} hidden = {filenames[i]}')
        display(cm)
        tp = cm[-1][filenames[i]]
        fp = cm[-1].sum() - tp
        fn = cm.iloc[filenames[i]].sum() - tp
        tn = cm.drop(columns=[-1]).values.sum() - fn

        acc = (tp+tn)/(tp+fp+tn+fn)
        recall = tp/(tp+fn)
        precision = tp/(tp+fp)
        if precision == 0 or recall == 0:
            f1 = 0
        else:
            f1 = 2*precision*recall/(precision+recall)

        f1s[index].append(f1)
        index += 1
        print(f'th: {th} hidden: {filenames[i]} acc:{acc} recall:{recall} precision:{precision} f1:{f1}')

        true_labels = np.array(y_true_all_exp_val[i])
        true_labels[true_labels == filenames[i]] = -1

        print('MULTICLASS DETECTION')
        print(classification_report(true_labels, y_pred))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 0

     0       1      2      3      4    5      -1
 0   0    2272      0      0      0    0  199956
 1   0  123518     13      1    248  145    4611
 2   0       1  81919      0      0    0     385
 3   0       0      3  60934      0    0      13
 4   0       8      0      0  45645   41      96
 5   0      14      0      0      8  102      23
-1   0       0      0      0      0    0       0

th: 20 hidden: 0 acc:0.9857680265253214 recall:0.9887651561603734 precision:0.9749956115542899 f1:0.9818321090466277
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.99      0.98    202228
           1       0.98      0.96      0.97    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       0.99      1.00      1.00     45790
           5       0.35      0.69      0.47       147

    accuracy                           0.98    519956
   macro avg       0.88      0.94      0.90    519956
weighted avg       0.99      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0

     0       1      2      3      4    5      -1
 0   0    2259      0      0      0    0  199969
 1   0  122335     13      1    195  124    5868
 2   0       0  81827      0      0    0     478
 3   0       0      3  60934      0    0      13
 4   0       8      0      0  45586    0     196
 5   0      14      0      0      8   88      37
-1   0       0      0      0      0    0       0

th: 21 hidden: 0 acc:0.9829774057804891 recall:0.9888294400379769 precision:0.968086908951835 f1:0.9783482432257228
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.99      0.98    202228
           1       0.98      0.95      0.97    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790
           5       0.42      0.60      0.49       147

    accuracy                           0.98    519956
   macro avg       0.89      0.92      0.90    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 0

     0       1      2      3      4   5      -1
 0   0    2200      0      0      0   0  200028
 1   0  120369     13      0    145  96    7913
 2   0       0  81527      0      0   0     778
 3   0       0      3  60913      0   0      34
 4   0       2      0      0  45469   0     319
 5   0      13      0      0      7  76      51
-1   0       0      0      0      0   0       0

th: 22 hidden: 0 acc:0.9782770080545277 recall:0.9891211899440235 precision:0.9565088488592838 f1:0.9725416979659708
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.96      0.99      0.97    202228
           1       0.98      0.94      0.96    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.44      0.52      0.48       147

    accuracy                           0.98    519956
   macro avg       0.90      0.90      0.90    519956
weighted avg       0.98      0.98      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 0

     0       1      2      3      4   5      -1
 0   0       4      0      0      0   0  202224
 1   0  116293     13      0    131  48   12051
 2   0       0  80768      0      0   0    1537
 3   0       0      3  60912      0   0      35
 4   0       2      0      0  45278   0     510
 5   0       5      0      0      5  50      87
-1   0       0      0      0      0   0       0

th: 23 hidden: 0 acc:0.9726438390940771 recall:0.9999802203453527 precision:0.9343017131452015 f1:0.9660259104979555
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.93      1.00      0.97    202228
           1       1.00      0.90      0.95    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.51      0.34      0.41       147

    accuracy                           0.97    519956
   macro avg       0.91      0.87      0.88    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 0

     0       1      2      3      4   5      -1
 0   0       4      0      0      0   0  202224
 1   0  113407     13      0     56  48   15012
 2   0       0  80127      0      0   0    2178
 3   0       0      3  60912      0   0      35
 4   0       2      0      0  43777   0    2011
 5   0       4      0      0      5  40      98
-1   0       0      0      0      0   0       0

th: 24 hidden: 0 acc:0.962808391479279 recall:0.9999802203453527 precision:0.9127361684073696 f1:0.9543684784301509
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.91      1.00      0.95    202228
           1       1.00      0.88      0.94    128536
           2       1.00      0.97      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.96      0.98     45790
           5       0.45      0.27      0.34       147

    accuracy                           0.96    519956
   macro avg       0.89      0.85      0.87    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 0

     0       1      2      3      4   5      -1
 0   0       4      0      0      0   0  202224
 1   0  110148      3      0     51  48   18286
 2   0       0  77401      0      0   0    4904
 3   0       0      3  60911      0   0      36
 4   0       2      0      0  43379   0    2409
 5   0       4      0      0      5  24     114
-1   0       0      0      0      0   0       0

th: 25 hidden: 0 acc:0.9504708090684596 recall:0.9999802203453527 precision:0.8870524141016699 f1:0.9401372846646102
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.89      1.00      0.94    202228
           1       1.00      0.86      0.92    128536
           2       1.00      0.94      0.97     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.95      0.97     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.95    519956
   macro avg       0.87      0.82      0.84    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 0

     0      1      2      3      4   5      -1
 0   0      3      0      0      0   0  202225
 1   0  98906      3      0     25  48   29554
 2   0      0  75286      0      0   0    7019
 3   0      0      3  60905      0   0      42
 4   0      0      0      0  39361   0    6429
 5   0      0      0      0      2  24     121
-1   0      0      0      0      0   0       0

th: 26 hidden: 0 acc:0.9169775904114964 recall:0.9999851652590146 precision:0.8240963364440279 f1:0.9035606253546551
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.82      1.00      0.90    202228
           1       1.00      0.77      0.87    128536
           2       1.00      0.91      0.96     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.86      0.92     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.92    519956
   macro avg       0.86      0.78      0.81    519956
weighted avg       0.93      0.92      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 27 hidden = 0

     0      1      2      3      4   5      -1
 0   0      3      0      0      0   0  202225
 1   0  91235      3      0      0  48   37250
 2   0      0  73688      0      0   0    8617
 3   0      0      3  60887      0   0      60
 4   0      0      0      0  32605   0   13185
 5   0      0      0      0      0  24     123
-1   0      0      0      0      0   0       0

th: 27 hidden: 0 acc:0.8860711290955389 recall:0.9999851652590146 precision:0.77344526887478 f1:0.8722459929952899
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.77      1.00      0.87    202228
           1       1.00      0.71      0.83    128536
           2       1.00      0.90      0.94     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.71      0.83     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.89    519956
   macro avg       0.85      0.75      0.78    519956
weighted avg       0.91      0.89      0.88    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 2

         0       1   2      3      4     5     -1
 0  201870      41   0      0      0     3    314
 1     527  121036   0      1    140  1767   5065
 2       0   16413   0      0     48     0  65844
 3       0       0   0  60907      0     0     43
 4       1      39   0      0  45229   331    190
 5       0       1   0      0      6   128     12
-1       0       0   0      0      0     0      0

th: 20 hidden: 2 acc:0.9575252521367192 recall:0.8 precision:0.9213074382940617 f1:0.8563792083135531
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.92      0.80      0.86     82305
           0       1.00      1.00      1.00    202228
           1       0.88      0.94      0.91    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.06      0.87      0.11       147

    accuracy                           0.95    519956
   macro avg       0.81      0.93      0.81    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2

         0       1   2      3      4     5     -1
 0  201829      41   0      0      0     3    355
 1     513  118632   0      1    124  1693   7573
 2       0    9875   0      0     43     0  72387
 3       0       0   0  60907      0     0     43
 4       1      39   0      0  45217   331    202
 5       0       0   0      0      6   123     18
-1       0       0   0      0      0     0      0

th: 21 hidden: 2 acc:0.9651720530198709 recall:0.8794969928922909 precision:0.8983469433344089 f1:0.8888220379045081
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.90      0.88      0.89     82305
           0       1.00      1.00      1.00    202228
           1       0.92      0.92      0.92    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.06      0.84      0.11       147

    accuracy                           0.96    519956
   macro avg       0.81      0.94      0.82    519956
weighted avg       0.96      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 2

         0       1   2      3      4     5     -1
 0  201726      37   0      0      0     0    465
 1     512  114681   0      1    112  1485  11745
 2       0    3959   0      0     36     0  78310
 3       0       0   0  60907      0     0     43
 4       1       3   0      0  45171   325    290
 5       0       0   0      0      5   119     23
-1       0       0   0      0      0     0      0

th: 22 hidden: 2 acc:0.968149228011601 recall:0.9514610290990827 precision:0.861723667414939 f1:0.9043717266905723
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.86      0.95      0.90     82305
           0       1.00      1.00      1.00    202228
           1       0.97      0.89      0.93    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.06      0.81      0.11       147

    accuracy                           0.96    519956
   macro avg       0.81      0.94      0.82    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 2

         0       1   2      3      4     5     -1
 0  201688      10   0      0      0     0    530
 1     479  110628   0      1     83  1333  16012
 2       0     112   0      0     28     0  82165
 3       0       0   0  60907      0     0     43
 4       1       0   0      0  44964   259    566
 5       0       0   0      0      5   105     37
-1       0       0   0      0      0     0      0

th: 23 hidden: 2 acc:0.9666741031933471 recall:0.9982990097806937 precision:0.8270006944933721 f1:0.9046119631395259
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.83      1.00      0.90     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.86      0.92    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790
           5       0.06      0.71      0.11       147

    accuracy                           0.96    519956
   macro avg       0.81      0.93      0.82    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 2

         0       1   2      3      4   5     -1
 0  201307       0   0      0      0   0    921
 1     473  106624   0      1      9  52  21377
 2       0      50   0      0     21   0  82234
 3       0       0   0  60902      0   0     48
 4       1       0   0      0  42009   0   3780
 5       0       0   0      0      5  46     96
-1       0       0   0      0      0   0      0

th: 24 hidden: 2 acc:0.9494322596527398 recall:0.999137354960209 precision:0.7582245334513535 f1:0.8621678435319587
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.76      1.00      0.86     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.83      0.91    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.92      0.96     45790
           5       0.47      0.31      0.38       147

    accuracy                           0.95    519956
   macro avg       0.87      0.84      0.85    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 2

         0       1   2      3      4   5     -1
 0  197915       0   0      0      0   0   4313
 1      72  100316   0      1      4  51  28092
 2       0      24   0      0      0   0  82281
 3       0       0   0  60891      0   0     59
 4       1       0   0      0  40396   0   5393
 5       0       0   0      0      4  46     97
-1       0       0   0      0      0   0      0

th: 25 hidden: 2 acc:0.9269592042403588 recall:0.9997084016766904 precision:0.6843348442633177 f1:0.8124913597314112
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.68      1.00      0.81     82305
           0       1.00      0.98      0.99    202228
           1       1.00      0.78      0.88    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.88      0.94     45790
           5       0.47      0.31      0.38       147

    accuracy                           0.93    519956
   macro avg       0.86      0.83      0.83    519956
weighted avg       0.95      0.93      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 2

         0      1   2      3      4   5     -1
 0  197435      0   0      0      0   0   4793
 1       5  91188   0      1      0  48  37294
 2       0     15   0      0      0   0  82290
 3       0      0   0  60879      0   0     71
 4       0      0   0      0  33607   0  12183
 5       0      0   0      0      1  24    122
-1       0      0   0      0      0   0      0

th: 26 hidden: 2 acc:0.8952257498711429 recall:0.9998177510479315 precision:0.6017418265047202 f1:0.7513078728008107
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.60      1.00      0.75     82305
           0       1.00      0.98      0.99    202228
           1       1.00      0.71      0.83    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.73      0.85     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.90    519956
   macro avg       0.82      0.76      0.77    519956
weighted avg       0.94      0.90      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 27 hidden = 2

         0      1   2      3      4   5     -1
 0  191188      0   0      0      0   0  11040
 1       1  85316   0      0      0  48  43171
 2       0      0   0      0      0   0  82305
 3       0      0   0  60866      0   0     84
 4       0      0   0      0  26261   0  19529
 5       0      0   0      0      1  24    122
-1       0      0   0      0      0   0      0

th: 27 hidden: 2 acc:0.8577841201947857 recall:1.0 precision:0.5267486288087756 f1:0.6900266604067807
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.53      1.00      0.69     82305
           0       1.00      0.95      0.97    202228
           1       1.00      0.66      0.80    128536
           3       1.00      1.00      1.00     60950
           4       1.00      0.57      0.73     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.86    519956
   macro avg       0.81      0.72      0.73    519956
weighted avg       0.92      0.86      0.87    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 3

         0       1      2   3      4    5     -1
 0  201798      69      0   0      0    0    361
 1     391  124834     15   0     72  481   2743
 2       0       1  82130   0      0    0    174
 3       0   30717      3   0      0    0  30230
 4       1      18      0   0  45216    0    555
 5       0       7      0   0      7  116     17
-1       0       0      0   0      0    0      0

th: 20 hidden: 3 acc:0.9335136049973459 recall:0.495980311730927 precision:0.8870305164319249 f1:0.6362201410081026
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.89      0.50      0.64     60950
           0       1.00      1.00      1.00    202228
           1       0.80      0.97      0.88    128536
           2       1.00      1.00      1.00     82305
           4       1.00      0.99      0.99     45790
           5       0.19      0.79      0.31       147

    accuracy                           0.93    519956
   macro avg       0.81      0.87      0.80    519956
weighted avg       0.94      0.93      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 3

         0       1      2   3      4    5     -1
 0  201564      67      0   0      0    0    597
 1     391  123150     15   0     70  433   4477
 2       0       1  82003   0      0    0    301
 3       0   14592      3   0      0    0  46355
 4       1      18      0   0  44875    0    896
 5       0       6      0   0      6   91     44
-1       0       0      0   0      0    0      0

th: 21 hidden: 3 acc:0.9597850587357392 recall:0.7605414273995078 precision:0.8801025251566357 f1:0.8159654990318606
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.88      0.76      0.82     60950
           0       1.00      1.00      1.00    202228
           1       0.89      0.96      0.92    128536
           2       1.00      1.00      1.00     82305
           4       1.00      0.98      0.99     45790
           5       0.17      0.62      0.27       147

    accuracy                           0.96    519956
   macro avg       0.82      0.89      0.83    519956
weighted avg       0.96      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 3

         0       1      2   3      4    5     -1
 0  201518      62      0   0      0    0    648
 1     378  116454     13   0     67  164  11460
 2       0       1  81583   0      0    0    721
 3       0   11978      3   0      0    0  48969
 4       1       8      0   0  43998    0   1783
 5       0       4      0   0      5   74     64
-1       0       0      0   0      0    0      0

th: 22 hidden: 3 acc:0.9487322004169584 recall:0.8034290401968827 precision:0.7694084374263492 f1:0.7860508046069264
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.77      0.80      0.79     60950
           0       1.00      1.00      1.00    202228
           1       0.91      0.91      0.91    128536
           2       1.00      0.99      1.00     82305
           4       1.00      0.96      0.98     45790
           5       0.31      0.50      0.38       147

    accuracy                           0.95    519956
   macro avg       0.83      0.86      0.84    519956
weighted avg       0.95      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 3

         0       1      2   3      4   5     -1
 0  201391       0      0   0      0   0    837
 1     260  113508     13   0     59  28  14668
 2       0       1  81016   0      0   0   1288
 3       0   11978      3   0      0   0  48969
 4       1       8      0   0  43569   0   2212
 5       0       4      0   0      5  31    107
-1       0       0      0   0      0   0      0

th: 23 hidden: 3 acc:0.9402007092907861 recall:0.8034290401968827 precision:0.7192755688077437 f1:0.75902690051228
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.72      0.80      0.76     60950
           0       1.00      1.00      1.00    202228
           1       0.90      0.88      0.89    128536
           2       1.00      0.98      0.99     82305
           4       1.00      0.95      0.97     45790
           5       0.53      0.21      0.30       147

    accuracy                           0.94    519956
   macro avg       0.86      0.80      0.82    519956
weighted avg       0.94      0.94      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 3

         0       1      2   3      4   5     -1
 0  199416       0      0   0      0   0   2812
 1       7  107905      3   0     45   0  20576
 2       0       1  80181   0      0   0   2123
 3       0   11978      3   0      0   0  48969
 4       0       8      0   0  42948   0   2834
 5       0       0      0   0      5  24    118
-1       0       0      0   0      0   0      0

th: 24 hidden: 3 acc:0.9222164952419051 recall:0.8034290401968827 precision:0.6324129558838723 f1:0.7077365553323409
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.63      0.80      0.71     60950
           0       1.00      0.99      0.99    202228
           1       0.90      0.84      0.87    128536
           2       1.00      0.97      0.99     82305
           4       1.00      0.94      0.97     45790
           5       1.00      0.16      0.28       147

    accuracy                           0.92    519956
   macro avg       0.92      0.78      0.80    519956
weighted avg       0.93      0.92      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 3

         0       1      2   3      4   5     -1
 0  199396       0      0   0      0   0   2832
 1       3  100292      3   0      2   0  28236
 2       0       1  78012   0      0   0   4292
 3       0    6700      3   0      0   0  54247
 4       0       8      0   0  40797   0   4985
 5       0       0      0   0      5  24    118
-1       0       0      0   0      0   0      0

th: 25 hidden: 3 acc:0.9092884782558525 recall:0.8900246103363413 precision:0.5727695069158484 f1:0.6969934472568419
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.57      0.89      0.70     60950
           0       1.00      0.99      0.99    202228
           1       0.94      0.78      0.85    128536
           2       1.00      0.95      0.97     82305
           4       1.00      0.89      0.94     45790
           5       1.00      0.16      0.28       147

    accuracy                           0.91    519956
   macro avg       0.92      0.78      0.79    519956
weighted avg       0.93      0.91      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 3

         0      1      2   3      4   5     -1
 0  194247      0      0   0      0   0   7981
 1       1  93627      3   0      1   0  34904
 2       0      0  75140   0      0   0   7165
 3       0      0      3   0      0   0  60947
 4       0      6      0   0  35481   0  10303
 5       0      0      0   0      1   8    138
-1       0      0      0   0      0   0      0

th: 26 hidden: 3 acc:0.8836555400841609 recall:0.9999507793273175 precision:0.5018775012763714 f1:0.6683224773559663
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.50      1.00      0.67     60950
           0       1.00      0.96      0.98    202228
           1       1.00      0.73      0.84    128536
           2       1.00      0.91      0.95     82305
           4       1.00      0.77      0.87     45790
           5       1.00      0.05      0.10       147

    accuracy                           0.88    519956
   macro avg       0.92      0.74      0.74    519956
weighted avg       0.94      0.88      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 27 hidden = 3

         0      1      2   3      4   5     -1
 0  193437      0      0   0      0   0   8791
 1       1  65683      2   0      0   0  62850
 2       0      0  72051   0      0   0  10254
 3       0      0      3   0      0   0  60947
 4       0      0      0   0  28079   0  17711
 5       0      0      0   0      0   0    147
-1       0      0      0   0      0   0      0

th: 27 hidden: 3 acc:0.8081453046026972 recall:0.9999507793273175 precision:0.3792594897324207 f1:0.5499390931648996
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.38      1.00      0.55     60950
           0       1.00      0.96      0.98    202228
           1       1.00      0.51      0.68    128536
           2       1.00      0.88      0.93     82305
           4       1.00      0.61      0.76     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.81    519956
   macro avg       0.73      0.66      0.65    519956
weighted avg       0.93      0.81      0.83    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 4

         0       1      2      3   4      5    -1
 0  201775     346      0      0   0      0   107
 1      72  126970     14      1   0    389  1090
 2       0       1  82144      0   0      0   160
 3       0       0      3  60942   0      0     5
 4       1   25058      0      0   0  20337   394
 5       0       8      0      0   0    129    10
-1       0       0      0      0   0      0     0

th: 20 hidden: 4 acc:0.9100539276400311 recall:0.008604498798864381 precision:0.22310305775764439 f1:0.016569938598704686
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.22      0.01      0.02     45790
           0       1.00      1.00      1.00    202228
           1       0.83      0.99      0.90    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.88      0.01       147

    accuracy                           0.91    519956
   macro avg       0.68      0.81      0.66    519956
weighted avg       0.89      0.91      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 4

         0       1      2      3   4    5     -1
 0  201532     346      0      0   0    0    350
 1      71  126278     14      1   0  320   1852
 2       0       1  82025      0   0    0    279
 3       0       0      3  60942   0    0      5
 4       1   25043      0      0   0    7  20739
 5       0       8      0      0   0  105     34
-1       0       0      0      0   0    0      0

th: 21 hidden: 4 acc:0.9469743593688696 recall:0.45291548373007207 precision:0.8916548432864697 f1:0.6007038479920056
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.89      0.45      0.60     45790
           0       1.00      1.00      1.00    202228
           1       0.83      0.98      0.90    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.24      0.71      0.36       147

    accuracy                           0.95    519956
   macro avg       0.83      0.86      0.81    519956
weighted avg       0.95      0.95      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 4

         0       1      2      3   4   5     -1
 0  201399     319      0      0   0   0    510
 1      71  125006     14      1   0  49   3395
 2       0       1  81836      0   0   0    468
 3       0       0      3  60942   0   0      5
 4       1   23554      0      0   0   0  22235
 5       0       4      0      0   0  46     97
-1       0       0      0      0   0   0      0

th: 22 hidden: 4 acc:0.9460915923655079 recall:0.48558637257043025 precision:0.832459752901535 f1:0.6133793103448276
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.83      0.49      0.61     45790
           0       1.00      1.00      1.00    202228
           1       0.84      0.97      0.90    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           5       0.48      0.31      0.38       147

    accuracy                           0.95    519956
   macro avg       0.86      0.79      0.81    519956
weighted avg       0.95      0.95      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 4

         0       1      2      3   4   5     -1
 0  201252     279      0      0   0   0    697
 1      71  123533     14      1   0  48   4869
 2       0       1  81483      0   0   0    821
 3       0       0      3  60942   0   0      5
 4       1   22622      0      0   0   0  23167
 5       0       4      0      0   0  24    119
-1       0       0      0      0   0   0      0

th: 23 hidden: 4 acc:0.9439683357822585 recall:0.5059401616073379 precision:0.7806119010715008 f1:0.6139555838236075
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.78      0.51      0.61     45790
           0       1.00      1.00      1.00    202228
           1       0.84      0.96      0.90    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.33      0.16      0.22       147

    accuracy                           0.94    519956
   macro avg       0.83      0.77      0.79    519956
weighted avg       0.94      0.94      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 4

         0       1      2      3   4   5     -1
 0  201144     279      0      0   0   0    805
 1      70  118689     14      1   0  48   9714
 2       0       1  81327      0   0   0    977
 3       0       0      3  60940   0   0      7
 4       0   21952      0      0   0   0  23838
 5       0       4      0      0   0  24    119
-1       0       0      0      0   0   0      0

th: 24 hidden: 4 acc:0.9354291516974513 recall:0.5205940161607338 precision:0.6722504230118443 f1:0.5867815384615385
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.67      0.52      0.59     45790
           0       1.00      0.99      1.00    202228
           1       0.84      0.92      0.88    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.33      0.16      0.22       147

    accuracy                           0.93    519956
   macro avg       0.81      0.76      0.78    519956
weighted avg       0.93      0.93      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 4

         0       1      2      3   4   5     -1
 0  200952       3      0      0   0   0   1273
 1      66  112966     14      1   0  48  15441
 2       0       0  80606      0   0   0   1699
 3       0       0      3  60935   0   0     12
 4       0   21951      0      0   0   0  23839
 5       0       4      0      0   0  24    119
-1       0       0      0      0   0   0      0

th: 25 hidden: 4 acc:0.9221184100193093 recall:0.5206158549901725 precision:0.5624660830993559 f1:0.5407324237578397
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.56      0.52      0.54     45790
           0       1.00      0.99      1.00    202228
           1       0.84      0.88      0.86    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.33      0.16      0.22       147

    accuracy                           0.92    519956
   macro avg       0.79      0.76      0.77    519956
weighted avg       0.92      0.92      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 4

         0       1      2      3   4   5     -1
 0  195584       0      0      0   0   0   6644
 1       1  104540      3      0   0  48  23944
 2       0       0  78709      0   0   0   3596
 3       0       0      3  60927   0   0     20
 4       0   21948      0      0   0   0  23842
 5       0       0      0      0   0  24    123
-1       0       0      0      0   0   0      0

th: 26 hidden: 4 acc:0.8917696882043865 recall:0.5206813714784888 precision:0.4098746755144493 f1:0.4586808260949028
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.41      0.52      0.46     45790
           0       1.00      0.97      0.98    202228
           1       0.83      0.81      0.82    128536
           2       1.00      0.96      0.98     82305
           3       1.00      1.00      1.00     60950
           5       0.33      0.16      0.22       147

    accuracy                           0.89    519956
   macro avg       0.76      0.74      0.74    519956
weighted avg       0.90      0.89      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 27 hidden = 4

         0      1      2      3   4   5     -1
 0  194899      0      0      0   0   0   7329
 1       1  98997      3      0   0  48  29487
 2       0      0  77006      0   0   0   5299
 3       0      0      3  60909   0   0     38
 4       0      5      0      0   0   0  45785
 5       0      0      0      0   0  24    123
-1       0      0      0      0   0   0      0

th: 27 hidden: 4 acc:0.918683503988799 recall:0.9998908058528063 precision:0.5199236892608533 f1:0.6841189083383763
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.52      1.00      0.68     45790
           0       1.00      0.96      0.98    202228
           1       1.00      0.77      0.87    128536
           2       1.00      0.94      0.97     82305
           3       1.00      1.00      1.00     60950
           5       0.33      0.16      0.22       147

    accuracy                           0.92    519956
   macro avg       0.81      0.81      0.79    519956
weighted avg       0.96      0.92      0.93    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 5

         0       1      2      3      4   5    -1
 0  201543      43      0      0      0   0   642
 1     157  126105     14      0     85   0  2175
 2       0       1  81749      0      0   0   555
 3       0       0      3  60917      0   0    30
 4       0      20      0      0  45409   0   361
 5       0     112      0      0     10   0    25
-1       0       0      0      0      0   0     0

th: 20 hidden: 5 acc:0.9925282139257937 recall:0.17006802721088435 precision:0.006599788806758183 f1:0.012706480304955527
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.17      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.98      0.99    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.86      0.83    519956
weighted avg       1.00      0.99      1.00    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 5

         0       1      2      3      4   5    -1
 0  201297       1      0      0      0   0   930
 1      49  123711     14      0     84   0  4678
 2       0       1  81684      0      0   0   620
 3       0       0      3  60916      0   0    31
 4       0       8      0      0  44758   0  1024
 5       0     107      0      0      9   0    31
-1       0       0      0      0      0   0     0

th: 21 hidden: 5 acc:0.9857699497649801 recall:0.2108843537414966 precision:0.004238446814328685 f1:0.00830987803243533
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.21      0.01       147
           0       1.00      1.00      1.00    202228
           1       1.00      0.96      0.98    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.98      0.99     45790

    accuracy                           0.99    519956
   macro avg       0.83      0.86      0.83    519956
weighted avg       1.00      0.99      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 5

         0       1      2      3      4   5    -1
 0  201115       1      0      0      0   0  1112
 1      31  119645     14      0     66   0  8780
 2       0       1  81502      0      0   0   802
 3       0       0      3  60916      0   0    31
 4       0       2      0      0  44223   0  1565
 5       0      79      0      0      9   0    59
-1       0       0      0      0      0   0     0

th: 22 hidden: 5 acc:0.9761941395041119 recall:0.4013605442176871 precision:0.00477771479472022 f1:0.009443021766965428
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.40      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.93      0.96    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.97      0.98     45790

    accuracy                           0.98    519956
   macro avg       0.83      0.88      0.82    519956
weighted avg       1.00      0.98      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 5

         0       1      2      3      4   5     -1
 0  200589       0      0      0      0   0   1639
 1       0  110829     14      0     63   0  17630
 2       0       0  81126      0      0   0   1179
 3       0       0      3  60916      0   0     31
 4       0       0      0      0  44000   0   1790
 5       0      62      0      0      8   0     77
-1       0       0      0      0      0   0      0

th: 23 hidden: 5 acc:0.9570367492633992 recall:0.5238095238095238 precision:0.003445806855813121 f1:0.006846574489841284
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.52      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.86      0.93    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.96      0.98     45790

    accuracy                           0.96    519956
   macro avg       0.83      0.89      0.82    519956
weighted avg       1.00      0.96      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 5

         0       1      2      3      4   5     -1
 0  199045       0      0      0      0   0   3183
 1       0  108806     13      0     61   0  19656
 2       0       0  80169      0      0   0   2136
 3       0       0      3  60904      0   0     43
 4       0       0      0      0  43829   0   1961
 5       0      49      0      0      7   0     91
-1       0       0      0      0      0   0      0

th: 24 hidden: 5 acc:0.9480052158259545 recall:0.6190476190476191 precision:0.003361654968599926 f1:0.006686997097402358
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.62      0.01       147
           0       1.00      0.98      0.99    202228
           1       1.00      0.85      0.92    128536
           2       1.00      0.97      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.96      0.98     45790

    accuracy                           0.95    519956
   macro avg       0.83      0.90      0.81    519956
weighted avg       1.00      0.95      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 5

         0       1      2      3      4   5     -1
 0  197849       0      0      0      0   0   4379
 1       0  102821      3      0     44   0  25668
 2       0       0  78397      0      0   0   3908
 3       0       0      3  60902      0   0     45
 4       0       0      0      0  43438   0   2352
 5       0      46      0      0      6   0     95
-1       0       0      0      0      0   0      0

th: 25 hidden: 5 acc:0.9299863834632162 recall:0.6462585034013606 precision:0.00260652454248635 f1:0.005192107995846313
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.65      0.01       147
           0       1.00      0.98      0.99    202228
           1       1.00      0.80      0.89    128536
           2       1.00      0.95      0.98     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.95      0.97     45790

    accuracy                           0.93    519956
   macro avg       0.83      0.89      0.81    519956
weighted avg       1.00      0.93      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 26 hidden = 5

         0      1      2      3      4   5     -1
 0  193225      0      0      0      0   0   9003
 1       0  94283      3      0      0   0  34250
 2       0      0  74820      0      0   0   7485
 3       0      0      3  60892      0   0     55
 4       0      0      0      0  41471   0   4319
 5       0     18      0      0      6   0    123
-1       0      0      0      0      0   0      0

th: 26 hidden: 5 acc:0.8939602581756918 recall:0.8367346938775511 precision:0.002226848918258351 f1:0.004441876421942148
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.84      0.00       147
           0       1.00      0.96      0.98    202228
           1       1.00      0.73      0.85    128536
           2       1.00      0.91      0.95     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.91      0.95     45790

    accuracy                           0.89    519956
   macro avg       0.83      0.89      0.79    519956
weighted avg       1.00      0.89      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 27 hidden = 5

         0      1      2      3      4   5     -1
 0  189367      0      0      0      0   0  12861
 1       0  75150      3      0      0   0  53383
 2       0      0  71083      0      0   0  11222
 3       0      0      3  60808      0   0    139
 4       0      0      0      0  40125   0   5665
 5       0      0      0      0      3   0    144
-1       0      0      0      0      0   0      0

th: 27 hidden: 5 acc:0.8398460638977144 recall:0.9795918367346939 precision:0.001726328913611624 f1:0.003446583932695875
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.98      0.00       147
           0       1.00      0.94      0.97    202228
           1       1.00      0.58      0.74    128536
           2       1.00      0.86      0.93     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.88      0.93     45790

    accuracy                           0.84    519956
   macro avg       0.83      0.87      0.76    519956
weighted avg       1.00      0.84      0.90    519956

# Média absolute threshold

In [8]:
for i in range(len(f1s)):
    print(f'Média f1 absolute th {ths[i]}: {np.mean(np.array(f1s[i]))}')

Média f1 absolute th 20: 0.5007415754543887
Média f1 absolute th 21: 0.6584299012373065
Média f1 absolute th 22: 0.6571573122750525
Média f1 absolute th 23: 0.650093386492642
Média f1 absolute th 24: 0.6235482825706782
Média f1 absolute th 25: 0.5991093246813098
Média f1 absolute th 26: 0.5572627356056554
Média f1 absolute th 27: 0.5599554477676085