In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture

In [3]:
def matriz_conf(y_true, y_pred, labels):
    total_labels = labels
    print(total_labels)
    cm = np.zeros((len(total_labels),len(total_labels)), dtype=int)
    for i in range(len(y_true)):
        cm[y_true[i]][y_pred[i]] += 1

    
    cm = pd.DataFrame(cm, columns=total_labels, index=total_labels)

    cm_transp = pd.DataFrame(np.transpose(cm.to_numpy()), columns=total_labels, index=total_labels)

    for c in cm_transp.columns:
        cm_transp[c] = cm_transp[c]/cm_transp[c].sum()

    cm_porcento = pd.DataFrame(np.transpose(cm_transp.to_numpy()), columns=total_labels, index=total_labels)

    return cm, cm_porcento

def acc(cm, hidden_classes):
    cm_transp = pd.DataFrame(np.transpose(cm.dropna().to_numpy()), columns=cm.columns, index=cm.columns)
    acc = 0
    total = 0
    for c in cm_transp.columns:
        if c not in hidden_classes:
            acc += cm_transp[c][c]
        else:
            acc += cm_transp[c][-1]
        total += cm_transp[c].sum()
    return acc/total

In [4]:
filenames = [0,2,3,4,5]

labels_str = ['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

filenames

# pd.set_option('future.no_silent_downcasting', True)

[0, 2, 3, 4, 5]

In [5]:
exp_val = []
y_true_all_exp_val = []
for i in range(len(filenames)):
    exp_val.append(pd.read_csv(f'val_{filenames[i]}_GMM_BIC_1_10_scores_corr.csv'))
    y_true_all_exp_val.append(exp_val[i]['Label'].values.tolist())
    exp_val[i] = exp_val[i].drop(columns=['Label'])

In [6]:
from sklearn.metrics import classification_report
ths = [20, 20.5, 21, 21.5, 22, 23, 24, 25]
f1s = [[],[],[],[],[],[],[],[]]
for i in range(len(exp_val)):
    index = 0
    for th in ths:
        y_pred = []
        prog= 0
        for j in range(len(exp_val[i])):
            # print(exp[i][j])
            m = np.nanmax(exp_val[i].values[j])
            # print(m)
            if m > th:
                y_pred.append(exp_val[i].values[j].tolist().index(m))
            else:
                y_pred.append(-1)
        # print(y_pred[:10])

        cm, cm_porcento = matriz_conf(y_true_all_exp_val[i], y_pred, list(range(len(labels_str))) + [-1])
        print(f'th = {th} hidden = {filenames[i]}')
        display(cm)
        tp = cm[-1][filenames[i]]
        fp = cm[-1].sum() - tp
        fn = cm.iloc[filenames[i]].sum() - tp
        tn = cm.drop(columns=[-1]).values.sum() - fn

        acc = (tp+tn)/(tp+fp+tn+fn)
        recall = tp/(tp+fn)
        precision = tp/(tp+fp)
        if precision == 0 or recall == 0:
            f1 = 0
        else:
            f1 = 2*precision*recall/(precision+recall)

        f1s[index].append(f1)
        index += 1
        print(f'th: {th} hidden: {filenames[i]} acc:{acc} recall:{recall} precision:{precision} f1:{f1}')

        true_labels = np.array(y_true_all_exp_val[i])
        true_labels[true_labels == filenames[i]] = -1

        print('MULTICLASS DETECTION')
        print(classification_report(true_labels, y_pred))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 0

     0       1      2      3      4   5      -1
 0   0   59660      0      0      0   0  142568
 1   0  125832     45      5    272  72    2310
 2   0       3  82044      0      0   0     258
 3   0       0      3  60903      0   0      44
 4   0      57      0      0  45569   0     164
 5   0       9      0      0     10  91      37
-1   0       0      0      0      0   0       0

th: 20 hidden: 0 acc:0.8798494487995138 recall:0.7049864509365666 precision:0.9806508415817747 f1:0.8202779559792756
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.98      0.70      0.82    202228
           1       0.68      0.98      0.80    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       0.99      1.00      0.99     45790
           5       0.56      0.62      0.59       147

    accuracy                           0.88    519956
   macro avg       0.87      0.88      0.87    519956
weighted avg       0.91      0.88      0.88    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 0

     0       1      2      3      4   5      -1
 0   0   58370      0      0      0   0  143858
 1   0  125119     43      5    268  68    3033
 2   0       3  82000      0      0   0     302
 3   0       0      3  60903      0   0      44
 4   0      54      0      0  45569   0     167
 5   0       9      0      0     10  87      41
-1   0       0      0      0      0   0       0

th: 20.5 hidden: 0 acc:0.8808418404634238 recall:0.7113653895602983 precision:0.9756722845806911 f1:0.8228144580794056
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.98      0.71      0.82    202228
           1       0.68      0.97      0.80    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       0.99      1.00      0.99     45790
           5       0.56      0.59      0.58       147

    accuracy                           0.88    519956
   macro avg       0.87      0.88      0.87    519956
weighted avg       0.91      0.88      0.88    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 0

     0       1      2      3      4   5      -1
 0   0   52925      0      0      0   0  149303
 1   0  124430     40      5    267  53    3741
 2   0       1  81966      0      0   0     338
 3   0       0      3  60903      0   0      44
 4   0      51      0      0  45567   0     172
 5   0       8      0      0     10  76      53
-1   0       0      0      0      0   0       0

th: 21 hidden: 0 acc:0.8898502950249636 recall:0.73829044444884 precision:0.9717021041190751 f1:0.8390660870689195
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.74      0.84    202228
           1       0.70      0.97      0.81    128536
           2       1.00      1.00      1.00     82305
           3       1.00      1.00      1.00     60950
           4       0.99      1.00      0.99     45790
           5       0.59      0.52      0.55       147

    accuracy                           0.89    519956
   macro avg       0.88      0.87      0.87    519956
weighted avg       0.91      0.89      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 0

     0       1      2      3      4   5      -1
 0   0   48460      0      0      0   0  153768
 1   0  123456     36      5    266  49    4724
 2   0       1  81779      0      0   0     525
 3   0       0      3  60903      0   0      44
 4   0      45      0      0  45565   0     180
 5   0       7      0      0     10  74      56
-1   0       0      0      0      0   0       0

th: 21.5 hidden: 0 acc:0.896166214064267 recall:0.7603694839488102 precision:0.9652912484227575 f1:0.8506631629901112
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.97      0.76      0.85    202228
           1       0.72      0.96      0.82    128536
           2       1.00      0.99      1.00     82305
           3       1.00      1.00      1.00     60950
           4       0.99      1.00      0.99     45790
           5       0.60      0.50      0.55       147

    accuracy                           0.90    519956
   macro avg       0.88      0.87      0.87    519956
weighted avg       0.92      0.90      0.90    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 0

     0       1      2      3      4   5      -1
 0   0   48425      0      0      0   0  153803
 1   0  122133     17      5    265  49    6067
 2   0       1  81432      0      0   0     872
 3   0       0      3  60903      0   0      44
 4   0      15      0      0  45563   0     212
 5   0       6      0      0     10  66      65
-1   0       0      0      0      0   0       0

th: 22 hidden: 0 acc:0.8929043996030434 recall:0.7605425559269735 precision:0.9549244705487915 f1:0.846720672959143
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.95      0.76      0.85    202228
           1       0.72      0.95      0.82    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       0.99      1.00      0.99     45790
           5       0.57      0.45      0.50       147

    accuracy                           0.89    519956
   macro avg       0.87      0.86      0.86    519956
weighted avg       0.91      0.89      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 0

     0       1      2      3      4   5      -1
 0   0   48384      0      0      0   0  153844
 1   0  119286     17      4    247  49    8933
 2   0       1  81098      0      0   0    1206
 3   0       0      3  60902      0   0      45
 4   0       3      0      0  45555   0     232
 5   0       0      0      0      8  66      73
-1   0       0      0      0      0   0       0

th: 23 hidden: 0 acc:0.886773111570979 recall:0.7607452973871076 precision:0.9361722843251203 f1:0.8393909881302157
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.94      0.76      0.84    202228
           1       0.71      0.93      0.81    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           4       0.99      0.99      0.99     45790
           5       0.57      0.45      0.50       147

    accuracy                           0.89    519956
   macro avg       0.87      0.85      0.86    519956
weighted avg       0.90      0.89      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 0

     0       1      2      3      4   5      -1
 0   0   46151      0      0      0   0  156077
 1   0  115911      3      4    225  49   12344
 2   0       1  80131      0      0   0    2173
 3   0       0      3  60897      0   0      50
 4   0       0      0      0  45515   0     275
 5   0       0      0      0      7  66      74
-1   0       0      0      0      0   0       0

th: 24 hidden: 0 acc:0.8825535237597028 recall:0.7717872895939237 precision:0.91276835893867 f1:0.8363784460145597
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.91      0.77      0.84    202228
           1       0.72      0.90      0.80    128536
           2       1.00      0.97      0.99     82305
           3       1.00      1.00      1.00     60950
           4       0.99      0.99      0.99     45790
           5       0.57      0.45      0.50       147

    accuracy                           0.88    519956
   macro avg       0.87      0.85      0.85    519956
weighted avg       0.90      0.88      0.88    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 0

     0       1      2      3      4   5      -1
 0   0   46060      0      0      0   0  156168
 1   0  114085      3      2    198  49   14199
 2   0       0  79531      0      0   0    2774
 3   0       0      3  60893      0   0      54
 4   0       0      0      0  45366   0     424
 5   0       0      0      0      6  66      75
-1   0       0      0      0      0   0       0

th: 25 hidden: 0 acc:0.8777088830593358 recall:0.7722372767371481 precision:0.8990984144530035 f1:0.8308532089103591
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.90      0.77      0.83    202228
           1       0.71      0.89      0.79    128536
           2       1.00      0.97      0.98     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790
           5       0.57      0.45      0.50       147

    accuracy                           0.88    519956
   macro avg       0.86      0.84      0.85    519956
weighted avg       0.89      0.88      0.88    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 2

         0       1   2      3      4   5     -1
 0  201527     280   0      0      0   0    421
 1      35  115227   0     10    100  93  13071
 2       0      36   0   1401      0   0  80868
 3       0       0   0  60847      0   0    103
 4       1      11   0      0  45344   0    434
 5       0       4   0      0      7  89     47
-1       0       0   0      0      0   0      0

th: 20 hidden: 2 acc:0.9701647831739608 recall:0.9825405503918353 precision:0.8517441860465116 f1:0.912479054888885
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.85      0.98      0.91     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.90      0.94    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.99      0.99     45790
           5       0.49      0.61      0.54       147

    accuracy                           0.97    519956
   macro avg       0.89      0.91      0.90    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 2

         0       1   2      3      4   5     -1
 0  201499     280   0      0      0   0    449
 1      35  114278   0      8     98  49  14068
 2       0      35   0   1338      0   0  80932
 3       0       0   0  60847      0   0    103
 4       1       9   0      0  45325   0    455
 5       0       4   0      0      7  73     63
-1       0       0   0      0      0   0      0

th: 20.5 hidden: 2 acc:0.968245389994538 recall:0.9833181459206609 precision:0.8424273966899136 f1:0.907436580238262
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.84      0.98      0.91     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.89      0.94    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.99      0.99     45790
           5       0.60      0.50      0.54       147

    accuracy                           0.97    519956
   macro avg       0.90      0.89      0.90    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 2

         0       1   2      3      4   5     -1
 0  201492     280   0      0      0   0    456
 1      30  112723   0      8     94  48  15633
 2       0      35   0   1283      0   0  80987
 3       0       0   0  60847      0   0    103
 4       1       7   0      0  45301   0    481
 5       0       4   0      0      6  72     65
-1       0       0   0      0      0   0      0

th: 21 hidden: 2 acc:0.9652739847217842 recall:0.9839863920782456 precision:0.8287234586850857 f1:0.899705604621452
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.83      0.98      0.90     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.88      0.93    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.99      0.99     45790
           5       0.60      0.49      0.54       147

    accuracy                           0.96    519956
   macro avg       0.90      0.89      0.89    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 2

         0       1   2      3      4   5     -1
 0  201464     279   0      0      0   0    485
 1      30  110158   0      8     90  48  18202
 2       0      35   0   1226      0   0  81044
 3       0       0   0  60844      0   0    106
 4       1       6   0      0  45270   0    513
 5       0       4   0      0      6  72     65
-1       0       0   0      0      0   0      0

th: 21.5 hidden: 2 acc:0.960319719360869 recall:0.984678938096106 precision:0.8070905741174127 f1:0.8870840630472854
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.81      0.98      0.89     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.86      0.92    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.99      0.99     45790
           5       0.60      0.49      0.54       147

    accuracy                           0.96    519956
   macro avg       0.90      0.89      0.89    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 2

         0       1   2      3      4   5     -1
 0  201435       0   0      0      0   0    793
 1      30  106291   0      8     88   0  22119
 2       0      35   0   1169      0   0  81101
 3       0       0   0  60842      0   0    108
 4       1       6   0      0  45228   0    555
 5       0       0   0      0      6  32    109
-1       0       0   0      0      0   0      0

th: 22 hidden: 2 acc:0.95213441137327 recall:0.9853714841139664 precision:0.7739752827217636 f1:0.8669731145438024
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.77      0.99      0.87     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.83      0.91    128536
           3       0.98      1.00      0.99     60950
           4       1.00      0.99      0.99     45790
           5       1.00      0.22      0.36       147

    accuracy                           0.95    519956
   macro avg       0.96      0.84      0.85    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 2

         0       1   2      3      4   5     -1
 0  201338       0   0      0      0   0    890
 1      30  103447   0      7     74   0  24978
 2       0      35   0   1034      0   0  81236
 3       0       0   0  60606      0   0    344
 4       1       6   0      0  44981   0    802
 5       0       0   0      0      5   0    142
-1       0       0   0      0      0   0      0

th: 23 hidden: 2 acc:0.9457165606320534 recall:0.987011724682583 precision:0.7494649051590523 f1:0.8519903302097043
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.75      0.99      0.85     82305
           0       1.00      1.00      1.00    202228
           1       1.00      0.80      0.89    128536
           3       0.98      0.99      0.99     60950
           4       1.00      0.98      0.99     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.95    519956
   macro avg       0.79      0.79      0.79    519956
weighted avg       0.96      0.95      0.95    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 2

         0      1   2      3      4   5     -1
 0  200042      0   0      0      0   0   2186
 1      30  95524   0      7     59   0  32916
 2       0      0   0    883      0   0  81422
 3       0      0   0  59688      0   0   1262
 4       1      6   0      0  44541   0   1242
 5       0      0   0      0      5   0    142
-1       0      0   0      0      0   0      0

th: 24 hidden: 2 acc:0.9257033287432014 recall:0.9892716116882327 precision:0.6832424267852647 f1:0.8082590892170244
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.68      0.99      0.81     82305
           0       1.00      0.99      0.99    202228
           1       1.00      0.74      0.85    128536
           3       0.99      0.98      0.98     60950
           4       1.00      0.97      0.99     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.93    519956
   macro avg       0.78      0.78      0.77    519956
weighted avg       0.95      0.93      0.93    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 2

         0      1   2      3      4   5     -1
 0  199538      0   0      0      0   0   2690
 1      12  86143   0      6      0   0  42375
 2       0      0   0    674      0   0  81631
 3       0      0   0  59632      0   0   1318
 4       1      6   0      0  41827   0   3956
 5       0      0   0      0      5   0    142
-1       0      0   0      0      0   0      0

th: 25 hidden: 2 acc:0.9016166752571372 recall:0.9918109470870542 precision:0.6178923943320819 f1:0.7614228349431248
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.62      0.99      0.76     82305
           0       1.00      0.99      0.99    202228
           1       1.00      0.67      0.80    128536
           3       0.99      0.98      0.98     60950
           4       1.00      0.91      0.95     45790
           5       0.00      0.00      0.00       147

    accuracy                           0.90    519956
   macro avg       0.77      0.76      0.75    519956
weighted avg       0.94      0.90      0.90    519956

d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Downloads\Mestrado\Experimentos\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 3

         0       1      2   3      4    5     -1
 0  201016     286      0   0      0   61    865
 1      77  112568     28   0    160  473  15230
 2       0       1  80891   0      0    0   1413
 3       0       0     67   0      0    0  60883
 4       1       6      0   0  45425  163    195
 5       0       4      0   0      6   97     40
-1       0       0      0   0      0    0      0

th: 20 hidden: 3 acc:0.9657471016778343 recall:0.9989007383100902 precision:0.7743367333960777 f1:0.8723992663495157
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.77      1.00      0.87     60950
           0       1.00      0.99      1.00    202228
           1       1.00      0.88      0.93    128536
           2       1.00      0.98      0.99     82305
           4       1.00      0.99      0.99     45790
           5       0.12      0.66      0.21       147

    accuracy                           0.96    519956
   macro avg       0.81      0.92      0.83    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 3

         0       1      2   3      4    5     -1
 0  200667     286      0   0      0   55   1220
 1      75  110490     28   0    130  278  17535
 2       0       1  80449   0      0    0   1855
 3       0       0     56   0      0    0  60894
 4       1       6      0   0  45404  163    216
 5       0       4      0   0      6   88     49
-1       0       0      0   0      0    0      0

th: 20.5 hidden: 3 acc:0.9597446707029056 recall:0.9990812141099261 precision:0.7447076520441732 f1:0.8533411809219514
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.74      1.00      0.85     60950
           0       1.00      0.99      1.00    202228
           1       1.00      0.86      0.92    128536
           2       1.00      0.98      0.99     82305
           4       1.00      0.99      0.99     45790
           5       0.15      0.60      0.24       147

    accuracy                           0.96    519956
   macro avg       0.81      0.90      0.83    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 3

         0       1      2   3      4    5     -1
 0  199651     286      0   0      0   52   2239
 1      69  108617     27   0    113  146  19564
 2       0       1  80072   0      0    0   2232
 3       0       0     26   0      0    0  60924
 4       1       6      0   0  45368  163    252
 5       0       4      0   0      6   78     59
-1       0       0      0   0      0    0      0

th: 21 hidden: 3 acc:0.9531268030371801 recall:0.9995734208367514 precision:0.7144834056526328 f1:0.8333196553139105
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.71      1.00      0.83     60950
           0       1.00      0.99      0.99    202228
           1       1.00      0.85      0.91    128536
           2       1.00      0.97      0.99     82305
           4       1.00      0.99      0.99     45790
           5       0.18      0.53      0.27       147

    accuracy                           0.95    519956
   macro avg       0.81      0.89      0.83    519956
weighted avg       0.97      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 3

         0       1      2   3      4    5     -1
 0  199149     286      0   0      0   47   2746
 1      69  106470     24   0    107  116  21750
 2       0       1  79913   0      0    0   2391
 3       0       0      6   0      0    0  60944
 4       1       6      0   0  45351  163    269
 5       0       4      0   0      6   76     61
-1       0       0      0   0      0    0      0

th: 21.5 hidden: 3 acc:0.9476436467701114 recall:0.9999015586546349 precision:0.691280725037148 f1:0.8174313095613336
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.69      1.00      0.82     60950
           0       1.00      0.98      0.99    202228
           1       1.00      0.83      0.90    128536
           2       1.00      0.97      0.99     82305
           4       1.00      0.99      0.99     45790
           5       0.19      0.52      0.28       147

    accuracy                           0.95    519956
   macro avg       0.81      0.88      0.83    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 3

         0       1      2   3      4    5     -1
 0  199089     285      0   0      0    4   2850
 1      69  102500     13   0    101   75  25778
 2       0       0  79330   0      0    0   2975
 3       0       0      4   0      0    0  60946
 4       1       4      0   0  45289  163    333
 5       0       4      0   0      6   74     63
-1       0       0      0   0      0    0      0

th: 22 hidden: 3 acc:0.9384505612013324 recall:0.9999343724364232 precision:0.65572112539674 f1:0.79204652522824
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.66      1.00      0.79     60950
           0       1.00      0.98      0.99    202228
           1       1.00      0.80      0.89    128536
           2       1.00      0.96      0.98     82305
           4       1.00      0.99      0.99     45790
           5       0.23      0.50      0.32       147

    accuracy                           0.94    519956
   macro avg       0.81      0.87      0.83    519956
weighted avg       0.96      0.94      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 3

         0      1      2   3      4   5     -1
 0  198476    283      0   0      0   0   3469
 1      63  94980      9   0     86  55  33343
 2       0      0  77489   0      0   0   4816
 3       0      0      3   0      0   0  60947
 4       1      4      0   0  45050  97    638
 5       0      4      0   0      6  66     71
-1       0      0      0   0      0   0      0

th: 23 hidden: 3 acc:0.9185700328489333 recall:0.9999507793273175 precision:0.5900913984741102 f1:0.7421971090030078
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.59      1.00      0.74     60950
           0       1.00      0.98      0.99    202228
           1       1.00      0.74      0.85    128536
           2       1.00      0.94      0.97     82305
           4       1.00      0.98      0.99     45790
           5       0.30      0.45      0.36       147

    accuracy                           0.92    519956
   macro avg       0.81      0.85      0.82    519956
weighted avg       0.95      0.92      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 3

         0      1      2   3      4   5     -1
 0  198241    277      0   0      0   0   3710
 1       3  77544      5   0     28  49  50907
 2       0      0  76157   0      0   0   6148
 3       0      0      3   0      0   0  60947
 4       1      0      0   0  43885   0   1904
 5       0      4      0   0      5  52     86
-1       0      0      0   0      0   0      0

th: 24 hidden: 3 acc:0.8793013254967728 recall:0.9999507793273175 precision:0.49269211492134324 f1:0.6601282412321556
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.49      1.00      0.66     60950
           0       1.00      0.98      0.99    202228
           1       1.00      0.60      0.75    128536
           2       1.00      0.93      0.96     82305
           4       1.00      0.96      0.98     45790
           5       0.51      0.35      0.42       147

    accuracy                           0.88    519956
   macro avg       0.83      0.80      0.79    519956
weighted avg       0.94      0.88      0.89    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 3

         0      1      2   3      4   5     -1
 0  197275      3      0   0      0   0   4950
 1       0  60664      2   0      2  48  67820
 2       0      0  73468   0      0   0   8837
 3       0      0      3   0      0   0  60947
 4       0      0      0   0  41338   0   4452
 5       0      4      0   0      5  24    114
-1       0      0      0   0      0   0      0

th: 25 hidden: 3 acc:0.8342628991683911 recall:0.9999507793273175 precision:0.41426726481783577 f1:0.5858316912577497
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.41      1.00      0.59     60950
           0       1.00      0.98      0.99    202228
           1       1.00      0.47      0.64    128536
           2       1.00      0.89      0.94     82305
           4       1.00      0.90      0.95     45790
           5       0.33      0.16      0.22       147

    accuracy                           0.83    519956
   macro avg       0.79      0.73      0.72    519956
weighted avg       0.93      0.83      0.84    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 4

         0       1      2      3   4      5     -1
 0  201657       5      0      0   0      0    566
 1    1878  117782     14      1   0   1249   7612
 2       0       1  81249      0   0      0   1055
 3       0       0      3  60906   0      0     41
 4       1    3083      0      0   0  15508  27198
 5       0       1      0      0   0     93     53
-1       0       0      0      0   0      0      0

th: 20 hidden: 4 acc:0.946305071967628 recall:0.5939724830749071 precision:0.7446406570841889 f1:0.6608273097248376
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.74      0.59      0.66     45790
           0       0.99      1.00      0.99    202228
           1       0.97      0.92      0.94    128536
           2       1.00      0.99      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.01      0.63      0.01       147

    accuracy                           0.94    519956
   macro avg       0.79      0.85      0.77    519956
weighted avg       0.97      0.94      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 4

         0       1      2      3   4     5     -1
 0  201428       4      0      0   0     0    796
 1    1873  116706     14      0   0  1247   8696
 2       0       0  81018      0   0     0   1287
 3       0       0      3  60905   0     0     42
 4       1    2485      0      0   0  2827  40477
 5       0       1      0      0   0    93     53
-1       0       0      0      0   0     0      0

th: 20.5 hidden: 4 acc:0.9688685196439699 recall:0.8839702991919633 precision:0.7882417090222196 f1:0.8333659319957587
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.79      0.88      0.83     45790
           0       0.99      1.00      0.99    202228
           1       0.98      0.91      0.94    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.02      0.63      0.04       147

    accuracy                           0.96    519956
   macro avg       0.80      0.90      0.80    519956
weighted avg       0.97      0.96      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 4

         0       1      2      3   4     5     -1
 0  201369       3      0      0   0     0    856
 1    1869  115699     13      0   0  1240   9715
 2       0       0  80859      0   0     0   1446
 3       0       0      3  60903   0     0     44
 4       1    2404      0      0   0     2  43383
 5       0       1      0      0   0    91     55
-1       0       0      0      0   0     0      0

th: 21 hidden: 4 acc:0.9720687904361138 recall:0.9474339375409478 precision:0.781689760175859 f1:0.8566181915114178
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.78      0.95      0.86     45790
           0       0.99      1.00      0.99    202228
           1       0.98      0.90      0.94    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.07      0.62      0.12       147

    accuracy                           0.97    519956
   macro avg       0.80      0.91      0.82    519956
weighted avg       0.97      0.97      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 4

         0       1      2      3   4     5     -1
 0  201337       3      0      0   0     0    888
 1    1862  114422      3      0   0  1234  11015
 2       0       0  80019      0   0     0   2286
 3       0       0      3  60901   0     0     46
 4       1    2404      0      0   0     0  43385
 5       0       1      0      0   0    78     68
-1       0       0      0      0   0     0      0

th: 21.5 hidden: 4 acc:0.9678665117817662 recall:0.9474776151998253 precision:0.7520628206906116 f1:0.8385357274009935
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.75      0.95      0.84     45790
           0       0.99      1.00      0.99    202228
           1       0.98      0.89      0.93    128536
           2       1.00      0.97      0.99     82305
           3       1.00      1.00      1.00     60950
           5       0.06      0.53      0.11       147

    accuracy                           0.96    519956
   macro avg       0.80      0.89      0.81    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 4

         0       1      2      3   4     5     -1
 0  201317       2      0      0   0     0    909
 1    1849  113406      3      0   0  1226  12052
 2       0       0  79554      0   0     0   2751
 3       0       0      3  60899   0     0     48
 4       1    2404      0      0   0     0  43385
 5       0       1      0      0   0    75     71
-1       0       0      0      0   0     0      0

th: 22 hidden: 4 acc:0.9649278015832109 recall:0.9474776151998253 precision:0.7326567144015131 f1:0.8263337333104775
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.73      0.95      0.83     45790
           0       0.99      1.00      0.99    202228
           1       0.98      0.88      0.93    128536
           2       1.00      0.97      0.98     82305
           3       1.00      1.00      1.00     60950
           5       0.06      0.51      0.10       147

    accuracy                           0.96    519956
   macro avg       0.79      0.88      0.81    519956
weighted avg       0.97      0.96      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 4

         0       1      2      3   4     5     -1
 0  201176       0      0      0   0     0   1052
 1     263  109958      3      0   0  1210  17102
 2       0       0  79088      0   0     0   3217
 3       0       0      3  60888   0     0     59
 4       1    2400      0      0   0     0  43389
 5       0       1      0      0   0    41    105
-1       0       0      0      0   0     0      0

th: 23 hidden: 4 acc:0.9539653355283909 recall:0.9475649705175803 precision:0.6683044790832358 f1:0.7838033130408077
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.67      0.95      0.78     45790
           0       1.00      0.99      1.00    202228
           1       0.98      0.86      0.91    128536
           2       1.00      0.96      0.98     82305
           3       1.00      1.00      1.00     60950
           5       0.03      0.28      0.06       147

    accuracy                           0.95    519956
   macro avg       0.78      0.84      0.79    519956
weighted avg       0.96      0.95      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 4

         0       1      2      3   4     5     -1
 0  200677       0      0      0   0     0   1551
 1      10  100659      3      0   0  1206  26658
 2       0       0  77428      0   0     0   4877
 3       0       0      3  60876   0     0     71
 4       0    2400      0      0   0     0  43390
 5       0       1      0      0   0    36    110
-1       0       0      0      0   0     0      0

th: 24 hidden: 4 acc:0.9314038110917078 recall:0.947586809347019 precision:0.5660278904731466 f1:0.7087147908891195
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.57      0.95      0.71     45790
           0       1.00      0.99      1.00    202228
           1       0.98      0.78      0.87    128536
           2       1.00      0.94      0.97     82305
           3       1.00      1.00      1.00     60950
           5       0.03      0.24      0.05       147

    accuracy                           0.93    519956
   macro avg       0.76      0.82      0.77    519956
weighted avg       0.96      0.93      0.94    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 4

         0      1      2      3   4     5     -1
 0  200136      0      0      0   0     0   2092
 1       8  95603      3      0   0  1205  31717
 2       0      0  71836      0   0     0  10469
 3       0      0      3  60769   0     0    178
 4       0      0      0      0   0     0  45790
 5       0      0      0      0   0    36    111
-1       0      0      0      0   0     0      0

th: 25 hidden: 4 acc:0.9142869781289186 recall:1.0 precision:0.5067675996325686 f1:0.6726552917067582
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.51      1.00      0.67     45790
           0       1.00      0.99      0.99    202228
           1       1.00      0.74      0.85    128536
           2       1.00      0.87      0.93     82305
           3       1.00      1.00      1.00     60950
           5       0.03      0.24      0.05       147

    accuracy                           0.91    519956
   macro avg       0.76      0.81      0.75    519956
weighted avg       0.96      0.91      0.92    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20 hidden = 5

         0       1      2      3      4   5    -1
 0  201130     309      0      0      0   0   789
 1     732  118005     15      6    166   0  9612
 2       0       0  80835      0      0   0  1470
 3       0       0      3  60898      0   0    49
 4       1      41      0      0  45622   0   126
 5       0      70      0      0     13   0    64
-1       0       0      0      0      0   0     0

th: 20 hidden: 5 acc:0.9766730261791382 recall:0.43537414965986393 precision:0.005284888521882742 f1:0.010443012156318838
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.01      0.44      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.92      0.96    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.97    519956
   macro avg       0.83      0.89      0.82    519956
weighted avg       1.00      0.97      0.99    519956

[0, 1, 2, 3, 4, 5, -1]
th = 20.5 hidden = 5

         0       1      2      3      4   5     -1
 0  201075     204      0      0      0   0    949
 1     732  116287     14      6    162   0  11335
 2       0       0  80483      0      0   0   1822
 3       0       0      3  60897      0   0     50
 4       1      40      0      0  45568   0    181
 5       0      68      0      0     12   0     67
-1       0       0      0      0      0   0      0

th: 20.5 hidden: 5 acc:0.9722726538399403 recall:0.4557823129251701 precision:0.004651485698417107 f1:0.009208989072915952
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.46      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.90      0.95    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      1.00      1.00     45790

    accuracy                           0.97    519956
   macro avg       0.83      0.89      0.82    519956
weighted avg       1.00      0.97      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21 hidden = 5

         0       1      2      3      4   5     -1
 0  201028       4      0      0      0   0   1196
 1     713  113426     14      6    162   0  14215
 2       0       0  80425      0      0   0   1880
 3       0       0      3  60897      0   0     50
 4       1      32      0      0  45429   0    328
 5       0      63      0      0     11   0     73
-1       0       0      0      0      0   0      0

th: 21 hidden: 5 acc:0.9658759587349699 recall:0.4965986394557823 precision:0.00411453049261639 f1:0.008161439991055956
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.50      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.88      0.94    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.96    519956
   macro avg       0.83      0.89      0.82    519956
weighted avg       1.00      0.96      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 21.5 hidden = 5

         0       1      2      3      4   5     -1
 0  200906       4      0      0      0   0   1318
 1     671  110087     14      6    162   0  17596
 2       0       0  80272      0      0   0   2033
 3       0       0      3  60894      0   0     53
 4       1      32      0      0  45372   0    385
 5       0      45      0      0     11   0     91
-1       0       0      0      0      0   0      0

th: 21.5 hidden: 5 acc:0.958763818476948 recall:0.6190476190476191 precision:0.00423728813559322 f1:0.008416963418582066
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.62      0.01       147
           0       1.00      0.99      1.00    202228
           1       1.00      0.86      0.92    128536
           2       1.00      0.98      0.99     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.96    519956
   macro avg       0.83      0.91      0.82    519956
weighted avg       1.00      0.96      0.98    519956

[0, 1, 2, 3, 4, 5, -1]
th = 22 hidden = 5

         0       1      2      3      4   5     -1
 0  200740       4      0      0      0   0   1484
 1     663  107036     14      6    161   0  20656
 2       0       0  79771      0      0   0   2534
 3       0       0      3  60892      0   0     55
 4       1      32      0      0  45267   0    490
 5       0      41      0      0     11   0     95
-1       0       0      0      0      0   0      0

th: 22 hidden: 5 acc:0.9513978105839724 recall:0.6462585034013606 precision:0.0037528640278106976 f1:0.007462393464514355
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.65      0.01       147
           0       1.00      0.99      0.99    202228
           1       1.00      0.83      0.91    128536
           2       1.00      0.97      0.98     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.95    519956
   macro avg       0.83      0.90      0.81    519956
weighted avg       1.00      0.95      0.97    519956

[0, 1, 2, 3, 4, 5, -1]
th = 23 hidden = 5

         0       1      2      3      4   5     -1
 0  199275       3      0      0      0   0   2950
 1     639  102966     14      6    160   0  24751
 2       0       0  78432      0      0   0   3873
 3       0       0      3  60848      0   0     99
 4       1       7      0      0  45207   0    575
 5       0      20      0      0     11   0    116
-1       0       0      0      0      0   0      0

th: 23 hidden: 5 acc:0.9379197470555201 recall:0.7891156462585034 precision:0.0035842293906810036 f1:0.007136046261265417
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.79      0.01       147
           0       1.00      0.99      0.99    202228
           1       1.00      0.80      0.89    128536
           2       1.00      0.95      0.98     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.94    519956
   macro avg       0.83      0.92      0.81    519956
weighted avg       1.00      0.94      0.96    519956

[0, 1, 2, 3, 4, 5, -1]
th = 24 hidden = 5

         0      1      2      3      4   5     -1
 0  198328      0      0      0      0   0   3900
 1     404  93820     13      6    157   0  34136
 2       0      0  76779      0      0   0   5526
 3       0      0      3  60843      0   0    104
 4       1      1      0      0  45164   0    624
 5       0      5      0      0     11   0    131
-1       0      0      0      0      0   0      0

th: 24 hidden: 5 acc:0.9147889436798499 recall:0.891156462585034 precision:0.0029490556268431597 f1:0.005878657332615329
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.89      0.01       147
           0       1.00      0.98      0.99    202228
           1       1.00      0.73      0.84    128536
           2       1.00      0.93      0.97     82305
           3       1.00      1.00      1.00     60950
           4       1.00      0.99      0.99     45790

    accuracy                           0.91    519956
   macro avg       0.83      0.92      0.80    519956
weighted avg       1.00      0.91      0.95    519956

[0, 1, 2, 3, 4, 5, -1]
th = 25 hidden = 5

         0      1      2      3      4   5     -1
 0  197952      0      0      0      0   0   4276
 1     398  85198      2      5    139   0  42794
 2       0      0  74615      0      0   0   7690
 3       0      0      3  60431      0   0    516
 4       1      0      0      0  44571   0   1218
 5       0      5      0      0     11   0    131
-1       0      0      0      0      0   0      0

th: 25 hidden: 5 acc:0.8913177268845826 recall:0.891156462585034 precision:0.002313465783664459 f1:0.004614951032198972
MULTICLASS DETECTION
              precision    recall  f1-score   support

          -1       0.00      0.89      0.00       147
           0       1.00      0.98      0.99    202228
           1       1.00      0.66      0.80    128536
           2       1.00      0.91      0.95     82305
           3       1.00      0.99      1.00     60950
           4       1.00      0.97      0.98     45790

    accuracy                           0.89    519956
   macro avg       0.83      0.90      0.79    519956
weighted avg       1.00      0.89      0.94    519956

# Média absolute threshold

In [7]:
for i in range(len(f1s)):
    print(f'Média f1 absolute th {ths[i]}: {np.mean(np.array(f1s[i]))}')

Média f1 absolute th 20: 0.6552853198197666
Média f1 absolute th 20.5: 0.6852334280616589
Média f1 absolute th 21: 0.6873741957013512
Média f1 absolute th 21.5: 0.6804262452836611
Média f1 absolute th 22: 0.6679072879012354
Média f1 absolute th 23: 0.6449035573290003
Média f1 absolute th 24: 0.603871844937095
Média f1 absolute th 25: 0.5710755955700382